"""
08_BRK_XAUUSD_15M_IBREAK_REGFILT_S01_V1_P05 -- Generated by Strategy Provisioner
Timestamp: 2026-03-10T00:05:17.864545
Directive: 08_BRK_XAUUSD_15M_IBREAK_REGFILT_S01_V1_P05

Variant A: Stop-entry breakout (10 tick buffer), 16:00 exit
Baseline: P03 (London close 16:00 exit).
"""

import pandas as pd
import numpy as np

# --- IMPORTS (Deterministic from Directive) ---
from indicators.trend.linreg_regime import linreg_regime
from indicators.trend.linreg_regime_htf import linreg_regime_htf
from indicators.trend.kalman_regime import kalman_regime
from indicators.trend.trend_persistence import trend_persistence
from indicators.trend.efficiency_ratio_regime import efficiency_ratio_regime
from indicators.volatility.volatility_regime import volatility_regime
from indicators.volatility.atr import atr
from indicators.structure.range_breakout_session import session_range_structure
from engines.filter_stack import FilterStack

# ---------------------------------------------------------------------------
# Strategy constants
# ---------------------------------------------------------------------------
_SESSION_START     = "01:00"
_SESSION_END       = "07:00"
_RANGE_QUALITY_MIN = 0.3
_RANGE_QUALITY_MAX = 2.0
_ALLOWED_REGIMES   = {0, 1}
_ENTRY_BUFFER      = 0.10    # 10 ticks
_EXIT_HOUR_UTC     = 16
_EXIT_MIN_UTC      = 0

class Strategy:

    # --- IDENTITY ---
    name = "08_BRK_XAUUSD_15M_IBREAK_REGFILT_S01_V1_P05"
    timeframe = "15m"

    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "stop_loss": {
            "fixed_points": 50,
            "type": "fixed_usd"
        },
        "take_profit": {
            "enabled": False
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "exit_rules": {
        "condition_1": {
            "timing": "london_close_16utc",
            "type": "time_based"
        },
        "condition_2": {
            "timing": "penultimate_bar_of_day",
            "type": "time_based"
        },
        "logic": "OR",
        "type": "composite"
    },
    "indicators": [
        "indicators.trend.linreg_regime",
        "indicators.trend.linreg_regime_htf",
        "indicators.trend.kalman_regime",
        "indicators.trend.trend_persistence",
        "indicators.trend.efficiency_ratio_regime",
        "indicators.volatility.volatility_regime",
        "indicators.volatility.atr",
        "indicators.structure.range_breakout_session"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "position_management": {
        "lots": 0.01
    },
    "range_definition": {
        "buffer_ticks": 10,
        "close_confirmation": False,
        "entry_trigger": "stop_breakout",
        "exit_time": "16:00",
        "range_quality_max": 2.0,
        "range_quality_min": 0.3,
        "session_end": "07:00",
        "session_start": "01:00"
    },
    "signature_version": 2,
    "state_machine": {
        "entry": {
            "direction": "long_and_short",
            "trigger": "signal_bar"
        },
        "no_reentry_after_stop": True,
        "session_reset": "new_day"
    },
    "trade_management": {
        "direction_restriction": "long_and_short",
        "max_trades_per_session": 1,
        "reentry": {
            "allowed": False
        }
    },
    "volatility_filter": {
        "allow_regime": "NORMAL,HIGH",
        "type": "volatility_regime"
    }
}
    # --- STRATEGY SIGNATURE END ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    def prepare_indicators(self, df):
        if not isinstance(df.index, pd.DatetimeIndex):
            df = df.set_index(pd.DatetimeIndex(df['timestamp']))

        # Engine-required authoritative columns
        df['atr'] = atr(df, window=14)
        vr = volatility_regime(df['atr'], window=100)
        df['volatility_regime'] = vr['regime']

        # Session range structure
        srs = session_range_structure(df, session_start=_SESSION_START,
                                      session_end=_SESSION_END)
        df['session_high']    = srs['session_high']
        df['session_low']     = srs['session_low']
        df['range_points']    = srs['range_points']
        df['break_direction'] = srs['break_direction']

        # Range quality ratio
        df['range_atr_ratio'] = df['range_points'] / df['atr']

        # Exit time flag
        df['is_exit_time'] = (df.index.hour == _EXIT_HOUR_UTC) & (df.index.minute == _EXIT_MIN_UTC)

        # Penultimate bar safety backstop
        dates = df.index.normalize()
        bar_number  = df.groupby(dates).cumcount()
        bars_in_day = df.groupby(dates)[df.columns[0]].transform('count')
        df['is_penultimate_bar'] = bar_number == (bars_in_day - 2)

        return df

    def check_entry(self, ctx):
        if not self.filter_stack.allow_trade(ctx):
            return None

        row = ctx.row

        regime = row.get('volatility_regime')
        if regime not in _ALLOWED_REGIMES:
            return None

        ratio = row.get('range_atr_ratio')
        if ratio is None or pd.isna(ratio):
            return None
        if ratio < _RANGE_QUALITY_MIN or ratio > _RANGE_QUALITY_MAX:
            return None

        high = row.get('high')
        low  = row.get('low')
        session_high = row.get('session_high')
        session_low  = row.get('session_low')

        if any(v is None or pd.isna(v) for v in [high, low, session_high, session_low]):
            return None

        long_trigger  = high >= session_high + _ENTRY_BUFFER
        short_trigger = low  <= session_low  - _ENTRY_BUFFER

        if long_trigger and short_trigger:
            return None

        if long_trigger:
            return {"signal": 1}
        if short_trigger:
            return {"signal": -1}

        return None

    def check_exit(self, ctx):
        row = ctx.row

        # Exit 1: Time-based exit
        if row.get('is_exit_time', False):
            return True

        # Exit 2: Penultimate bar safety backstop
        if row.get('is_penultimate_bar', False):
            return True

        return False
