"""
SPX02_MR — Generated by Strategy Provisioner
Timestamp: 2026-02-27T20:58:09.710399
Directive: SPX02_MR
"""

# --- IMPORTS (Deterministic from Directive) ---
from indicators.structure.highest_high import highest_high
from indicators.trend.linreg_regime import linreg_regime
from indicators.trend.linreg_regime_htf import linreg_regime_htf
from indicators.trend.kalman_regime import kalman_regime
from indicators.trend.trend_persistence import trend_persistence
from indicators.volatility.volatility_regime import volatility_regime
from indicators.volatility.atr import atr
from engines.filter_stack import FilterStack

class Strategy:
    
    # --- IDENTITY ---
    name = "SPX02_MR"
    timeframe = "1d"
    
    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "entry_logic": {
            "atr_length": 10,
            "atr_multiplier": 1.6,
            "condition": "close_less_than_hh_minus_atr",
            "lookback_bars": 5,
            "type": "volatility_pullback"
        },
        "entry_when_flat_only": True,
        "exit_logic": {
            "price_exit": "close_greater_than_hh_prev",
            "time_exit_bars": 4,
            "type": "dynamic_or_time"
        },
        "pyramiding": False,
        "reset_on_exit": True,
        "stop_loss": {
            "type": "none"
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "indicators": [
        "indicators.structure.highest_high",
        "indicators.trend.linreg_regime",
        "indicators.trend.linreg_regime_htf",
        "indicators.trend.kalman_regime",
        "indicators.trend.trend_persistence",
        "indicators.volatility.volatility_regime",
        "indicators.volatility.atr"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "signature_version": 2,
    "trade_management": {
        "direction": "long_only",
        "reentry": {
            "allowed": False
        }
    }
}
    # --- STRATEGY SIGNATURE END ---
    
    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    
    def prepare_indicators(self, df):
        """
        Compute indicators here.
        Must return the dataframe with new columns.
        """
        # Lookback from signature
        hh_lookback = self.STRATEGY_SIGNATURE["execution_rules"]["entry_logic"]["lookback_bars"]
        atr_length = self.STRATEGY_SIGNATURE["execution_rules"]["entry_logic"]["atr_length"]
        
        # 1. Highest High of previous bars (shift=1 to avoid lookahead)
        df['hh'] = highest_high(df['high'], window=hh_lookback, shift=1)
        
        # 2. ATR for volatility distance
        df['atr'] = atr(df, window=atr_length)
        
        # 3. Volatility Regime (Default window 100)
        df['volatility_regime'] = volatility_regime(df['atr'], window=100)['regime']
        
        return df

    def check_entry(self, ctx):
        """
        Return entry signal dict or None.
        e.g. {"signal": 1} for Long
        """
        # Architectural Requirement: Allow FilterStack to gate entry
        if not self.filter_stack.allow_trade(ctx):
            return None

        # Logic: Volatility Pullback
        # close < (hh - multiplier * atr)
        multiplier = self.STRATEGY_SIGNATURE["execution_rules"]["entry_logic"]["atr_multiplier"]
        
        close = ctx.row['close']
        hh = ctx.row.get('hh')
        atr_val = ctx.row.get('atr')
        
        if hh is None or atr_val is None:
            return None
            
        if close < (hh - multiplier * atr_val):
            # Direction is long_only per signature
            return {"signal": 1, "comment": "volatility_pullback"}

        return None

    def check_exit(self, ctx):
        """
        Return True to close position.
        """
        # 1. Time Exit
        max_bars = self.STRATEGY_SIGNATURE["execution_rules"]["exit_logic"]["time_exit_bars"]
        if ctx.bars_held >= max_bars:
            return True
            
        # 2. Price Exit: close > hh
        close = ctx.row['close']
        hh = ctx.row.get('hh')
        
        if hh is not None and close > hh:
            return True
            
        return False
