"""
01_MR_FX_1D_RSIAVG_TRENDFILT_S01_V1_P00 -- Generated by Strategy Provisioner

S01_V1_P00: Multi-signal mean-reversion on daily indices (JPN225, NAS100, US30).
Long-only. No stop loss. Entry on intersection of primary and secondary conditions.

Primary condition  : 3 consecutive lower closes (bearish exhaustion pattern)
Secondary gate     : UNION of any of:
  (a) ROC(5) < -1.0  (momentum oversold)
  (b) Stochastic %K(14,3) < 20  (price oversold)
  (c) RSI(2) 2-bar avg < 25  (fast RSI oversold)

Entry gate         : Primary AND secondary (intersection)
Exit               : RSI(2) > 75 (overbought) OR time exit after 4 bars
Direction          : Long only
Regime filter      : Trend regime indicators loaded (not gating — informational)
"""

import pandas as pd

# --- IMPORTS (Deterministic from Directive) ---
from indicators.momentum.stochastic import stochastic_k
from indicators.momentum.roc import roc
from indicators.momentum.rsi import rsi
from indicators.structure.highest_high import highest_high
from indicators.structure.lowest_low import lowest_low
from indicators.trend.linreg_regime import linreg_regime
from indicators.trend.linreg_regime_htf import linreg_regime_htf
from indicators.trend.kalman_regime import kalman_regime
from indicators.trend.trend_persistence import trend_persistence
from indicators.volatility.volatility_regime import volatility_regime
from indicators.volatility.atr import atr
from engines.filter_stack import FilterStack


class Strategy:

    # --- IDENTITY ---
    name = "01_MR_FX_1D_RSIAVG_TRENDFILT_S01_V1_P00"
    timeframe = "1d"

    # Directive parameters
    RSI_LENGTH         = 2
    RSI_AVG_BARS       = 2        # rolling avg of RSI(2) for deep-oversold check
    RSI_OVERSOLD_THR   = 25.0
    RSI_EXIT_OB        = 75.0

    ROC_LENGTH         = 5
    ROC_OVERSOLD_THR   = -1.0

    STOCH_K_LENGTH     = 14
    STOCH_D_LENGTH     = 3        # smoothing (smooth_period in stochastic_k)
    STOCH_OVERSOLD_THR = 20.0

    TIME_EXIT_BARS     = 4        # max bars in trade

    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "entry_logic": {
            "condition": "intersection_with_union",
            "type": "multi_signal_mean_reversion"
        },
        "entry_when_flat_only": True,
        "exit_logic": {
            "time_exit_bars": 4,
            "type": "dynamic_or_time"
        },
        "pyramiding": False,
        "reset_on_exit": True,
        "stop_loss": {
            "type": "none"
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "indicators": [
        "indicators.momentum.stochastic",
        "indicators.momentum.roc",
        "indicators.momentum.rsi",
        "indicators.structure.highest_high",
        "indicators.structure.lowest_low",
        "indicators.trend.linreg_regime",
        "indicators.trend.linreg_regime_htf",
        "indicators.trend.kalman_regime",
        "indicators.trend.trend_persistence",
        "indicators.volatility.volatility_regime",
        "indicators.volatility.atr"
    ],
    "mean_reversion_rules": {
        "entry_gate": "intersection",
        "exit_rsi_overbought": {
            "rsi_length": 2,
            "threshold": 75
        },
        "primary_condition": "three_consecutive_lower_closes",
        "roc_oversold_cross": {
            "roc_length": 5,
            "threshold": -1.0
        },
        "rsi_deep_oversold": {
            "avg_bars": 2,
            "rsi_length": 2,
            "threshold": 25
        },
        "secondary_gate": "union",
        "stochastic_oversold_cross": {
            "d_length": 3,
            "k_length": 14,
            "threshold": 20
        }
    },
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "signature_version": 2,
    "trade_management": {
        "direction": "long_only",
        "reentry": {
            "allowed": False
        }
    }
}
    # --- STRATEGY SIGNATURE END ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    def prepare_indicators(self, df):
        if not isinstance(df.index, pd.DatetimeIndex):
            df = df.set_index(pd.DatetimeIndex(df['timestamp']))

        # Engine-required authoritative columns
        df['atr'] = atr(df, window=14)
        vr = volatility_regime(df['atr'], window=100)
        df['volatility_regime'] = vr['regime']

        # Momentum indicators
        df['rsi_2']     = rsi(df['close'], period=self.RSI_LENGTH)
        # 2-bar smoothed RSI: (rsi_t + rsi_t-1) / 2
        df['rsi_2_avg'] = (df['rsi_2'] + df['rsi_2'].shift(1)) / 2
        df['roc_5']    = roc(df['close'], period=self.ROC_LENGTH)
        df['stoch_k']  = stochastic_k(
            df['high'], df['low'], df['close'],
            k_period=self.STOCH_K_LENGTH,
            smooth_period=self.STOCH_D_LENGTH
        )

        # Structure
        df['hh_10'] = highest_high(df['high'], window=10)
        df['ll_10'] = lowest_low(df['low'], window=10)

        # Primary condition: 3 consecutive lower closes
        df['three_lower_closes'] = (
            (df['close'] < df['close'].shift(1)) &
            (df['close'].shift(1) < df['close'].shift(2)) &
            (df['close'].shift(2) < df['close'].shift(3))
        )

        return df

    def check_entry(self, ctx):
        if not self.filter_stack.allow_trade(ctx):
            return None

        row = ctx.row
        direction = ctx.direction

        # Long-only — skip if already in a position
        if direction != 0:
            return None

        # Primary: 3 consecutive lower closes
        if not row.get('three_lower_closes', False):
            return None

        # Secondary union: at least one of the oversold conditions fires
        rsi_avg = row.get('rsi_2_avg')
        roc_val = row.get('roc_5')
        stoch_val = row.get('stoch_k')

        rsi_oversold   = (rsi_avg is not None and not pd.isna(rsi_avg) and rsi_avg < self.RSI_OVERSOLD_THR)
        roc_oversold   = (roc_val is not None and not pd.isna(roc_val) and roc_val < self.ROC_OVERSOLD_THR)
        stoch_oversold = (stoch_val is not None and not pd.isna(stoch_val) and stoch_val < self.STOCH_OVERSOLD_THR)

        if not (rsi_oversold or roc_oversold or stoch_oversold):
            return None

        return {"signal": 1}

    def check_exit(self, ctx):
        row = ctx.row
        direction = ctx.direction

        if direction == 0:
            return False

        # RSI overbought exit
        rsi_2 = row.get('rsi_2')
        if rsi_2 is not None and not pd.isna(rsi_2) and rsi_2 > self.RSI_EXIT_OB:
            return True

        # Time exit
        bars_held = getattr(ctx, 'bars_held', 0)
        if bars_held >= self.TIME_EXIT_BARS:
            return True

        return False
