"""
strategy_provisioner.py — Preflight Strategy Artifact Provisioner

Authority: SOP_TESTING (Stage-0 Provisioning)
Purpose:
    - Deterministically provision valid strategy artifacts from Directive.
    - Ensure Stage-0.5 Semantic Validation passes.
    - Idempotent: Can run multiple times without destructive side effects unless determining drift.

Rules:
    1. READ-ONLY on Directive.
    2. CREATE/UPDATE on strategies/<StrategyName>/.
    3. THIN TEMPLATE: Generates structural boilerplate only.
    4. NO INFERENCE: Imports strictly from directive['indicators'].
    5. SIGNATURE-ONLY UPDATE: If file exists, only update signature block and ensure imports.
    6. STRICT MARKERS: Validate marker presence and order before touching file.
    7. DETERMINISTIC IMPORTS: Inject missing imports only, no reordering.
"""

import sys
import shutil
from pathlib import Path
import json
import re

# Project Setup
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Template for strategy.py
STRATEGY_TEMPLATE = """\"\"\"
{strategy_name} — Generated by Strategy Provisioner
Timestamp: {timestamp}
Directive: {strategy_name}
\"\"\"

# --- IMPORTS (Deterministic from Directive) ---
{imports_block}

class Strategy:
    
    # --- IDENTITY ---
    name = "{strategy_name}"
    timeframe = "{timeframe}"
    
    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {signature_json}
    # --- STRATEGY SIGNATURE END ---
    # --- SIGNATURE HASH: {signature_hash} ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    @staticmethod
    def _schema_sample() -> dict:
        \"\"\"Return a representative valid signal dict for Phase 0 schema validation.
        Must match the structure returned by check_entry() when a signal fires.
        Required fields: signal (1 or -1), stop_price, entry_reference_price, entry_reason.
        Optional field:  tp_price.
        Example: {{"signal": 1, "stop_price": 0.0, "entry_reference_price": 0.0, "entry_reason": "your_reason"}}
        \"\"\"
        raise NotImplementedError(
            "_schema_sample() not implemented. "
            "Fill in to match check_entry() return structure before deployment."
        )

    def prepare_indicators(self, df):
        \"\"\"
        Compute indicators here.
        Must return the dataframe with new columns.
        \"\"\"
        return df

    def check_entry(self, ctx):
        \"\"\"
        Return signal dict or None. Required fields: signal, stop_price,
        entry_reference_price, entry_reason. Optional: tp_price.
        \"\"\"
        # Architectural Requirement: Allow FilterStack to gate entry
        if not self.filter_stack.allow_trade(ctx):
            return None

        return None

    def check_exit(self, ctx):
        \"\"\"
        Return True to close position. Use ctx.get('bars_held', 0) not ctx.bars_held.
        \"\"\"
        return False
"""

def _generate_import_lines(indicators):
    lines = []
    for ind in indicators:
        if not ind: continue
        # Clean path to module notation
        mod_path = ind.replace("\\", "/").replace("/", ".").replace(".py", "")
        
        if not mod_path.startswith("indicators."):
            mod_path = f"indicators.{mod_path}"
        
        symbol = mod_path.split(".")[-1]
        lines.append(f"from {mod_path} import {symbol}")
    return lines

def _insert_imports(content: str, required_imports: list) -> str:
    """
    Inject missing imports into content.
    - Scans for existing 'from ... import ...' lines.
    - Inserts new imports after the last existing import.
    - OR after docstring if no imports.
    - OR at top if nothing found.
    - Does NOT reorder or duplicate.
    """
    lines = content.splitlines()
    existing_imports = set()
    last_import_idx = -1
    
    # 1. Scan for existing imports (by module path, not exact string)
    import_regex = re.compile(r"^from\s+([\w\.]+)\s+import\s+\w+")
    
    existing_modules = set()
    for i, line in enumerate(lines):
        m = import_regex.match(line.strip())
        if m:
            existing_modules.add(m.group(1))
            last_import_idx = i

    imports_to_add = []
    for imp in required_imports:
        # Extract module path from the required import line
        m = import_regex.match(imp.strip())
        imp_module = m.group(1) if m else None
        if imp_module and imp_module not in existing_modules:
            imports_to_add.append(imp)
            
    if not imports_to_add:
        return content # No changes needed

    # 2. Determine Insertion Point
    insert_idx = 0
    
    if last_import_idx != -1:
        # Insert after last import
        insert_idx = last_import_idx + 1
    else:
        # No imports found. Look for docstring end.
        docstring_end_regex = re.compile(r'\"\"\"|\'\'\'')
        docstring_matches = list(docstring_end_regex.finditer(content))
        
        if len(docstring_matches) >= 2:
            # Assumes module docstring is the first block
            # We want to insert after the second match (end of docstring)
            # But converting char index to line index is tricky with just regex
            # Let's iterate lines to find docstring boundaries?
            # Simple heuristic: If line starts with triple quote and we found 2 calls,
            # assume module docstring is done.
            # Safe Fallback: Top of file (after docstring usually works by lines)
            
            # Let's find line index of second triple quote?
            count = 0
            for i, line in enumerate(lines):
                if '"""' in line or "'''" in line:
                    count += line.count('"""') + line.count("'''")
                    if count >= 2:
                        insert_idx = i + 1
                        break
    
    # 3. Inject
    # Add a newline for separation if inserting into code body
    prefix = []
    if last_import_idx == -1 and insert_idx > 0:
        prefix = [""] 
        
    lines[insert_idx:insert_idx] = prefix + imports_to_add
    
    return "\n".join(lines)

def _hash_sig_dict(signature: dict) -> str:
    """16-char hex hash of a signature dict — embedded in strategy.py as audit trace."""
    import hashlib
    canonical = json.dumps(signature, sort_keys=True, ensure_ascii=True)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


def _update_existing_strategy(file_path: Path, signature: dict, required_imports: list) -> bool:
    """
    Update existing strategy file:
    1. Validate Markers.
    2. Replace STRATEGY_SIGNATURE block.
    3. Inject missing imports via _insert_imports.
    4. Idempotency Check.
    """
    try:
        content = file_path.read_text(encoding="utf-8")
        original_content = content
        
        # 1. Validate Markers
        start_marker = "# --- STRATEGY SIGNATURE START ---"
        end_marker = "# --- STRATEGY SIGNATURE END ---"
        
        if content.count(start_marker) != 1:
            raise ValueError(f"File must contain exactly one START marker. Found {content.count(start_marker)}")
        if content.count(end_marker) != 1:
            raise ValueError(f"File must contain exactly one END marker. Found {content.count(end_marker)}")
            
        start_idx = content.find(start_marker)
        end_idx = content.find(end_marker)
        
        if start_idx >= end_idx:
             raise ValueError("Malformed markers: START appears after END.")

        # 1.5. Drift Detection: compare existing vs incoming signature
        _sig_drifted = True
        _existing_sig = None
        try:
            sig_block_text = content[start_idx + len(start_marker):end_idx]
            sig_match = re.search(r'STRATEGY_SIGNATURE\s*=\s*(\{.*\})', sig_block_text, re.DOTALL)
            if sig_match:
                import ast as _ast
                _existing_sig = _ast.literal_eval(sig_match.group(1).strip())
                if json.dumps(_existing_sig, sort_keys=True) == json.dumps(signature, sort_keys=True):
                    _sig_drifted = False
        except Exception:
            pass  # cannot parse existing signature; assume drifted

        # 1.6. Embedded hash audit: detect post-provision manual mutation
        _hash_marker_re = re.compile(r'# --- SIGNATURE HASH: ([0-9a-f]{16}) ---')
        _hash_search = _hash_marker_re.search(content)
        _stored_sig_hash = _hash_search.group(1) if _hash_search else None

        if _stored_sig_hash is not None and _existing_sig is not None:
            _current_hash = _hash_sig_dict(_existing_sig)
            if _current_hash != _stored_sig_hash:
                print(
                    f"[PROVISION] WARNING: Strategy mutated post-provision (signature drift). "
                    f"stored_hash={_stored_sig_hash} current_hash={_current_hash}"
                )

        if _sig_drifted:
            print("[PROVISION] SIGNATURE DRIFT DETECTED — patching STRATEGY_SIGNATURE block only.")

        # 2. Update Signature Block
        sig_json = json.dumps(signature, indent=4, sort_keys=True)
        
        # Convert JSON literals to Python literals for valid code generation
        # NOTE: This replaces values only (preceded by ": ") to avoid touching keys
        sig_json = sig_json.replace(": true", ": True").replace(": false", ": False").replace(": null", ": None")

        new_block = f"{start_marker}\n    STRATEGY_SIGNATURE = {sig_json}\n    {end_marker}"
        
        # Precise Regex Replace
        pattern = re.compile(f"{re.escape(start_marker)}.*?{re.escape(end_marker)}", re.DOTALL)
        content = pattern.sub(new_block, content, count=1)
        
        # 3. Remove legacy import path (kept for backward compatibility only).
        # Canonical source is engines.filter_stack.
        content = re.sub(
            r"^\s*from\s+tools\.pipeline_utils\s+import\s+FilterStack\s*$\n?",
            "",
            content,
            flags=re.MULTILINE,
        )

        # 4. Inject Imports
        content = _insert_imports(content, required_imports)

        # 4.5. Update embedded signature hash comment
        new_sig_hash = _hash_sig_dict(signature)
        new_hash_line = f"# --- SIGNATURE HASH: {new_sig_hash} ---"
        if _hash_marker_re.search(content):
            content = _hash_marker_re.sub(new_hash_line, content, count=1)
        else:
            # No hash comment yet (legacy strategy) — insert after END marker
            content = content.replace(
                end_marker,
                f"{end_marker}\n    {new_hash_line}",
                1,
            )
            print(f"[PROVISION] SIGNATURE HASH INJECTED: {new_sig_hash} (legacy strategy backfilled)")

        # 5. Idempotency Check
        if content != original_content:
            file_path.write_text(content, encoding="utf-8")
            print(f"[PROVISION] Updated strategy signature: {file_path}")
        else:
            print(f"[PROVISION] Strategy signature already up to date: {file_path}")
            
        return True

    except Exception as e:
        print(f"[PROVISION] Update Failed: {e}")
        return False

# ... (removed import yaml below)

from tools.directive_utils import load_directive_yaml, get_key_ci
from tools.directive_schema import normalize_signature, SIGNATURE_SCHEMA_VERSION


def _check_schema_sample(strategy_file: Path) -> None:
    """Post-provision gate: inspect strategy file for _schema_sample() compliance.

    Three outcomes:
      SCHEMA_SAMPLE_OK          — method present and implemented (no NotImplementedError)
      SCHEMA_SAMPLE_STUB        — method present but still raises NotImplementedError
      SCHEMA_SAMPLE_MISSING     — method absent entirely

    STUB and MISSING both block Phase 0 startup (ENFORCE_SCHEMA_SAMPLE=True).
    This warning at provision time gives the developer early notice.
    """
    try:
        content = strategy_file.read_text(encoding="utf-8")
        has_method = "_schema_sample" in content
        has_stub   = has_method and "NotImplementedError" in content

        if not has_method:
            print(
                f"[PROVISION] SCHEMA_SAMPLE_MISSING  {strategy_file.name}"
                f" — Phase 0 will block deployment. Add _schema_sample() alongside check_entry()."
            )
        elif has_stub:
            print(
                f"[PROVISION] SCHEMA_SAMPLE_STUB  {strategy_file.name}"
                f" — stub detected (NotImplementedError). Implement before deployment."
            )
        else:
            print(f"[PROVISION] SCHEMA_SAMPLE_OK  {strategy_file.name}")
    except Exception as e:
        print(f"[PROVISION] WARNING: could not inspect _schema_sample: {e}")


def provision_strategy(directive_path: str) -> bool:
    """
    Provision strategy artifacts from directive.
    Returns True if successful/exists, False on failure.
    """
    try:
        d_path = Path(directive_path)
        if not d_path.exists():
            print(f"[PROVISION] Directive not found: {d_path}")
            return False

        # 1. Parse Directive (Direct YAML Load via Shared Utility)
        d_conf = load_directive_yaml(d_path)
        
        # 2. Extract Identity & Signature Elements
        # Handle snake_case vs TitleCase key variations if necessary.
        # Direct YAML keys are usually case-sensitive from the file.
        # We look for standard keys.
        
        # Identity - Check "test" block first, then root
        test_block = get_key_ci(d_conf, "test") or {}
        
        s_name = get_key_ci(test_block, "strategy") or get_key_ci(d_conf, "strategy")
        timeframe = get_key_ci(test_block, "timeframe") or get_key_ci(d_conf, "timeframe")
        
        if not s_name:
            print("[PROVISION] Directive missing 'Strategy' field (checked root and 'test' block).")
            return False
        
        # 3. Target Directory
        strategy_dir = PROJECT_ROOT / "strategies" / s_name
        strategy_file = strategy_dir / "strategy.py"
        
        # 4. Signature Construction (Single Authority: directive_schema.py)
        try:
            signature = normalize_signature(d_conf)
        except ValueError as e:
            print(f"[PROVISION] FATAL: {e}")
            return False
        
        # Extract indicators (needed for import generation)
        indicators = signature.get("indicators", [])
        if isinstance(indicators, str):
            indicators = [indicators]

        
        # 5. Build Import Requirements
        import_lines = _generate_import_lines(indicators)
        import_lines.append("from engines.filter_stack import FilterStack")
        
        # 6. Check Existence
        if strategy_file.exists():
            ok = _update_existing_strategy(strategy_file, signature, import_lines)
            _check_schema_sample(strategy_file)
            return (ok, False)
        else:
            print(f"[PROVISION] Creating new strategy: {s_name}")
            strategy_dir.mkdir(parents=True, exist_ok=True)

            # 7. Generate Content
            from datetime import datetime

            sig_json = json.dumps(signature, indent=4, sort_keys=True)
            sig_json = sig_json.replace(": true", ": True").replace(": false", ": False").replace(": null", ": None")

            content = STRATEGY_TEMPLATE.format(
                strategy_name=s_name,
                timestamp=datetime.now().isoformat(),
                imports_block="\n".join(import_lines),
                timeframe=timeframe,
                signature_json=sig_json,
                signature_hash=_hash_sig_dict(signature),
            )

            # 8. Write File
            with open(strategy_file, "w", encoding="utf-8") as f:
                f.write(content)

            print(f"[PROVISION] SUCCESS: {strategy_file}")
            _check_schema_sample(strategy_file)
            return (True, True)

    except Exception as e:
        print(f"[PROVISION] FAILED: {e}")
        return (False, False)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python tools/strategy_provisioner.py <DIRECTIVE_PATH>")
        sys.exit(1)
    
    provision_strategy(sys.argv[1])
