"""
08_BRK_XAUUSD_15M_IBREAK_REGFILT_S01_V1_P00 -- Generated by Strategy Provisioner
Timestamp: 2026-03-09T17:32:10.117590
Directive: 08_BRK_XAUUSD_15M_IBREAK_REGFILT_S01_V1_P00

S01_V1_P00: Asian Session Breakout baseline.

Thesis: XAUUSD consolidates during the Asian session (01:00-07:00 UTC).
London/NY open injects directional liquidity that breaks this range.
On NORMAL and HIGH volatility days, breakouts are genuine momentum moves.

Setup      : Asian session range computed from 01:00-07:00 UTC bars
Entry      : Close breaks above session high (long) or below session low (short)
             after 07:00 UTC, with close confirmation
Vol gate   : NORMAL (0) and HIGH (1) regimes only (LOW excluded)
Range gate : Asian range must be 0.3-2.0x ATR (filter noise and spent ranges)
Exit       : Penultimate bar of day (EOD close)
Risk       : Fixed $50 stop loss, single trade per session, bidirectional
"""

import pandas as pd
import numpy as np

# --- IMPORTS (Deterministic from Directive) ---
from indicators.trend.linreg_regime import linreg_regime
from indicators.trend.linreg_regime_htf import linreg_regime_htf
from indicators.trend.kalman_regime import kalman_regime
from indicators.trend.trend_persistence import trend_persistence
from indicators.trend.efficiency_ratio_regime import efficiency_ratio_regime
from indicators.volatility.volatility_regime import volatility_regime
from indicators.volatility.atr import atr
from indicators.structure.range_breakout_session import session_range_structure
from engines.filter_stack import FilterStack

# ---------------------------------------------------------------------------
# Strategy constants
# ---------------------------------------------------------------------------
_SESSION_START     = "01:00"
_SESSION_END       = "07:00"
_RANGE_QUALITY_MIN = 0.3   # Min Asian range as multiple of ATR
_RANGE_QUALITY_MAX = 2.0   # Max Asian range as multiple of ATR
_ALLOWED_REGIMES   = {0, 1} # 0=normal, 1=high; -1=low excluded

class Strategy:

    # --- IDENTITY ---
    name = "08_BRK_XAUUSD_15M_IBREAK_REGFILT_S01_V1_P00"
    timeframe = "15m"

    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "stop_loss": {
            "fixed_points": 50,
            "type": "fixed_usd"
        },
        "take_profit": {
            "enabled": False
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "exit_rules": {
        "timing": "penultimate_bar_of_day",
        "type": "time_based"
    },
    "indicators": [
        "indicators.trend.linreg_regime",
        "indicators.trend.linreg_regime_htf",
        "indicators.trend.kalman_regime",
        "indicators.trend.trend_persistence",
        "indicators.trend.efficiency_ratio_regime",
        "indicators.volatility.volatility_regime",
        "indicators.volatility.atr",
        "indicators.structure.range_breakout_session"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "position_management": {
        "lots": 0.01
    },
    "range_definition": {
        "close_confirmation": True,
        "range_quality_max": 2.0,
        "range_quality_min": 0.3,
        "session_end": "07:00",
        "session_start": "01:00"
    },
    "signature_version": 2,
    "state_machine": {
        "entry": {
            "direction": "long_and_short",
            "trigger": "signal_bar"
        },
        "no_reentry_after_stop": True,
        "session_reset": "new_day"
    },
    "trade_management": {
        "direction_restriction": "long_and_short",
        "max_trades_per_session": 1,
        "reentry": {
            "allowed": False
        }
    },
    "volatility_filter": {
        "allow_regime": "NORMAL,HIGH",
        "type": "volatility_regime"
    }
}
    # --- STRATEGY SIGNATURE END ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)


    def prepare_indicators(self, df):
        if not isinstance(df.index, pd.DatetimeIndex):
            df = df.set_index(pd.DatetimeIndex(df['timestamp']))

        # Engine-required authoritative columns
        df['atr'] = atr(df, window=14)
        vr = volatility_regime(df['atr'], window=100)
        df['volatility_regime'] = vr['regime']

        # Session range structure (Asian session breakout detection)
        srs = session_range_structure(df, session_start=_SESSION_START,
                                      session_end=_SESSION_END)
        df['session_high']    = srs['session_high']
        df['session_low']     = srs['session_low']
        df['range_points']    = srs['range_points']
        df['break_direction'] = srs['break_direction']

        # Range quality ratio: Asian range as multiple of ATR
        df['range_atr_ratio'] = df['range_points'] / df['atr']

        # Session bar labels (exit backstop)
        dates = df.index.normalize()
        bar_number  = df.groupby(dates).cumcount()
        bars_in_day = df.groupby(dates)[df.columns[0]].transform('count')
        df['is_penultimate_bar'] = bar_number == (bars_in_day - 2)

        return df

    def check_entry(self, ctx):
        if not self.filter_stack.allow_trade(ctx):
            return None

        row = ctx.row

        # Gate 0: Volatility regime — NORMAL or HIGH only
        regime = row.get('volatility_regime')
        if regime not in _ALLOWED_REGIMES:
            return None

        # Gate 1: Breakout direction detected (non-zero after session end)
        break_dir = row.get('break_direction', 0)
        if break_dir == 0:
            return None

        # Gate 2: Range quality — Asian range must be meaningful
        ratio = row.get('range_atr_ratio')
        if ratio is None or pd.isna(ratio):
            return None
        if ratio < _RANGE_QUALITY_MIN or ratio > _RANGE_QUALITY_MAX:
            return None

        # Gate 3: Close confirmation — close must be beyond the range
        close = row.get('close')
        session_high = row.get('session_high')
        session_low  = row.get('session_low')

        if any(v is None or pd.isna(v) for v in [close, session_high, session_low]):
            return None

        if break_dir == 1 and close > session_high:
            return {"signal": 1}
        if break_dir == -1 and close < session_low:
            return {"signal": -1}

        return None

    def check_exit(self, ctx):
        row = ctx.row

        if row.get('is_penultimate_bar', False):
            return True

        return False
