"""
45_STR_XAU_1H_CHOCH_S01_V2_P00 — Generated by Strategy Provisioner
Timestamp: 2026-04-14T12:45:31.800302
Directive: 45_STR_XAU_1H_CHOCH_S01_V2_P00
"""

# --- IMPORTS (Deterministic from Directive) ---
from indicators.volatility.atr import atr
from indicators.structure.choch import choch
from engines.filter_stack import FilterStack

class Strategy:
    
    # --- IDENTITY ---
    name = "45_STR_XAU_1H_CHOCH_S01_V2_P00"
    timeframe = "1h"
    
    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "entry_logic": {
            "type": "choch_structural_break"
        },
        "entry_when_flat_only": True,
        "exit_logic": {
            "type": "sl_or_tp"
        },
        "pyramiding": False,
        "reset_on_exit": True,
        "stop_loss": {
            "atr_multiplier": 1.5,
            "type": "atr_multiple"
        },
        "take_profit": {
            "atr_multiplier": 3.0,
            "enabled": True,
            "type": "atr_multiple"
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "exit_rules": {
        "type": "sl_tp"
    },
    "indicators": [
        "indicators.volatility.atr",
        "indicators.structure.choch"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "position_management": {
        "lots": 0.01
    },
    "signal_version": 3,
    "signature_version": 2,
    "state_machine": {
        "entry": {
            "direction": "long_and_short",
            "trigger": "signal_bar"
        },
        "no_reentry_after_stop": True,
        "session_reset": "none"
    },
    "trade_management": {
        "direction_restriction": "long_and_short",
        "reentry": {
            "allowed": True
        },
        "session_reset": "none"
    },
    "version": 1
}
    # --- STRATEGY SIGNATURE END ---
    # --- SIGNATURE HASH: 099572ba0806b148 ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    # Fixed hyperparameters — identical across ideas 43 (USDJPY), 44 (BTCUSD),
    # and 45 (XAUUSD) to preserve cross-asset comparability.
    _ATR_WINDOW  = 14
    _SL_ATR_MULT = 1.5
    _TP_ATR_MULT = 3.0

    @staticmethod
    def _schema_sample() -> dict:
        return {
            "signal": 1,
            "stop_price": 0.0,
            "tp_price": 0.0,
            "entry_reference_price": 0.0,
            "entry_reason": "choch_bullish_break",
        }

    def prepare_indicators(self, df):
        """Compute ATR(14) and CHOCH structural events.

        No trend filter, no volatility filter, no session filter.
        CHOCH event detection only (first structural break, edge-triggered).
        """
        df['atr'] = atr(df, self._ATR_WINDOW)
        df = choch(df)
        return df

    def check_entry(self, ctx):
        """Enter on the bar that prints a CHOCH event (choch_event != 0).

        +1 → long; -1 → short. Symmetric long/short treatment.
        SL = close -/+ 1.5 * ATR; TP = close +/- 3.0 * ATR.
        """
        if not self.filter_stack.allow_trade(ctx):
            return None

        event = int(ctx.require('choch_event'))
        if event == 0:
            return None

        close = float(ctx.require('close'))
        atr_val = float(ctx.require('atr'))
        if atr_val <= 0 or not (atr_val == atr_val):  # NaN guard
            return None

        if event == 1:
            reason = "choch_bullish_break"
        else:
            reason = "choch_bearish_break"

        return {
            "signal": event,
            "entry_reference_price": close,
            "entry_reason": reason,
        }

    def check_exit(self, ctx):
        """Exit is managed by the engine via stop_price / tp_price. No strategy-side exit."""
        return False

# --- CAPABILITY REQUIREMENTS START ---
REQUIRED_CAPABILITIES = [
    "execution.entry.v1",
    "execution.exit.v1",
]
REQUIRED_CONTRACT_IDS = [
    "sha256:378a1931d1edebd8e736b402f010eaed29e9f47412e7c522e6c49964f6c56704",
]
# --- CAPABILITY REQUIREMENTS END ---
