"""
ORB_FX_01 — Generated by Strategy Provisioner
Timestamp: 2026-02-26T18:27:45.433787
Directive: ORB_FX_01
"""

# --- IMPORTS (Deterministic from Directive) ---
from indicators.structure.highest_high import highest_high
from indicators.structure.lowest_low import lowest_low
from indicators.volatility.volatility_regime import volatility_regime
from indicators.volatility.atr import atr
from engines.filter_stack import FilterStack

class Strategy:
    
    # --- IDENTITY ---
    name = "ORB_FX_01"
    timeframe = "1h"
    
    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "cancel_opposite_on_fill": True,
        "stop_loss": {
            "type": "session_opposite_range"
        },
        "take_profit": {
            "enabled": False
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "exit_rules": {
        "time_exit": {
            "enabled": True,
            "execution": "market",
            "time": "18:00"
        }
    },
    "indicators": [
        "indicators.structure.highest_high",
        "indicators.structure.lowest_low",
        "indicators.volatility.volatility_regime",
        "indicators.volatility.atr"
    ],
    "order_placement": {
        "execution_timeframe": "1h",
        "orders": [
            {
                "condition": "close >= session_high",
                "direction": "long"
            },
            {
                "condition": "close <= session_low",
                "direction": "short"
            }
        ],
        "price_validation": {
            "ignore_pre_breakouts": True
        },
        "trigger": "close_outside_frozen_range",
        "type": "close_confirm"
    },
    "range_definition": {
        "calculation": {
            "source": "timeframe_data",
            "timeframe": "1h"
        },
        "freeze_at": "06:00",
        "include_window_end_bar": True,
        "window_end": "06:00",
        "window_start": "03:00"
    },
    "signature_version": 2,
    "trade_management": {
        "direction_restriction": "none",
        "max_trades_per_session": 2,
        "no_reentry_after_second_trade": True,
        "reentry": {
            "allowed": True,
            "allowed_until_trade_count": 1,
            "place_both_orders_on_reentry": True,
            "reuse_original_range": True
        },
        "trade_counting_mode": "filled_orders"
    }
}
    # --- STRATEGY SIGNATURE END ---
    
    # --- DIRECTIVE PARAMETERS ---
    RANGE_START_HOUR = 3   # 03:00 UTC
    RANGE_END_HOUR   = 6   # 06:00 UTC (inclusive per include_window_end_bar)
    TIME_EXIT_HOUR   = 18  # 18:00 UTC market exit
    MAX_TRADES_PER_SESSION = 2
    
    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)
        
        # Session state (reset each new trading day)
        self._session_high = None
        self._session_low = None
        self._range_frozen = False
        self._current_date = None
        self._session_trade_count = 0

    
    def prepare_indicators(self, df):
        """
        Compute ATR and volatility regime. 
        Note: Session high/low are computed dynamically in check_entry
        per the "Minimal Correction Patch" requirement.
        """
        # ATR for engine stop contract and sizing
        df['atr'] = atr(df, window=14)
        
        # Volatility regime (Required by FilterStack and Emitter)
        vol_df = volatility_regime(df['atr'])
        df['volatility_regime'] = vol_df['regime']
        
        return df

    def _get_bar_hour(self, row):
        """Extract hour from timestamp column."""
        ts = row.get('timestamp', row.get('time', None))
        if ts is None:
            return None
        import pandas as pd
        if not isinstance(ts, pd.Timestamp):
            ts = pd.Timestamp(ts)
        return ts.hour

    def _get_bar_date(self, row):
        """Extract date from timestamp column."""
        ts = row.get('timestamp', row.get('time', None))
        if ts is None:
            return None
        import pandas as pd
        if not isinstance(ts, pd.Timestamp):
            ts = pd.Timestamp(ts)
        return ts.date()

    def _reset_session(self):
        """Reset all session state for a new trading day."""
        self._session_high = None
        self._session_low = None
        self._range_frozen = False
        self._session_trade_count = 0

    def _update_range(self, row):
        """
        Accumulate session high/low during range window.
        """
        bar_high = row.get('high', row.get('close'))
        bar_low = row.get('low', row.get('close'))
        
        if self._session_high is None or bar_high > self._session_high:
            self._session_high = bar_high
        if self._session_low is None or bar_low < self._session_low:
            self._session_low = bar_low

    def check_entry(self, ctx):
        """
        Opening Range Breakout on 1h bars (close-confirm style).
        
        Phase 1 (03:00–06:00 inclusive): Accumulate session high/low.
                 Range freezes at close of 06:00 bar.
        Phase 2 (after freeze, before 18:00): Close-confirm breakout.
        
        Long:  close >= session_high → entry, SL = session_low
        Short: close <= session_low  → entry, SL = session_high
        """
        # Architectural Requirement: FilterStack gate
        if not self.filter_stack.allow_trade(ctx):
            return None

        row = ctx.row
        direction = ctx.direction
        bar_hour = self._get_bar_hour(row)
        bar_date = self._get_bar_date(row)

        if bar_hour is None or bar_date is None:
            return None

        # --- SESSION RESET on new day ---
        if bar_date != self._current_date:
            self._reset_session()
            self._current_date = bar_date

        # --- PHASE 1: RANGE ACCUMULATION (03:00–06:00 inclusive) ---
        if self.RANGE_START_HOUR <= bar_hour <= self.RANGE_END_HOUR:
            self._update_range(row)
            # Freeze at the close of the 06:00 bar
            if bar_hour == self.RANGE_END_HOUR:
                self._range_frozen = True
            return None

        # --- PHASE 2: CLOSE-CONFIRM BREAKOUT (after freeze, before time exit) ---
        if not self._range_frozen:
            return None

        if bar_hour >= self.TIME_EXIT_HOUR:
            return None  # Past time exit window, no new entries

        if self._session_high is None or self._session_low is None:
            return None

        if self._session_trade_count >= self.MAX_TRADES_PER_SESSION:
            return None  # Hard cap reached

        # Range validity
        if self._session_high <= self._session_low:
            return None

        close = row.get('close')
        if close is None:
            return None

        # --- LONG BREAKOUT (close-confirm) ---
        if close >= self._session_high and direction != 1:
            self._session_trade_count += 1
            return {"signal": 1, "stop_price": self._session_low}

        # --- SHORT BREAKOUT (close-confirm) ---
        if close <= self._session_low and direction != -1:
            self._session_trade_count += 1
            return {"signal": -1, "stop_price": self._session_high}

        return None

    def check_exit(self, ctx):
        """
        Exit rules:
          1. Time exit at 18:00 UTC (market close)
          2. Stop loss handled by engine via stop_price at entry
        """
        direction = ctx.direction
        if direction == 0:
            return False

        row = ctx.row
        bar_hour = self._get_bar_hour(row)

        if bar_hour is None:
            return False

        # Time exit: close position at or after 18:00
        if bar_hour >= self.TIME_EXIT_HOUR:
            return True

        return False
