"""Markdown renderer for the Family Analysis Report.

Renders a single markdown document from per-variant pre-computed analytics.
The orchestrator (`tools/family_report.py`) is responsible for gathering data
and computing per-variant metrics; this module is rendering-only.

Wrapper-first per FAMILY_REPORT_IMPLEMENTATION_PLAN.md Rule 4: this module
performs no analytics — all numbers come pre-computed in the `family_data`
dict from the orchestrator.

Section order (matches `outputs/family_psbrk_24m_report.md`):
  1. Executive ranking
  2. Core metrics + Δ vs parent
  3. Lineage (parent → child diff)
  4. Structural attribution
       4a. Concentration / tail
       4b. Direction × Session / Trend / Volatility cell matrices
       4c. Yearwise stability
       4d. Streaks
       4e. Rolling stability
       4f. Early/late
       4g. Drawdown clusters
  5. Per-variant verdict
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def render(family_data: dict) -> str:
    """Top-level: return the full markdown report for `family_data`."""
    lines: list[str] = []
    lines.extend(_render_header(family_data))
    lines.extend(_render_dedup_notice(family_data))
    lines.extend(_render_window_warnings(family_data))
    lines.extend(_render_executive_ranking(family_data))
    lines.extend(_render_promotion_summary(family_data))
    lines.extend(_render_core_metrics(family_data))
    lines.extend(_render_parent_delta(family_data))
    lines.extend(_render_prior_run_delta(family_data))
    lines.extend(_render_lineage(family_data))
    lines.extend(_render_concentration(family_data))
    lines.extend(_render_session(family_data))
    lines.extend(_render_direction(family_data))
    lines.extend(_render_regime_cells(family_data))
    lines.extend(_render_yearwise(family_data))
    lines.extend(_render_streaks(family_data))
    lines.extend(_render_rolling(family_data))
    lines.extend(_render_early_late(family_data))
    lines.extend(_render_drawdown(family_data))
    lines.extend(_render_verdicts(family_data))
    lines.append("")
    lines.append(f"*Generated by `tools/family_report.py` at {family_data.get('generated_at', '')}*")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Section renderers
# ---------------------------------------------------------------------------

def _render_header(d: dict) -> list[str]:
    win = d.get("window", {}) or {}
    dedup = d.get("dedup") or {}
    out = [
        f"# Family Analysis — {d.get('prefix', '?')}",
        "",
        f"**Variants:** {len(d.get('variants', []))}  ",
        f"**Window (median):** {win.get('start', '?')} → {win.get('end', '?')}  ",
        f"**Generated:** {d.get('generated_at', '')}",
    ]
    if dedup.get("enabled"):
        out.append(
            f"**Filter:** `--latest-only` — kept "
            f"{dedup.get('kept_rows', '?')} / "
            f"{dedup.get('input_rows', '?')} MF rows (max rowid per strategy, "
            f"is_current ≠ 0)"
        )
    out.extend(["", "---", ""])
    return out


def _render_dedup_notice(d: dict) -> list[str]:
    """Surface latest-only ambiguities (strategies with >1 current row).

    These are pre-existing supersession-bookkeeping gaps that --latest-only
    papers over by picking max(rowid). Listing them tells the operator
    where to invoke ``tools/rerun_backtest.py`` or otherwise mark the
    older rows superseded.
    """
    dedup = d.get("dedup") or {}
    if not dedup.get("enabled"):
        return []
    ambig = dedup.get("ambiguities") or []
    if not ambig:
        return []
    out = [
        "## ⚠ Latest-Only Ambiguities",
        "",
        "These strategies have >1 current Master Filter row after the "
        "`is_current ≠ 0` filter. `--latest-only` kept the highest-rowid "
        "row per strategy; the others remain in the ledger and should be "
        "formally superseded.",
        "",
        "| Strategy | Current rows |",
        "|---|---|",
    ]
    for a in ambig:
        out.append(f"| `{a.get('strategy', '?')}` | {a.get('n_current', '?')} |")
    out.append("")
    return out


def _render_window_warnings(d: dict) -> list[str]:
    warnings = d.get("window_warnings", [])
    if not warnings:
        return []
    out = ["## ⚠ Cross-Window Comparability Warnings", ""]
    for w in warnings:
        out.append(f"- {w}")
    out.append("")
    out.append("Rows flagged `⚠` in tables below ran on a different window than the family median.")
    out.append("Their metrics are not directly comparable.")
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_executive_ranking(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    # Rank: SQN desc, then DD asc, then PF desc, then expectancy desc
    def _key(v):
        r = v.get("row", {}) or {}
        return (
            -_f(r.get("sqn")),
            _f(r.get("max_dd_pct")),
            -_f(r.get("profit_factor")),
            -_f(r.get("expectancy")),
        )
    ranked = sorted(variants, key=_key)

    out = ["## 1. Executive Ranking", "",
           "Ranked by SQN ↓, then DD% ↑, then PF ↓, then Expectancy ↓.",
           "",
           "| # | Variant | SQN | DD% | PF | Expectancy | Status |",
           "|---|---------|-----|-----|----|-----------|--------|"]
    for i, v in enumerate(ranked, 1):
        r = v.get("row", {}) or {}
        verdict = (v.get("verdict") or {}).get("effective_status", "—")
        marker = " ⚠" if not v.get("in_window", True) else ""
        out.append(
            f"| {i} | {_short_name(v['directive_id'])}{marker} "
            f"| {_f(r.get('sqn')):.2f} "
            f"| {_f(r.get('max_dd_pct')):.2f}% "
            f"| {_f(r.get('profit_factor')):.2f} "
            f"| ${_f(r.get('expectancy')):.2f} "
            f"| {verdict} |"
        )
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_promotion_summary(d: dict) -> list[str]:
    """Promotion Summary — separates "best raw edge" from "best deployable".

    Two blocks with deliberately different authority:

      - Block A: groups variants by **canonical** status only
        (`verdict.status` from `tools/filter_strategies.
        _compute_candidate_status` via `family_verdicts`). Status labels
        are NEVER altered by soft flags. An empty group renders "None"
        — no hidden empties.

      - Block B: soft-overlay flags (tail concentration, body deficit,
        long flat, loss streak, stall decay). These ANNOTATE only — they
        do not move a variant between Block A groups.

    This split makes the tension explicit: a variant can rank #1 in the
    Executive Ranking by raw quality (e.g., PSBRK V4 P14 SQN 2.87) and
    still sit in `FAIL` here because its DD breaches the canonical 40%
    gate. That gap is one of the main reasons this reporting layer
    exists.
    """
    variants = d.get("variants", []) or []
    if not variants:
        return []

    # ----- Block A — canonical status groups -----
    groups: dict[str, list[dict]] = {"CORE": [], "WATCH": [], "FAIL": []}
    other: list[tuple[str, dict]] = []  # RESERVE / LIVE / UNKNOWN — surface verbatim
    for v in variants:
        verdict = v.get("verdict") or {}
        status = str(verdict.get("status") or "UNKNOWN").upper()
        if status in groups:
            groups[status].append(v)
        else:
            other.append((status, v))

    out = [
        "## 2. Promotion Summary",
        "",
        "Answers the question **\"what is actually promotable?\"** — distinct "
        "from the Executive Ranking above, which answers \"which variant "
        "has the strongest raw edge?\" A variant can lead the ranking and "
        "still sit in FAIL here.",
        "",
        "### Block A — Canonical Promotion Status",
        "",
        "Source: `tools/filter_strategies._compute_candidate_status` "
        "(canonical authority). Soft flags below in Block B do not move "
        "variants between groups here.",
        "",
    ]

    for status_label in ("CORE", "WATCH", "FAIL"):
        members = groups[status_label]
        out.append(f"**{status_label}** ({len(members)}):")
        if not members:
            out.append("")
            out.append("- None")
            out.append("")
            continue
        out.append("")
        for v in members:
            row = v.get("row") or {}
            sqn = _f(row.get("sqn"))
            dd  = _f(row.get("max_dd_pct"))
            pf  = _f(row.get("profit_factor"))
            out.append(
                f"- `{_short_name(v.get('directive_id', '?'))}` — "
                f"SQN {sqn:.2f}, DD {dd:.2f}%, PF {pf:.2f}"
            )
        out.append("")

    if other:
        # Don't lose visibility of RESERVE / LIVE / UNKNOWN — they should
        # appear if they exist, but they are not promotion candidates in
        # the usual sense.
        out.append(f"**Other** ({len(other)}):")
        out.append("")
        for status_label, v in other:
            out.append(
                f"- `{_short_name(v.get('directive_id', '?'))}` "
                f"(status: {status_label})"
            )
        out.append("")

    # ----- Block B — Soft risk overlays -----
    out.extend([
        "### Block B — Soft Risk Overlays (annotation only)",
        "",
        "Informational flags that do **not** alter the canonical labels "
        "above. They identify risk that a passing label may hide (tail "
        "dependence, body deficit, flat periods, loss streaks, second-"
        "half decay).",
        "",
    ])

    rows: list[tuple[str, list[str]]] = []
    for v in variants:
        verdict_trips = list((v.get("verdict") or {}).get("soft_gate_trips") or [])
        extra = list(v.get("additional_soft_flags") or [])
        merged = _merge_soft_flags(verdict_trips + extra)
        rows.append((v.get("directive_id", "?"), merged))

    any_fired = any(flags for _, flags in rows)
    if not any_fired:
        out.append("_No soft overlays fired across the family._")
        out.append("")
    else:
        for vid, flags in rows:
            if not flags:
                continue
            out.append(f"**`{_short_name(vid)}`**")
            for f in flags:
                # The Phase A helpers already prefix with ⚠ in some cases;
                # bullet-list either way.
                out.append(f"- {f}")
            out.append("")

        # Compact list of variants with NO flags so the reader knows the
        # set is complete (avoids "is this missing?" anxiety).
        clean = [vid for vid, flags in rows if not flags]
        if clean:
            out.append("**Clean (no soft overlays):**")
            out.append(", ".join(f"`{_short_name(v)}`" for v in clean))
            out.append("")

    out.append("---")
    out.append("")
    return out


def _merge_soft_flags(items: list[str]) -> list[str]:
    """Deduplicate soft-flag trip messages while preserving order.

    `verdict.soft_gate_trips` from `family_verdicts._evaluate_soft_gates`
    and the Phase A helpers can overlap on tail/body content but with
    slightly different phrasing. Keep first-seen wording per message
    string; suppress exact duplicates only.
    """
    seen: set[str] = set()
    out: list[str] = []
    for s in items:
        if not isinstance(s, str):
            continue
        key = s.strip()
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(s)
    return out


def _render_core_metrics(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    out = ["## 3. Core Metrics", "",
           "| Variant | Trades | Net PnL | PF | SQN | Sharpe | DD% | R/DD | Expectancy | Avg Bars |",
           "|---------|--------|---------|----|-----|--------|-----|------|-----------|----------|"]
    for v in variants:
        r = v.get("row", {}) or {}
        marker = " ⚠" if not v.get("in_window", True) else ""
        out.append(
            f"| {_short_name(v['directive_id'])}{marker} "
            f"| {int(_f(r.get('total_trades')))} "
            f"| ${_f(r.get('total_net_profit')):.2f} "
            f"| {_f(r.get('profit_factor')):.2f} "
            f"| {_f(r.get('sqn')):.2f} "
            f"| {_f(r.get('sharpe_ratio')):.2f} "
            f"| {_f(r.get('max_dd_pct')):.2f}% "
            f"| {_f(r.get('return_dd_ratio')):.2f} "
            f"| ${_f(r.get('expectancy')):.2f} "
            f"| {_f(r.get('avg_bars_in_trade')):.1f} |"
        )
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_parent_delta(d: dict) -> list[str]:
    variants = d.get("variants", [])
    parent_map = d.get("lineage_parents", {}) or {}
    if not variants or not parent_map:
        return []
    out = ["## 4. Δ vs Parent", "",
           "| Variant | Parent | Δ Trades | Δ PnL | Δ SQN | Δ DD% | Status |",
           "|---------|--------|----------|-------|-------|-------|--------|"]
    rows_by_id = {v["directive_id"]: v for v in variants}
    for v in variants:
        vid = v["directive_id"]
        parent_id = parent_map.get(vid)
        if not parent_id or parent_id == vid:
            out.append(f"| {_short_name(vid)} | — | — | — | — | — | (root) |")
            continue
        parent = rows_by_id.get(parent_id)
        if parent is None:
            out.append(f"| {_short_name(vid)} | {_short_name(parent_id)} | (parent not in family) | | | | |")
            continue
        # Window mismatch?
        if not parent.get("in_window", True) or not v.get("in_window", True):
            out.append(
                f"| {_short_name(vid)} | {_short_name(parent_id)} | "
                f"unavailable (window mismatch) | | | | |"
            )
            continue
        cr = v.get("row", {}) or {}
        pr = parent.get("row", {}) or {}
        d_trades = int(_f(cr.get("total_trades")) - _f(pr.get("total_trades")))
        d_pnl = _f(cr.get("total_net_profit")) - _f(pr.get("total_net_profit"))
        d_sqn = _f(cr.get("sqn")) - _f(pr.get("sqn"))
        d_dd = _f(cr.get("max_dd_pct")) - _f(pr.get("max_dd_pct"))
        # Improvement marker
        better = "↑" if d_sqn > 0 and d_pnl > 0 else ("↓" if d_sqn < 0 and d_pnl < 0 else "≈")
        out.append(
            f"| {_short_name(vid)} | {_short_name(parent_id)} | "
            f"{d_trades:+d} | ${d_pnl:+.2f} | {d_sqn:+.2f} | {d_dd:+.2f}pp | {better} |"
        )
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_prior_run_delta(d: dict) -> list[str]:
    """Same-strategy comparison — current run vs prior run of THIS strategy.

    Comparison policy differs from ``_render_parent_delta``:
      - Parent-Δ (cross-strategy): window mismatch *suppresses* the row.
      - Prior-run-Δ (same strategy): window mismatch is *informative* and
        the delta is rendered with an annotation.
    """
    variants = d.get("variants", []) or []
    if not variants:
        return []
    # Filter to variants that actually have a prior run.
    with_prior = [
        v for v in variants
        if (v.get("prior_run_delta") or {}).get("found")
    ]
    if not with_prior:
        return []

    out = [
        "## 5. Δ vs Prior Run (same strategy)",
        "",
        "Compares each variant's current Master Filter row to the "
        "immediately preceding row for the **same strategy**. Window "
        "mismatch is **shown with a warning** here — unlike the parent-Δ "
        "above, which suppresses on mismatch — because the window change "
        "itself is one of the things that may have changed between runs.",
        "",
    ]

    for v in with_prior:
        vid = v.get("directive_id", "?")
        prd = v.get("prior_run_delta") or {}
        cur_w = prd.get("current_window", {}) or {}
        pri_w = prd.get("prior_window", {}) or {}
        drift = prd.get("window_drift", {}) or {}
        is_cur = prd.get("prior_is_current")

        header = f"### {_short_name(vid)}"
        out.append(header)
        out.append("")

        # Window line + mismatch annotation
        win_line = (
            f"**Current:** {cur_w.get('start', '?')} → {cur_w.get('end', '?')}  "
            f"  **Prior:** {pri_w.get('start', '?')} → {pri_w.get('end', '?')}"
        )
        out.append(win_line)
        if prd.get("window_mismatch"):
            sd = drift.get("start_days")
            ed = drift.get("end_days")
            parts = []
            if sd is not None:
                parts.append(f"start {sd:+d}d")
            if ed is not None:
                parts.append(f"end {ed:+d}d")
            drift_str = ", ".join(parts) if parts else "drift n/a"
            out.append(f"⚠ **Window mismatch** ({drift_str}) — delta below is "
                       f"informational, not a like-for-like comparison.")
        if is_cur == 0:
            out.append("ℹ Prior row is explicitly **superseded** "
                       "(`is_current = 0`).")
        out.append("")

        # Delta table
        out.append("| Metric | Prior | Current | Δ | Δ% |")
        out.append("|--------|-------|---------|---|----|")
        for m in prd.get("metrics", []) or []:
            out.append(
                f"| {m['label']} | {m['prior_str']} | {m['current_str']} | "
                f"{m['delta_str']} | {m.get('pct_str', '')} |"
            )
        out.append("")

    out.append("---")
    out.append("")
    return out


def _render_lineage(d: dict) -> list[str]:
    variants = d.get("variants", [])
    lineage_diffs = d.get("lineage_diffs", {}) or {}
    if not variants:
        return []
    out = ["## 6. Lineage — Signature Diffs (parent → child)", ""]
    any_diff = False
    for v in variants:
        vid = v["directive_id"]
        diffs = lineage_diffs.get(vid, [])
        if not diffs:
            continue
        any_diff = True
        out.append(f"### {_short_name(vid)} vs parent")
        out.append("")
        out.append("| Field | Parent | Current |")
        out.append("|-------|--------|---------|")
        for key, pv, cv in diffs:
            out.append(f"| `{key}` | `{pv}` | `{cv}` |")
        out.append("")
    if not any_diff:
        out.append("_No signature-level differences detected among the variants in this family._")
        out.append("")
    out.append("---")
    out.append("")
    return out


def _render_concentration(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    out = ["## 7. Concentration / Tail", "",
           "| Variant | Top-1% | Top-5 | Top-1pct N | Body after Top-20 | Verdict |",
           "|---------|--------|-------|------------|-------------------|---------|"]
    for v in variants:
        tc = v.get("tail_contribution", {}) or {}
        body = v.get("body_after_top_20", None)
        top5 = _f(tc.get("top_5"))
        top1pct = _f(tc.get("top_1pct"))
        n1pct = int(tc.get("n_1pct", 0))
        verdict = _tail_verdict(top5, body)
        body_str = "—" if body is None else f"${body:,.2f}"
        out.append(
            f"| {_short_name(v['directive_id'])} | "
            f"{top1pct * 100:.1f}% | {top5 * 100:.1f}% | {n1pct} | "
            f"{body_str} | {verdict} |"
        )
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_session(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    out = ["## 8. Session Contribution", "",
           "PnL share by entry-session (UTC). Bold = max session.",
           "",
           "| Variant | Asia | London | NY | Max |",
           "|---------|------|--------|-----|-----|"]
    for v in variants:
        ss = v.get("session_share", {}) or {}
        a = _f(ss.get("asia"))
        l = _f(ss.get("london"))
        n = _f(ss.get("ny"))
        mx = max(a, l, n)
        flag = " ⚠" if mx > 70.0 else ""
        out.append(
            f"| {_short_name(v['directive_id'])} | "
            f"{a:.1f}% | {l:.1f}% | {n:.1f}% | {mx:.1f}%{flag} |"
        )
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_direction(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    out = ["## 9. Direction Concentration", "",
           "Share of POSITIVE PnL by direction.",
           "",
           "| Variant | Long share | Short share | Verdict |",
           "|---------|-----------|-------------|---------|"]
    for v in variants:
        ds = v.get("direction_share", {}) or {}
        long_s = _f(ds.get("long"))
        short_s = _f(ds.get("short"))
        if max(long_s, short_s) > 85.0:
            verdict = "⚠ Extreme bias"
        elif min(long_s, short_s) >= 30.0:
            verdict = "Balanced"
        else:
            verdict = "Tilted"
        out.append(
            f"| {_short_name(v['directive_id'])} | "
            f"{long_s:.1f}% | {short_s:.1f}% | {verdict} |"
        )
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_regime_cells(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    out = ["## 10. Regime Cell Matrix", ""]
    out.append("Best and worst Direction×{Session, Trend, Volatility} cells (min 30 trades).")
    out.append("")
    for axis_label, axis_key in [("Session", "session"),
                                  ("Trend",   "trend"),
                                  ("Vol",     "volatility")]:
        out.append(f"### 10.{axis_label[0]}. Direction × {axis_label}")
        out.append("")
        out.append("| Variant | Best cell | Best PnL | Worst cell | Worst PnL |")
        out.append("|---------|-----------|----------|------------|-----------|")
        for v in variants:
            cells = (v.get("regime_cells", {}) or {}).get(axis_key, {}) or {}
            best = cells.get("best")
            worst = cells.get("worst")
            if best is None and worst is None:
                out.append(f"| {_short_name(v['directive_id'])} | — | — | — | — |")
                continue
            b_lbl = best["cell"] if best else "—"
            b_pnl = f"${best['net_pnl']:+,.2f}" if best else "—"
            w_lbl = worst["cell"] if worst else "—"
            w_pnl = f"${worst['net_pnl']:+,.2f}" if worst else "—"
            out.append(
                f"| {_short_name(v['directive_id'])} | "
                f"{b_lbl} | {b_pnl} | {w_lbl} | {w_pnl} |"
            )
        out.append("")
    out.append("---")
    out.append("")
    return out


def _render_yearwise(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    out = ["## 11. Yearwise Stability", "",
           "Per-year PnL % of variant net. Flag: any year > 60% = dominant.",
           ""]
    # Union of years across variants
    all_years = sorted({y for v in variants for y in (v.get("yearwise") or {}).keys()})
    if not all_years:
        out.append("_No yearwise data available._")
        out.append("")
        out.append("---")
        out.append("")
        return out
    out.append("| Variant | " + " | ".join(all_years) + " | Max year % |")
    out.append("|---------|" + "|".join(["----" for _ in all_years]) + "|-----------|")
    for v in variants:
        yw = v.get("yearwise") or {}
        total = float(sum((row or {}).get("net_pnl", 0.0) for row in yw.values())) or 1.0
        cells: list[str] = []
        shares: list[float] = []
        for y in all_years:
            row = yw.get(y)
            if row is None:
                cells.append("—")
                shares.append(0.0)
                continue
            pnl = float(row.get("net_pnl", 0.0))
            share = pnl / total * 100.0
            shares.append(abs(share))
            cells.append(f"${pnl:,.0f} ({share:+.0f}%)")
        max_share = max(shares) if shares else 0.0
        flag = " ⚠" if max_share > 60.0 else ""
        out.append(f"| {_short_name(v['directive_id'])} | " + " | ".join(cells) + f" | {max_share:.0f}%{flag} |")
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_streaks(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    out = ["## 12. Streaks", "",
           "| Variant | Max Win | Max Loss | Avg Win | Avg Loss |",
           "|---------|---------|----------|---------|----------|"]
    for v in variants:
        s = v.get("streaks") or {}
        flag = " ⚠" if int(s.get("max_loss_streak", 0)) > 15 else ""
        out.append(
            f"| {_short_name(v['directive_id'])} | "
            f"{int(s.get('max_win_streak', 0))} | "
            f"{int(s.get('max_loss_streak', 0))}{flag} | "
            f"{_f(s.get('avg_win_streak')):.1f} | "
            f"{_f(s.get('avg_loss_streak')):.1f} |"
        )
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_rolling(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    out = ["## 13. Rolling Stability (365d window, 30d step)", "",
           "| Variant | Windows | Neg | DD>20% | Worst Return | Worst DD | Clustering |",
           "|---------|---------|-----|--------|--------------|----------|------------|"]
    for v in variants:
        rs = v.get("rolling_stability") or {}
        if not rs:
            out.append(f"| {_short_name(v['directive_id'])} | — | — | — | — | — | — |")
            continue
        out.append(
            f"| {_short_name(v['directive_id'])} | "
            f"{int(rs.get('total_windows', 0))} | "
            f"{int(rs.get('negative_windows', 0))} | "
            f"{int(rs.get('dd_over_20', 0))} | "
            f"{_f(rs.get('worst_return')):.1f}% | "
            f"{_f(rs.get('worst_dd')):.1f}% | "
            f"{rs.get('clustering', '—')} |"
        )
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_early_late(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    out = ["## 14. Early/Late Split", "",
           "| Variant | H1 PnL | H2 PnL | H1 WR | H2 WR | Δ WR |",
           "|---------|--------|--------|-------|-------|------|"]
    for v in variants:
        el = v.get("early_late") or {}
        h1 = el.get("first_half") or {}
        h2 = el.get("second_half") or {}
        h1_pnl = _f(h1.get("final_equity")) - _f(h1.get("starting_capital", 10000))
        h2_pnl = _f(h2.get("final_equity")) - _f(h2.get("starting_capital", 10000))
        h1_wr = _f(h1.get("win_rate"))
        h2_wr = _f(h2.get("win_rate"))
        d_wr = h2_wr - h1_wr
        out.append(
            f"| {_short_name(v['directive_id'])} | "
            f"${h1_pnl:,.2f} | ${h2_pnl:,.2f} | "
            f"{h1_wr:.1f}% | {h2_wr:.1f}% | {d_wr:+.1f}pp |"
        )
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_drawdown(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    out = ["## 15. Worst Drawdown Episode", "",
           "| Variant | Start | Trough | Recovery | Max DD% | Duration (days) |",
           "|---------|-------|--------|----------|---------|-----------------|"]
    for v in variants:
        clusters = v.get("dd_clusters") or []
        if not clusters:
            out.append(f"| {_short_name(v['directive_id'])} | — | — | — | — | — |")
            continue
        c = clusters[0]
        out.append(
            f"| {_short_name(v['directive_id'])} | "
            f"{c.get('start_date', '—')} | {c.get('trough_date', '—')} | "
            f"{c.get('recovery_date', '—')} | {_f(c.get('max_dd_pct')):.1f}% | "
            f"{int(c.get('duration_days', 0))} |"
        )
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_verdicts(d: dict) -> list[str]:
    variants = d.get("variants", [])
    if not variants:
        return []
    out = ["## 16. Deployment Verdict", "",
           "Canonical verdict via `filter_strategies._compute_candidate_status`.",
           "Soft-gate trips (advisory) may demote a CORE/WATCH variant to FAIL (effective).",
           ""]
    for v in variants:
        vd = v.get("verdict") or {}
        effective = vd.get("effective_status", vd.get("status", "—"))
        canonical = vd.get("status", "—")
        rationale = vd.get("rationale", "")
        if effective != canonical:
            header = f"### {_short_name(v['directive_id'])} — **{effective}** (canonical: {canonical})"
        else:
            header = f"### {_short_name(v['directive_id'])} — **{effective}**"
        out.append(header)
        out.append("")
        out.append(rationale)
        out.append("")
    out.append("---")
    out.append("")
    return out


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _short_name(name: str) -> str:
    """Return the trailing `_S0n_Vm_Pkk` portion when prefix is shared.

    Renders compact in tables. Caller decides how aggressive to short.
    """
    parts = name.split("_")
    # Heuristic: prefix is the first 5 tokens (idea_FAMILY_SYMBOL_TF_MODEL)
    if len(parts) >= 8:
        return "_".join(parts[5:])
    return name


def _tail_verdict(top5_share: float, body_after_top20: float | None) -> str:
    if top5_share > 0.70:
        return "⚠ SEVERELY TAIL-DEPENDENT"
    if body_after_top20 is not None and body_after_top20 < -500.0:
        return "⚠ TAIL-DEPENDENT"
    if top5_share > 0.40:
        return "TAIL-LEANING"
    return "BODY-DRIVEN"


def _f(v) -> float:
    try:
        if v is None:
            return 0.0
        return float(v)
    except Exception:
        return 0.0
