"""
IDX22 — Generated by Strategy Provisioner
Timestamp: 2026-02-28T13:43:19.914024
Directive: IDX22
"""

# --- IMPORTS (Deterministic from Directive) ---
from indicators.structure.highest_high import highest_high
from indicators.volatility.atr import atr
from indicators.volatility.atr_percentile import atr_percentile
from indicators.volatility.volatility_regime import volatility_regime
from engines.filter_stack import FilterStack

class Strategy:
    
    # --- IDENTITY ---
    name = "IDX22"
    timeframe = "1d"
    
    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "entry_logic": {
            "atr_length": 14,
            "condition": "close_less_than_hh_minus_atr",
            "lookback_bars": 5,
            "type": "volatility_pullback"
        },
        "entry_when_flat_only": True,
        "exit_logic": {
            "price_exit": "close_greater_than_hh_prev",
            "time_exit_bars": 5,
            "type": "dynamic_or_time"
        },
        "pyramiding": False,
        "reset_on_exit": True,
        "stop_loss": {
            "type": "none"
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "indicators": [
        "indicators.structure.highest_high",
        "indicators.volatility.atr",
        "indicators.volatility.atr_percentile",
        "indicators.volatility.volatility_regime"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "signature_version": 2,
    "trade_management": {
        "direction": "long_only",
        "reentry": {
            "allowed": False
        }
    },
    "volatility_filter": {
        "atr_length": 14,
        "atr_percentile_lookback": 100,
        "condition": "atr_percentile_above_threshold",
        "cooldown_bars": 5,
        "threshold": 75
    }
}
    # --- STRATEGY SIGNATURE END ---
    
    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    
    def prepare_indicators(self, df):
        """
        Compute indicators here.
        Must return the dataframe with new columns.
        """
        entry_sig     = self.STRATEGY_SIGNATURE["execution_rules"]["entry_logic"]
        vf_sig        = self.STRATEGY_SIGNATURE["volatility_filter"]

        hh_lookback   = entry_sig["lookback_bars"]          # 5
        atr_length    = entry_sig["atr_length"]              # 14
        pct_lookback  = vf_sig["atr_percentile_lookback"]   # 100
        pct_threshold = vf_sig["threshold"]                 # 75
        cooldown_bars = vf_sig["cooldown_bars"]              # 5

        # 1. Highest High of previous N bars (shift=1 — no lookahead)
        df["hh"] = highest_high(df["high"], window=hh_lookback, shift=1)

        # 2. ATR(14)
        df["atr"] = atr(df, window=atr_length)

        # 3. ATR percentile via canonical indicator (returns 0.0–1.0, scale to 0–100)
        df["atr_pct"] = atr_percentile(df["atr"], window=pct_lookback) * 100

        # 4. Volatility regime — required authoritative indicator (engine contract)
        df["volatility_regime"] = volatility_regime(df["atr"], window=pct_lookback)["regime"]

        # 5. Volatility Shock Cooldown
        #    Trigger: ATR pct crosses ABOVE threshold (prev <= threshold, curr > threshold)
        above       = df["atr_pct"] > pct_threshold
        prev_above  = above.shift(1).fillna(False).infer_objects(copy=False)
        shock_cross = above & ~prev_above

        # For each bar, mark cooldown active for N bars following a shock cross
        df["cooldown_active"] = False
        if shock_cross.any():
            last_shock = None
            for idx in df.index:
                if shock_cross.loc[idx]:
                    last_shock = idx
                if last_shock is not None:
                    bars_since = df.index.get_loc(idx) - df.index.get_loc(last_shock)
                    df.at[idx, "cooldown_active"] = (bars_since <= cooldown_bars)

        return df

    def check_entry(self, ctx):
        """
        Return entry signal dict or None.
        e.g. {"signal": 1} for Long
        """
        # Architectural Requirement: Allow FilterStack to gate entry
        if not self.filter_stack.allow_trade(ctx):
            return None

        close        = ctx.row.get("close")
        hh           = ctx.row.get("hh")
        atr_val      = ctx.row.get("atr")
        atr_pct      = ctx.row.get("atr_pct")
        cooldown     = ctx.row.get("cooldown_active", False)

        # Guard: require valid indicator values
        if any(v is None for v in [close, hh, atr_val, atr_pct]):
            return None

        # Volatility filter: do NOT trade when ATR pct > 75
        pct_threshold = self.STRATEGY_SIGNATURE["volatility_filter"]["threshold"]
        if atr_pct > pct_threshold:
            return None

        # Cooldown filter: do NOT take new entries while cooldown is active
        if cooldown:
            return None

        # Entry condition: close < (HH_prev5 - ATR14)
        # No ATR multiplier declared in directive — pure ATR subtraction
        if close < (hh - atr_val):
            return {"signal": 1, "comment": "dip_below_hh_minus_atr"}

        return None

    def check_exit(self, ctx):
        """
        Return True to close position.
        """
        exit_sig = self.STRATEGY_SIGNATURE["execution_rules"]["exit_logic"]

        # 1. Time Exit: bars held >= 5
        max_bars = exit_sig["time_exit_bars"]
        if ctx.bars_held >= max_bars:
            return True

        # 2. Price Exit: close > HH_prev (recomputed on each bar)
        close = ctx.row.get("close")
        hh    = ctx.row.get("hh")

        if close is not None and hh is not None and close > hh:
            return True

        return False
