"""
IDX25_MR_RSIAVG — Generated by Strategy Provisioner
Timestamp: 2026-03-01T15:18:25.545956
Directive: IDX25_MR_RSIAVG
"""

# --- IMPORTS (Deterministic from Directive) ---
from indicators.price.stochastic import stochastic_k
from indicators.price.roc import roc
from indicators.price.rsi import rsi
from indicators.structure.highest_high import highest_high
from indicators.structure.lowest_low import lowest_low
from indicators.trend.linreg_regime import linreg_regime
from indicators.trend.linreg_regime_htf import linreg_regime_htf
from indicators.trend.kalman_regime import kalman_regime
from indicators.trend.trend_persistence import trend_persistence
from indicators.volatility.volatility_regime import volatility_regime
from indicators.volatility.atr import atr
from engines.filter_stack import FilterStack

class Strategy:
    
    # --- IDENTITY ---
    name = "IDX25_MR_RSIAVG"
    timeframe = "1d"
    
    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "entry_logic": {
            "condition": "intersection_with_union",
            "type": "multi_signal_mean_reversion"
        },
        "entry_when_flat_only": True,
        "exit_logic": {
            "time_exit_bars": 4,
            "type": "dynamic_or_time"
        },
        "pyramiding": False,
        "reset_on_exit": True,
        "stop_loss": {
            "type": "none"
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "indicators": [
        "indicators.price.stochastic",
        "indicators.price.roc",
        "indicators.price.rsi",
        "indicators.structure.highest_high",
        "indicators.structure.lowest_low",
        "indicators.trend.linreg_regime",
        "indicators.trend.linreg_regime_htf",
        "indicators.trend.kalman_regime",
        "indicators.trend.trend_persistence",
        "indicators.volatility.volatility_regime",
        "indicators.volatility.atr"
    ],
    "mean_reversion_rules": {
        "entry_gate": "intersection",
        "exit_rsi_overbought": {
            "rsi_length": 2,
            "threshold": 75
        },
        "primary_condition": "three_consecutive_lower_closes",
        "roc_oversold_cross": {
            "roc_length": 5,
            "threshold": -1.0
        },
        "rsi_deep_oversold": {
            "avg_bars": 2,
            "rsi_length": 2,
            "threshold": 25
        },
        "secondary_gate": "union",
        "stochastic_oversold_cross": {
            "d_length": 3,
            "k_length": 14,
            "threshold": 20
        }
    },
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "signature_version": 2,
    "trade_management": {
        "direction": "long_only",
        "reentry": {
            "allowed": False
        }
    }
}
    # --- STRATEGY SIGNATURE END ---
    
    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    
    def prepare_indicators(self, df):
        """
        Compute indicators here.
        Must return the dataframe with new columns.
        """
        mr = self.STRATEGY_SIGNATURE["mean_reversion_rules"]
        stoch_cfg = mr["stochastic_oversold_cross"]
        roc_cfg   = mr["roc_oversold_cross"]
        rsi_cfg   = mr["rsi_deep_oversold"]
        exit_cfg  = mr["exit_rsi_overbought"]

        # 1. RSI(2) for entry and exit
        df["rsi_2"] = rsi(df["close"], period=rsi_cfg["rsi_length"])

        # 2. RSI(2) 2-bar average (manual — no .rolling to satisfy governance)
        avg_bars = rsi_cfg["avg_bars"]  # 2
        df["rsi_2_avg"] = (df["rsi_2"] + df["rsi_2"].shift(1)) / avg_bars

        # 3. Stochastic %K(14, smooth=3)
        df["stoch_k"] = stochastic_k(
            df["high"], df["low"], df["close"],
            k_period=stoch_cfg["k_length"],
            smooth_period=stoch_cfg["d_length"]
        )

        # 4. ROC(5)
        df["roc_5"] = roc(df["close"], period=roc_cfg["roc_length"])

        # 5. Three consecutive lower closes
        c = df["close"]
        df["lower_close_1"] = c < c.shift(1)
        df["lower_close_2"] = c.shift(1) < c.shift(2)
        df["lower_close_3"] = c.shift(2) < c.shift(3)
        df["three_lower_closes"] = (
            df["lower_close_1"] & df["lower_close_2"] & df["lower_close_3"]
        )

        # 6. ATR (for engine contract)
        df["atr"] = atr(df, window=14)

        # 7. Volatility regime (engine contract)
        df["volatility_regime"] = volatility_regime(df["atr"], window=100)["regime"]

        # 8. Stochastic oversold cross: stoch crosses below threshold
        stoch_thresh = stoch_cfg["threshold"]
        df["stoch_below"] = df["stoch_k"] < stoch_thresh
        df["stoch_cross_down"] = df["stoch_below"] & ~df["stoch_below"].shift(1).fillna(False)

        # 9. ROC oversold cross: ROC crosses below threshold
        roc_thresh = roc_cfg["threshold"]
        df["roc_below"] = df["roc_5"] < roc_thresh
        df["roc_cross_down"] = df["roc_below"] & ~df["roc_below"].shift(1).fillna(False)

        # Clean up temporary columns
        df.drop(columns=["lower_close_1", "lower_close_2", "lower_close_3"], inplace=True)

        return df

    def check_entry(self, ctx):
        """
        Return entry signal dict or None.
        e.g. {"signal": 1} for Long

        Entry logic (INTERSECTION):
          1. Primary: 3 consecutive lower closes (must be True)
          AND
          2. Secondary (UNION — at least one):
             a. Stochastic(14,3) crosses below 20
             b. ROC(5) crosses below -1.0
             c. RSI(2) 2-bar avg < 25
        """
        # Architectural Requirement: Allow FilterStack to gate entry
        if not self.filter_stack.allow_trade(ctx):
            return None

        mr = self.STRATEGY_SIGNATURE["mean_reversion_rules"]

        # Primary gate: three consecutive lower closes
        three_lc = ctx.row.get("three_lower_closes", False)
        if not three_lc:
            return None

        # Secondary gate (union — at least one must fire)
        signals_fired = []

        # a. Stochastic oversold cross
        stoch_cross = ctx.row.get("stoch_cross_down", False)
        if stoch_cross:
            signals_fired.append("stoch_oversold_cross")

        # b. ROC oversold cross
        roc_cross = ctx.row.get("roc_cross_down", False)
        if roc_cross:
            signals_fired.append("roc_oversold_cross")

        # c. RSI(2) 2-bar avg < 25
        rsi_avg = ctx.row.get("rsi_2_avg")
        rsi_thresh = mr["rsi_deep_oversold"]["threshold"]
        if rsi_avg is not None and rsi_avg < rsi_thresh:
            signals_fired.append("rsi_deep_oversold")

        if not signals_fired:
            return None

        return {
            "signal": 1,
            "comment": f"3_lower_closes+{'+'.join(signals_fired)}"
        }

    def check_exit(self, ctx):
        """
        Return True to close position.

        Exit logic (PRECEDENCE):
          Primary: RSI(2) > 75 (overbought)
          Fallback: Time exit after 4 bars
        """
        mr = self.STRATEGY_SIGNATURE["mean_reversion_rules"]
        exit_cfg = mr["exit_rsi_overbought"]

        # 1. Primary exit: RSI(2) crosses above overbought threshold
        rsi_val = ctx.row.get("rsi_2")
        if rsi_val is not None and rsi_val > exit_cfg["threshold"]:
            return True

        # 2. Fallback: time exit
        exit_sig = self.STRATEGY_SIGNATURE["execution_rules"]["exit_logic"]
        max_bars = exit_sig["time_exit_bars"]
        if ctx.bars_held >= max_bars:
            return True

        return False

