"""
01_MR_FX_1D_RSIAVG_TRENDFILT_S01_V1_P02 — Generated by Strategy Provisioner
Timestamp: 2026-03-10T15:48:14.147530
Directive: 01_MR_FX_1D_RSIAVG_TRENDFILT_S01_V1_P02
"""

# --- IMPORTS (Deterministic from Directive) ---
from indicators.momentum.stochastic import stochastic_k
from indicators.momentum.roc import roc
from indicators.momentum.rsi import rsi
from indicators.structure.highest_high import highest_high
from indicators.structure.lowest_low import lowest_low
from indicators.trend.linreg_regime import linreg_regime
from indicators.trend.linreg_regime_htf import linreg_regime_htf
from indicators.trend.kalman_regime import kalman_regime
from indicators.trend.trend_persistence import trend_persistence
from indicators.volatility.volatility_regime import volatility_regime
from indicators.volatility.atr import atr
from engines.filter_stack import FilterStack

class Strategy:
    
    # --- IDENTITY ---
    name = "01_MR_FX_1D_RSIAVG_TRENDFILT_S01_V1_P02"
    timeframe = "1d"
    
    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "entry_logic": {
            "condition": "intersection_with_union",
            "type": "multi_signal_mean_reversion"
        },
        "entry_when_flat_only": True,
        "exit_logic": {
            "time_exit_bars": 4,
            "type": "dynamic_or_time"
        },
        "pyramiding": False,
        "reset_on_exit": True,
        "stop_loss": {
            "type": "none"
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "indicators": [
        "indicators.momentum.stochastic",
        "indicators.momentum.roc",
        "indicators.momentum.rsi",
        "indicators.structure.highest_high",
        "indicators.structure.lowest_low",
        "indicators.trend.linreg_regime",
        "indicators.trend.linreg_regime_htf",
        "indicators.trend.kalman_regime",
        "indicators.trend.trend_persistence",
        "indicators.volatility.volatility_regime",
        "indicators.volatility.atr"
    ],
    "mean_reversion_rules": {
        "entry_gate": "intersection",
        "exit_rsi_overbought": {
            "rsi_length": 2,
            "threshold": 75
        },
        "primary_condition": {
            "type": "three_consecutive_lower_closes"
        },
        "roc_oversold_cross": {
            "event": "cross_below",
            "roc_length": 5,
            "threshold": -1.0
        },
        "rsi_deep_oversold": {
            "avg_bars": 2,
            "rsi_length": 2,
            "threshold": 25
        },
        "secondary_gate": "union",
        "stochastic_oversold_cross": {
            "d_length": 3,
            "event": "cross_above",
            "k_length": 14,
            "threshold": 20.0
        }
    },
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "signature_version": 2,
    "trade_management": {
        "direction": "long_only",
        "reentry": {
            "allowed": False
        },
        "session_reset": "none"
    }
}
    # --- STRATEGY SIGNATURE END ---
    
    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    
    def prepare_indicators(self, df):
        import pandas as pd
        if not isinstance(df.index, pd.DatetimeIndex):
            df = df.set_index(pd.DatetimeIndex(df['timestamp']))

        # Engine-required authoritative columns
        df['atr'] = atr(df, window=14)
        vr = volatility_regime(df['atr'], window=100)
        df['volatility_regime'] = vr['regime']

        # Momentum indicators
        df['rsi_2']     = rsi(df['close'], period=self.STRATEGY_SIGNATURE["mean_reversion_rules"]["exit_rsi_overbought"]["rsi_length"])
        # 2-bar smoothed RSI: (rsi_t + rsi_t-1) / 2
        df['rsi_2_avg'] = (df['rsi_2'] + df['rsi_2'].shift(1)) / 2
        
        df['roc_5']    = roc(df['close'], period=self.STRATEGY_SIGNATURE["mean_reversion_rules"]["roc_oversold_cross"]["roc_length"])
        df['roc_5_prev'] = df['roc_5'].shift(1)
        
        df['stoch_k']  = stochastic_k(
            df['high'], df['low'], df['close'],
            k_period=self.STRATEGY_SIGNATURE["mean_reversion_rules"]["stochastic_oversold_cross"]["k_length"],
            smooth_period=self.STRATEGY_SIGNATURE["mean_reversion_rules"]["stochastic_oversold_cross"]["d_length"]
        )
        df['stoch_k_prev'] = df['stoch_k'].shift(1)

        # Structure
        df['hh_10'] = highest_high(df['high'], window=10)
        df['ll_10'] = lowest_low(df['low'], window=10)

        # Primary condition: 3 consecutive lower closes
        df['three_lower_closes'] = (
            (df['close'] < df['close'].shift(1)) &
            (df['close'].shift(1) < df['close'].shift(2)) &
            (df['close'].shift(2) < df['close'].shift(3))
        )

        return df

    def check_entry(self, ctx):
        import pandas as pd
        if not self.filter_stack.allow_trade(ctx):
            return None

        row = ctx.row
        direction = ctx.direction

        # Long-only — skip if already in a position
        if direction != 0:
            return None

        # Primary: 3 consecutive lower closes
        if not row.get('three_lower_closes', False):
            return None

        # Secondary union: at least one of the oversold conditions fires
        rsi_avg = row.get('rsi_2_avg')
        roc_val = row.get('roc_5')
        roc_prev = row.get('roc_5_prev')
        stoch_val = row.get('stoch_k')
        stoch_prev = row.get('stoch_k_prev')

        rsi_oversold   = (pd.notnull(rsi_avg) and rsi_avg < self.STRATEGY_SIGNATURE["mean_reversion_rules"]["rsi_deep_oversold"]["threshold"])
        
        # Cross type resolution
        roc_thr = self.STRATEGY_SIGNATURE["mean_reversion_rules"]["roc_oversold_cross"]["threshold"]
        roc_event = self.STRATEGY_SIGNATURE["mean_reversion_rules"]["roc_oversold_cross"]["event"]
        if roc_event == "cross_below":
            roc_cross = (pd.notnull(roc_val) and pd.notnull(roc_prev) and roc_prev >= roc_thr and roc_val < roc_thr)
        elif roc_event == "cross_above":
            roc_cross = (pd.notnull(roc_val) and pd.notnull(roc_prev) and roc_prev <= roc_thr and roc_val > roc_thr)
        else:
            roc_cross = False
            
        stoch_thr = self.STRATEGY_SIGNATURE["mean_reversion_rules"]["stochastic_oversold_cross"]["threshold"]
        stoch_event = self.STRATEGY_SIGNATURE["mean_reversion_rules"]["stochastic_oversold_cross"]["event"]
        if stoch_event == "cross_above":
            stoch_cross = (pd.notnull(stoch_val) and pd.notnull(stoch_prev) and stoch_prev <= stoch_thr and stoch_val > stoch_thr)
        elif stoch_event == "cross_below":
            stoch_cross = (pd.notnull(stoch_val) and pd.notnull(stoch_prev) and stoch_prev >= stoch_thr and stoch_val < stoch_thr)
        else:
            stoch_cross = False

        if not (rsi_oversold or roc_cross or stoch_cross):
            return None

        return {"signal": 1}

    def check_exit(self, ctx):
        import pandas as pd
        row = ctx.row
        direction = ctx.direction

        if direction == 0:
            return False

        # RSI overbought exit
        rsi_2 = row.get('rsi_2')
        if pd.notnull(rsi_2) and rsi_2 > self.STRATEGY_SIGNATURE["mean_reversion_rules"]["exit_rsi_overbought"]["threshold"]:
            return True

        # Time exit
        bars_held = getattr(ctx, 'bars_held', 0)
        if bars_held >= self.STRATEGY_SIGNATURE["execution_rules"]["exit_logic"]["time_exit_bars"]:
            return True

        return False
