"""
07_MR_XAUUSD_15M_SMI_SMIFILT_S02_V1_P04 -- Generated by Strategy Provisioner

S02_V1_P04: Bidirectional mean-reversion with symmetric SMI thresholds.

Extension of P03 (event-triggered window) to long_and_short:
  - Long setup : 1H SMI crosses below -50 → opens 8-bar entry window
  - Short setup: 1H SMI crosses above +50 → opens 8-bar entry window
  - Long entry : 15M SMI crosses above signal AND 15M SMI > -40 (within long window)
  - Short entry: 15M SMI crosses below signal AND 15M SMI < +40 (within short window)
  - Vol gate   : LOW and HIGH regimes only (NORMAL excluded)
  - Long exit  : 1H SMI > -10 OR penultimate bar of day
  - Short exit : 1H SMI < +10 OR penultimate bar of day
  - Risk       : Fixed $50 stop loss, single trade per session
"""

import pandas as pd

# --- IMPORTS (Deterministic from Directive) ---
from indicators.trend.linreg_regime import linreg_regime
from indicators.trend.linreg_regime_htf import linreg_regime_htf
from indicators.trend.kalman_regime import kalman_regime
from indicators.trend.trend_persistence import trend_persistence
from indicators.trend.efficiency_ratio_regime import efficiency_ratio_regime
from indicators.volatility.volatility_regime import volatility_regime
from indicators.volatility.atr import atr
from indicators.momentum.stochastic_momentum_index import stochastic_momentum_index
from engines.filter_stack import FilterStack

# ---------------------------------------------------------------------------
# Strategy constants
# ---------------------------------------------------------------------------
_SMI_PERIOD        = 14
_SMI_SMOOTH1       = 3
_SMI_SMOOTH2       = 3
_SMI_SIGNAL        = 3

_SETUP_THRESHOLD_LONG  = -50.0   # 1H SMI cross-below threshold (long setup)
_SETUP_THRESHOLD_SHORT =  50.0   # 1H SMI cross-above threshold (short setup)
_SETUP_WINDOW_BARS     = 8       # 15M bars the setup window stays open (2 hours)

_TRIGGER_RECOVERY_LONG  = -40.0  # 15M SMI must be above this at long signal cross
_TRIGGER_RECOVERY_SHORT =  40.0  # 15M SMI must be below this at short signal cross

_EXIT_REVERSION_LONG  = -10.0    # 1H SMI long exit threshold
_EXIT_REVERSION_SHORT =  10.0    # 1H SMI short exit threshold

_ALLOWED_REGIMES = {-1, 1}       # -1=low, 1=high; 0=normal excluded


class Strategy:

    # --- IDENTITY ---
    name = "07_MR_XAUUSD_15M_SMI_SMIFILT_S02_V1_P04"
    timeframe = "15m"

    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "stop_loss": {
            "fixed_points": 50,
            "type": "fixed_usd"
        },
        "take_profit": {
            "enabled": False
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "exit_rules": {
        "condition_1": {
            "condition": "direction_aware",
            "indicator": "smi_1h",
            "threshold_long": -10,
            "threshold_short": 10,
            "type": "indicator_threshold"
        },
        "condition_2": {
            "timing": "penultimate_bar_of_day",
            "type": "time_based"
        },
        "logic": "OR",
        "type": "composite"
    },
    "indicators": [
        "indicators.trend.linreg_regime",
        "indicators.trend.linreg_regime_htf",
        "indicators.trend.kalman_regime",
        "indicators.trend.trend_persistence",
        "indicators.trend.efficiency_ratio_regime",
        "indicators.volatility.volatility_regime",
        "indicators.volatility.atr",
        "indicators.momentum.stochastic_momentum_index"
    ],
    "mean_reversion_rules": {
        "exit_reversion_threshold_long": -10,
        "exit_reversion_threshold_short": 10,
        "setup_condition": "cross_below_or_above",
        "setup_indicator": "smi_1h",
        "setup_threshold_long": -50,
        "setup_threshold_short": 50,
        "setup_timeframe": "1H",
        "setup_window_bars": 8,
        "trigger_recovery_threshold_long": -40,
        "trigger_recovery_threshold_short": 40,
        "trigger_timeframe": "15M",
        "trigger_type": "signal_cross_with_recovery"
    },
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "position_management": {
        "lots": 0.01
    },
    "signature_version": 2,
    "state_machine": {
        "entry": {
            "direction": "long_and_short",
            "trigger": "signal_bar"
        },
        "no_reentry_after_stop": True,
        "session_reset": "new_day"
    },
    "trade_management": {
        "direction_restriction": "long_and_short",
        "max_trades_per_session": 1,
        "reentry": {
            "allowed": False
        }
    },
    "volatility_filter": {
        "allow_regime": "LOW,HIGH",
        "type": "volatility_regime"
    }
}
    # --- STRATEGY SIGNATURE END ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    def prepare_indicators(self, df):
        if not isinstance(df.index, pd.DatetimeIndex):
            df = df.set_index(pd.DatetimeIndex(df['timestamp']))

        # Engine-required authoritative columns
        df['atr'] = atr(df, window=14)
        vr = volatility_regime(df['atr'], window=100)
        df['volatility_regime'] = vr['regime']

        # 15M SMI
        smi_15m = stochastic_momentum_index(
            df['high'], df['low'], df['close'],
            period=_SMI_PERIOD, smooth1=_SMI_SMOOTH1,
            smooth2=_SMI_SMOOTH2, signal_period=_SMI_SIGNAL
        )
        df['smi_15m']             = smi_15m['smi']
        df['smi_signal_15m']      = smi_15m['smi_signal']
        df['smi_15m_prev']        = df['smi_15m'].shift(1)
        df['smi_signal_15m_prev'] = df['smi_signal_15m'].shift(1)

        # 1H SMI (resampled from 15M, shift(1) to avoid lookahead)
        h1_df = pd.DataFrame({
            'high':  df['high'].resample('1h').max(),
            'low':   df['low'].resample('1h').min(),
            'close': df['close'].resample('1h').last(),
        }).dropna()

        smi_1h = stochastic_momentum_index(
            h1_df['high'], h1_df['low'], h1_df['close'],
            period=_SMI_PERIOD, smooth1=_SMI_SMOOTH1,
            smooth2=_SMI_SMOOTH2, signal_period=_SMI_SIGNAL
        )

        smi_by_hour = smi_1h['smi'].shift(1).to_dict()
        df['smi_1h'] = df.index.floor('1h').map(smi_by_hour)
        df['smi_1h'] = df['smi_1h'].ffill()

        # ----------------------------------------------------------------
        # Event-triggered setup windows (bidirectional)
        #
        # long_window_active : True for SETUP_WINDOW_BARS bars after 1H SMI
        #                      crosses below -50 (fresh oversold capitulation)
        # short_window_active: True for SETUP_WINDOW_BARS bars after 1H SMI
        #                      crosses above +50 (fresh overbought exhaustion)
        # ----------------------------------------------------------------
        smi_1h_prev = df['smi_1h'].shift(1)

        cross_below_50 = (
            (smi_1h_prev >= _SETUP_THRESHOLD_LONG) &
            (df['smi_1h'] < _SETUP_THRESHOLD_LONG)
        )
        cross_above_50 = (
            (smi_1h_prev <= _SETUP_THRESHOLD_SHORT) &
            (df['smi_1h'] > _SETUP_THRESHOLD_SHORT)
        )

        long_window  = pd.Series(False, index=df.index)
        short_window = pd.Series(False, index=df.index)
        for lag in range(_SETUP_WINDOW_BARS):
            long_window  = long_window  | cross_below_50.shift(lag).fillna(False)
            short_window = short_window | cross_above_50.shift(lag).fillna(False)

        df['long_window_active']  = long_window
        df['short_window_active'] = short_window

        # Session bar labels (exit backstop)
        dates = df.index.normalize()
        bar_number  = df.groupby(dates).cumcount()
        bars_in_day = df.groupby(dates)[df.columns[0]].transform('count')
        df['is_penultimate_bar'] = bar_number == (bars_in_day - 2)

        return df

    def check_entry(self, ctx):
        if not self.filter_stack.allow_trade(ctx):
            return None

        row = ctx.row

        # Gate 0: Volatility regime — LOW or HIGH only
        regime = row.get('volatility_regime')
        if regime not in _ALLOWED_REGIMES:
            return None

        smi_now  = row.get('smi_15m')
        sig_now  = row.get('smi_signal_15m')
        smi_prev = row.get('smi_15m_prev')
        sig_prev = row.get('smi_signal_15m_prev')

        if any(pd.isna(v) or v is None for v in [smi_now, sig_now, smi_prev, sig_prev]):
            return None

        # --- LONG setup ---
        if row.get('long_window_active', False):
            # 15M SMI upward cross above signal
            if (smi_prev <= sig_prev) and (smi_now > sig_now):
                # Must be in recovery zone (not too deeply oversold still)
                if smi_now > _TRIGGER_RECOVERY_LONG:
                    return {"signal": 1}

        # --- SHORT setup ---
        if row.get('short_window_active', False):
            # 15M SMI downward cross below signal
            if (smi_prev >= sig_prev) and (smi_now < sig_now):
                # Must be in recovery zone (not too deeply overbought still)
                if smi_now < _TRIGGER_RECOVERY_SHORT:
                    return {"signal": -1}

        return None

    def check_exit(self, ctx):
        row = ctx.row
        direction = ctx.direction  # 1=long, -1=short

        smi_1h = row.get('smi_1h')

        if smi_1h is not None and not pd.isna(smi_1h):
            if direction == 1 and smi_1h > _EXIT_REVERSION_LONG:
                return True
            if direction == -1 and smi_1h < _EXIT_REVERSION_SHORT:
                return True

        if row.get('is_penultimate_bar', False):
            return True

        return False
