"""Styling rules — color/font/format constants + column orders used by styling.py.

Pure data. No functions, no side effects. Imported by styling.py.
"""

# Styling
HEADER_FILL_COLOR = "4472C4"  # Lighter Blue (SOP Governance)
HEADER_FONT_COLOR = "FFFFFF"
ALT_ROW_FILL_COLOR = "DCE6F1"

# Number Formats
FMT_CURRENCY = "#,##0.00"   # USD (2 decimals, comma)
FMT_PERCENT = "0.0%"        # Percent ratio (0.1234 -> 12.3%)
FMT_PCT_RAW = "0.0\"%\""    # Raw percent number (65.24 -> 65.2%)
FMT_FLOAT = "0.00"          # Ratio/Float (2 decimals: 1.23)
FMT_INT = "0"               # Integer

# Header display
HEADER_ROW_HEIGHT = 36       # Tall enough for 2-line wrapped headers
MAX_HEADER_LINE_LEN = 14     # Wrap headers wider than this

# Column Rules (Column Name -> Format)
# Keys should be lower-case for matching
FORMAT_MAP = {
    # Rank (auto-generated by formatter)
    "rank": FMT_INT,

    # Trades List Headers (Human Readable)
    "pnl (usd)": FMT_CURRENCY,
    "entry price": FMT_FLOAT,
    "exit price": FMT_FLOAT,
    "bars held": FMT_INT,

    # Summary Metrics (Human Readable - Lowercase)
    "net profit (usd)": FMT_CURRENCY,
    "gross profit (usd)": FMT_CURRENCY,
    "gross loss (usd)": FMT_CURRENCY,
    "starting capital": FMT_CURRENCY,
    "max drawdown (usd)": FMT_CURRENCY,
    "largest win (usd)": FMT_CURRENCY,
    "largest loss (usd)": FMT_CURRENCY,
    "expectancy (usd)": FMT_CURRENCY,
    "avg trade (usd)": FMT_CURRENCY,
    "avg win (usd)": FMT_CURRENCY,
    "avg loss (usd)": FMT_CURRENCY,

    # Pre-multiplied (0..100 scale) — emitted as such by Stage 2
    # (engine stage2_compiler.py: max_dd_pct = raw_dd_pct * 100;
    #  metrics_core: pct_profitable = win_rate * 100). Use literal-% format
    # so Excel does NOT multiply by 100 again.
    "max drawdown (%)": FMT_PCT_RAW,
    "% profitable": FMT_PCT_RAW,
    "unspecified exit %": FMT_PCT_RAW,

    # Exit Source Breakdown sheet (Stage 2, contract v1.3)
    "count (all)":      FMT_INT,
    "count (long)":     FMT_INT,
    "count (short)":    FMT_INT,
    "pnl usd (all)":    FMT_CURRENCY,
    "pnl usd (long)":   FMT_CURRENCY,
    "pnl usd (short)":  FMT_CURRENCY,
    # Raw fractions (0..1) — Excel's 0.0% format auto-multiplies by 100 for display
    "% of gross profit (top trades)": FMT_PERCENT,
    "worst 5 trades loss %": FMT_PERCENT,
    "return on capital": FMT_PERCENT,
    "% time in market": FMT_PERCENT,

    "profit factor": FMT_FLOAT,
    "sharpe ratio": FMT_FLOAT,
    "sortino ratio": FMT_FLOAT,
    "k-ratio": FMT_FLOAT,
    "sqn (system quality number)": FMT_FLOAT,
    "return / drawdown ratio": FMT_FLOAT,
    "return retracement ratio": FMT_FLOAT,
    "avg mfe (r)": FMT_FLOAT,
    "avg mae (r)": FMT_FLOAT,
    "edge ratio (mfe / mae)": FMT_FLOAT,
    "win/loss ratio": FMT_FLOAT,
    "avg bars in winning trades": FMT_FLOAT,
    "avg bars in losing trades": FMT_FLOAT,
    "avg bars per trade": FMT_FLOAT,

    # Strategy Master Filter Keys (Stage-3)
    "total_net_profit": FMT_CURRENCY,
    "expectancy": FMT_CURRENCY,
    "sharpe_ratio": FMT_FLOAT,
    "return_dd_ratio": FMT_FLOAT,
    "worst_5_loss_pct": FMT_PERCENT,
    "max_drawdown": FMT_CURRENCY, # "max_dd_usd" is legacy
    "longest_loss_streak": FMT_INT,
    "pct_time_in_market": FMT_PERCENT,
    "avg_bars_in_trade": FMT_FLOAT,
    "net_profit_high_vol": FMT_CURRENCY,
    "net_profit_normal_vol": FMT_CURRENCY,
    "net_profit_low_vol": FMT_CURRENCY,

    # Legacy / Internal Keys (Keep for compatibility)
    "net_pnl_usd": FMT_CURRENCY,
    "realized_pnl": FMT_CURRENCY,
    "theoretical_pnl": FMT_CURRENCY,
    "net_profit": FMT_CURRENCY,
    "theoretical_pnl": FMT_CURRENCY,
    "net_profit": FMT_CURRENCY,
    "gross_profit": FMT_CURRENCY,
    "gross_loss": FMT_CURRENCY,
    "max_dd_usd": FMT_CURRENCY,
    "max_dd_pct": FMT_PCT_RAW,
    "win_rate": FMT_PCT_RAW,
    "sharpe": FMT_FLOAT,
    "profit_factor": FMT_FLOAT,
    "total_trades": FMT_INT,
    "sqn": FMT_FLOAT,
    "edge_quality": FMT_FLOAT,
    "peak_dd_ratio": FMT_FLOAT,
    "trade_density": FMT_INT,                  # Master Filter: per-symbol trades/yr
    "symbol_count": FMT_INT,
    "trade_density_total": FMT_INT,
    "trade_density_min": FMT_INT,
    "profile_trade_density_total": FMT_INT,
    "profile_trade_density_min": FMT_INT,
    "winning_trades": FMT_INT,
    "losing_trades": FMT_INT,
    "max_consec_wins": FMT_INT,
    "max_consec_losses": FMT_INT,
    "consecutive_wins": FMT_INT,
    "consecutive_losses": FMT_INT,

    # Profile Selector (Step 12) — Master Portfolio Sheet
    "trades_accepted": FMT_INT,
    "trades_rejected": FMT_INT,
    "rejection_rate_pct": FMT_PCT_RAW,
    "realized_vs_theoretical_pnl": FMT_FLOAT,

    # Portfolio Sheet — Additional Keys
    "reference_capital_usd": FMT_CURRENCY,
    "peak_capital_deployed": FMT_CURRENCY,
    "capital_overextension_ratio": FMT_FLOAT,
    "avg_concurrent": FMT_FLOAT,
    "max_concurrent": FMT_INT,
    "p95_concurrent": FMT_INT,
    "dd_max_concurrent": FMT_INT,
    "full_load_cluster": FMT_FLOAT,
    "avg_pairwise_corr": FMT_FLOAT,
    "max_pairwise_corr_stress": FMT_FLOAT,
    "portfolio_net_profit_low_vol": FMT_CURRENCY,
    "portfolio_net_profit_normal_vol": FMT_CURRENCY,
    "portfolio_net_profit_high_vol": FMT_CURRENCY,
    "exposure_pct": FMT_PCT_RAW,
    "equity_stability_k_ratio": FMT_FLOAT,
    "expectancy": FMT_CURRENCY,

    # Single-Asset Composites — Regime-Aware Metrics
    "n_strategies": FMT_INT,
    "activation_rate_pct": FMT_PCT_RAW,
    "regime_blocked_trades": FMT_INT,
    "blocked_pnl_raw": FMT_CURRENCY,
}

# Hidden Columns (SOP Auditing Fields)
HIDDEN_COLS = {
    "constituent_run_ids",
    "run_ids",
    "genome_id",
    "run_id",
    "creation_timestamp",
    "timestamp",
    "source_strategy",   # Redundant with portfolio_id
    "parsed_fields",     # JSON blob — machine-readable, not for visual inspection
    "total_trades",      # trade_density_total provides equivalent information
    "base_strategy_id",  # Redundant with strategy column
}

# Columns with short text values — override text width logic to be data-driven (universal)
NARROW_TEXT_COLS = {
    "portfolio_engine_version",
    "timeframe",
}

# Explicit width overrides — bypass auto-sizing for specific columns (column_name_lower -> width)
COLUMN_WIDTH_OVERRIDES = {
    "portfolio_id": 22,   # IDs are 35-44 chars; 22 shows family+asset+timeframe, saves space
    "strategy":     26,   # Strategy names are long; 26 is a comfortable readable cap
    "rank":          6,   # 1-3 digit values; header wraps fine
    "exit_spread":  12,   # 6 decimal places (e.g. 0.000120)
    "net_pnl":      12,   # 6 decimal places (e.g. -0.001234)
    "portfolio_status": 12,
    "evaluation_timeframe": 12,
}

# Dropdown Columns (Column Name -> list of allowed values)
# Applied as Excel Data Validation (dropdown) on all data rows.
# Analysis_selection uses 0/1 (not True/False) so Excel stores it as the
# integer the DB writes back after control_panel --select-analysis.
DROPDOWN_COLS = {
    "Analysis_selection": ["0", "1"],
    "candidate_status": ["CORE", "WATCH", "FAIL", "LIVE", "REMOVE"],
}

# Strategy Master Filter — Preferred Column Order
# Analysis_selection sits right after return_dd_ratio for quick
# pick-and-choose while reviewing the FSP sheet.
STRATEGY_COLUMN_ORDER = [
    "run_id",
    "strategy",
    "symbol",
    "asset_class",
    "timeframe",
    "test_start",
    "test_end",
    "trading_period",
    "sqn",
    "total_trades",
    "trade_density",
    "total_net_profit",
    "gross_profit",
    "gross_loss",
    "profit_factor",
    "expectancy",
    "sharpe_ratio",
    "max_drawdown",
    "max_dd_pct",
    "return_dd_ratio",
    "Analysis_selection",    # 0/1 — picks rows for next composite_portfolio_analysis
    "candidate_status",
    "worst_5_loss_pct",
    "longest_loss_streak",
    "pct_time_in_market",
    "avg_bars_in_trade",
    "net_profit_high_vol",
    "net_profit_normal_vol",
    "net_profit_low_vol",
    "net_profit_asia",
    "net_profit_london",
    "net_profit_ny",
    "net_profit_strong_up",
    "net_profit_weak_up",
    "net_profit_neutral",
    "net_profit_weak_down",
    "net_profit_strong_down",
    "trades_strong_up",
    "trades_weak_up",
    "trades_neutral",
    "trades_weak_down",
    "trades_strong_down",
]

# Portfolio Ledger — Preferred Column Orders
# Keep rank out of canonical order so reference_capital remains column C.
# Multi-asset ("Portfolios" tab)
PORTFOLIO_COLUMN_ORDER = [
    "portfolio_id",
    "source_strategy",
    "reference_capital_usd",
    "portfolio_status",
    "burn_in_status",
    "evaluation_timeframe",
    "symbol_count",
    "trade_density_total",
    "trade_density_min",
    "profile_trade_density_total",
    "profile_trade_density_min",
    "theoretical_pnl",
    "realized_pnl",
    "sharpe",
    "max_dd_pct",
    "return_dd_ratio",
    "win_rate",
    "profit_factor",
    "expectancy",
    "total_trades",
    "exposure_pct",
    "equity_stability_k_ratio",
    "deployed_profile",
    "edge_quality",
    "peak_dd_ratio",
    "trades_accepted",
    "trades_rejected",
    "rejection_rate_pct",
    "realized_vs_theoretical_pnl",
    "peak_capital_deployed",
    "capital_overextension_ratio",
    "avg_concurrent",
    "max_concurrent",
    "p95_concurrent",
    "dd_max_concurrent",
    "full_load_cluster",
    "avg_pairwise_corr",
    "max_pairwise_corr_stress",
    "portfolio_net_profit_low_vol",
    "portfolio_net_profit_normal_vol",
    "portfolio_net_profit_high_vol",
    "parsed_fields",
    "portfolio_engine_version",
    "creation_timestamp",
    "constituent_run_ids",
]

# Single-asset ("Single-Asset Composites" tab)
# Drops correlation, regime-gate, and full_load columns (meaningless for single asset).
# Adds n_strategies.
SINGLE_ASSET_COLUMN_ORDER = [
    "portfolio_id",
    "source_strategy",
    "reference_capital_usd",
    "portfolio_status",
    "burn_in_status",
    "evaluation_timeframe",
    "n_strategies",
    "symbol_count",
    "trade_density_total",
    "trade_density_min",
    "profile_trade_density_total",
    "profile_trade_density_min",
    "theoretical_pnl",
    "realized_pnl",
    "sharpe",
    "max_dd_pct",
    "return_dd_ratio",
    "win_rate",
    "profit_factor",
    "expectancy",
    "total_trades",
    "exposure_pct",
    "equity_stability_k_ratio",
    "deployed_profile",
    "sqn",
    "peak_dd_ratio",
    "trades_accepted",
    "trades_rejected",
    "rejection_rate_pct",
    "realized_vs_theoretical_pnl",
    "peak_capital_deployed",
    "capital_overextension_ratio",
    "avg_concurrent",
    "max_concurrent",
    "p95_concurrent",
    "dd_max_concurrent",
    "portfolio_net_profit_low_vol",
    "portfolio_net_profit_normal_vol",
    "portfolio_net_profit_high_vol",
    "parsed_fields",
    "portfolio_engine_version",
    "creation_timestamp",
    "constituent_run_ids",
]

# Shadow Trades — Finalized column order (v2, 2026-04-06)
SHADOW_TRADES_COLUMN_ORDER = [
    "run_id",
    "symbol",
    "event_utc",
    "event_type",
    "strategy_id",
    "bar_time",
    "direction",
    "lot_size",
    "entry_price",
    "entry_price_source",
    "exit_price",
    "exit_price_source",
    "exit_spread",
    "net_pnl",
    "net_pnl_usd",
    "bars_held",
    "stop_price",
    "tp_price",
    "reason",
    "magic_number",
    "signal_hash",
    "event_id",
    "sequence_id",
    "burn_in_layer",
    "archetype",
    "lifecycle_status",
]

# Display-only header renames for portfolio profile.
# Column keys in DataFrames and code stay unchanged — this only affects
# what the user sees in the Excel header row.
PORTFOLIO_HEADER_DISPLAY = {
    "sharpe": "sharpe (ann.)",
    "equity_stability_k_ratio": "k_ratio (log)",
}
