"""
XAUUSD_1H_TREND_PULLBACK_L03_H2 - Generated by Strategy Provisioner
"""

# --- IMPORTS (Deterministic from Directive) ---
from indicators.structure.ema_slope import ema_slope
from indicators.structure.highest_high import highest_high
from indicators.volatility.atr import atr
from indicators.price.rsi import rsi
from indicators.volatility.volatility_regime import volatility_regime
from engines.filter_stack import FilterStack
import pandas as pd

class Strategy:

    # --- IDENTITY ---
    name = "XAUUSD_1H_TREND_PULLBACK_L03_H2"
    timeframe = "1h"

    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "entry_logic": {
            "atr_length": 14,
            "condition": "ema_slope_50_up_AND_three_lower_closes_AND_break_hh2_shift1",
            "lookback_bars": 2,
            "type": "intersection"
        },
        "entry_when_flat_only": True,
        "exit_logic": {
            "price_exit": "rsi2_above_85",
            "time_exit_bars": 14,
            "type": "dynamic_or_time"
        },
        "pyramiding": False,
        "reset_on_exit": True,
        "stop_loss": {
            "atr_multiplier": 2.3,
            "type": "atr_multiple"
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "indicators": [
        "indicators.structure.ema_slope",
        "indicators.structure.highest_high",
        "indicators.volatility.atr",
        "indicators.price.rsi",
        "indicators.volatility.volatility_regime"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "signature_version": 2,
    "trade_management": {
        "direction": "long_only",
        "reentry": {
            "allowed": False
        }
    },
    "volatility_filter": {
        "enabled": True,
        "operator": "gte",
        "required_regime": 0
    }
}
    # --- STRATEGY SIGNATURE END ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)
        self._active_direction = 0
        self._active_stop_price = None

    def prepare_indicators(self, df):
        """
        Compute directive-declared indicators and derived entry helpers.
        """
        entry_cfg = self.STRATEGY_SIGNATURE["execution_rules"]["entry_logic"]
        stop_cfg = self.STRATEGY_SIGNATURE["execution_rules"]["stop_loss"]

        # ema_slope_50_up
        df["ema_slope_50"] = ema_slope(df["close"], period=50, slope_window=1)

        # break_hh2_shift1
        hh_window = int(entry_cfg["lookback_bars"])
        df["hh_2_prev"] = highest_high(df["high"], window=hh_window, shift=1)

        # atr_length and stop distance
        atr_len = int(entry_cfg["atr_length"])
        df["atr"] = atr(df, window=atr_len)
        df["stop_distance"] = float(stop_cfg["atr_multiplier"]) * df["atr"]

        # rsi2_above_85 exit condition
        df["rsi_2"] = rsi(df["close"], period=2)

        # three_lower_closes for prior 3 bars (pullback before breakout bar)
        df["three_lower_closes"] = (
            (df["close"].shift(1) < df["close"].shift(2)) &
            (df["close"].shift(2) < df["close"].shift(3))
        )

        # engine-required market state metadata
        reg_df = volatility_regime(df["atr"], window=100)
        df["volatility_regime"] = reg_df["regime"] if isinstance(reg_df, pd.DataFrame) else reg_df

        return df

    def check_entry(self, ctx):
        """
        Return entry signal dict or None.
        """
        # Architectural Requirement: Allow FilterStack to gate entry
        if not self.filter_stack.allow_trade(ctx):
            return None

        # Do not re-arm while already tracking an open trade.
        if self._active_direction != 0:
            return None

        row = ctx.row

        ema_slope_val = row.get("ema_slope_50")
        pullback_ok = row.get("three_lower_closes")
        close_val = row.get("close")
        hh_prev = row.get("hh_2_prev")

        if ema_slope_val is None or ema_slope_val <= 0:
            return None
        if not bool(pullback_ok):
            return None
        if close_val is None or hh_prev is None or close_val <= hh_prev:
            return None

        stop_dist = row.get("stop_distance")
        if stop_dist is None or stop_dist <= 0:
            return None

        stop_price = close_val - stop_dist
        self._active_direction = 1
        self._active_stop_price = stop_price

        return {
            "signal": 1,
            "stop_price": stop_price,
        }

    def check_exit(self, ctx):
        """
        Return True to close position.
        """
        # Guard against stale internal state.
        if self._active_direction == 0:
            return False

        row = ctx.row
        close_val = row.get("close")
        low_val = row.get("low", close_val)

        # Stop-loss precedence: exit immediately when breached.
        if self._active_stop_price is not None and low_val is not None:
            if low_val <= self._active_stop_price:
                self._active_direction = 0
                self._active_stop_price = None
                return True

        exit_cfg = self.STRATEGY_SIGNATURE["execution_rules"]["exit_logic"]

        rsi_val = row.get("rsi_2")
        if rsi_val is not None and rsi_val > 85.0:
            self._active_direction = 0
            self._active_stop_price = None
            return True

        if ctx.bars_held >= int(exit_cfg["time_exit_bars"]):
            self._active_direction = 0
            self._active_stop_price = None
            return True

        return False
