"""
47_STR_FX_1H_CHOCH_S01_V2_P00 — Generated by Strategy Provisioner
Timestamp: 2026-04-14T13:27:08.806851
Directive: 47_STR_FX_1H_CHOCH_S01_V2_P00
"""

# --- IMPORTS (Deterministic from Directive) ---
from indicators.volatility.atr import atr
from indicators.structure.choch_v2 import choch_v2
from engines.filter_stack import FilterStack

class Strategy:

    # --- IDENTITY ---
    name = "47_STR_FX_1H_CHOCH_S01_V2_P00"
    timeframe = "1h"

    # --- PARAMETERS ---
    _ATR_WINDOW = 14
    _SL_ATR_MULT = 1.5
    _TP_ATR_MULT = 3.0
    
    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "entry_logic": {
            "type": "choch_structural_break"
        },
        "entry_when_flat_only": True,
        "exit_logic": {
            "type": "sl_or_tp"
        },
        "pyramiding": False,
        "reset_on_exit": True,
        "stop_loss": {
            "atr_multiplier": 1.5,
            "type": "atr_multiple"
        },
        "take_profit": {
            "atr_multiplier": 3.0,
            "enabled": True,
            "type": "atr_multiple"
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "exit_rules": {
        "type": "sl_tp"
    },
    "indicators": [
        "indicators.volatility.atr",
        "indicators.structure.choch_v2"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "position_management": {
        "lots": 0.01
    },
    "signal_version": 3,
    "signature_version": 2,
    "state_machine": {
        "entry": {
            "direction": "long_and_short",
            "trigger": "signal_bar"
        },
        "no_reentry_after_stop": True,
        "session_reset": "none"
    },
    "trade_management": {
        "direction_restriction": "long_and_short",
        "reentry": {
            "allowed": True
        },
        "session_reset": "none"
    },
    "version": 1
}
    # --- STRATEGY SIGNATURE END ---
    # --- SIGNATURE HASH: 0aedbca46b17b79c ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    @staticmethod
    def _schema_sample() -> dict:
        return {
            "signal": 1,
            "stop_price": 0.0,
            "tp_price": 0.0,
            "entry_reference_price": 0.0,
            "entry_reason": "choch_v2_bullish_break",
        }

    def prepare_indicators(self, df):
        df['atr'] = atr(df, self._ATR_WINDOW)
        df = choch_v2(df)
        return df

    def check_entry(self, ctx):
        if not self.filter_stack.allow_trade(ctx):
            return None
        event = int(ctx.require('choch_event_v2'))
        if event == 0:
            return None
        close = float(ctx.require('close'))
        atr_val = float(ctx.require('atr'))
        if atr_val <= 0 or not (atr_val == atr_val):
            return None
        if event == 1:
            reason = "choch_v2_bullish_break"
        else:
            reason = "choch_v2_bearish_break"
        return {
            "signal": event,
            "entry_reference_price": close,
            "entry_reason": reason,
        }

    def check_exit(self, ctx):
        return False

# --- CAPABILITY REQUIREMENTS START ---
REQUIRED_CAPABILITIES = [
    "execution.entry.v1",
    "execution.exit.v1",
]
REQUIRED_CONTRACT_IDS = [
    "sha256:378a1931d1edebd8e736b402f010eaed29e9f47412e7c522e6c49964f6c56704",
]
# --- CAPABILITY REQUIREMENTS END ---
