"""
07_MR_XAUUSD_15M_SMI_SMIFILT_S02_V1_P02 -- Generated by Strategy Provisioner
Timestamp: 2026-03-09T13:20:12.122324
Directive: 07_MR_XAUUSD_15M_SMI_SMIFILT_S02_V1_P02

S02_V1_P02: Volatility regime gate -- allow LOW + HIGH only (block NORMAL).
Setup threshold = -50 (identical to S01_P00 baseline).

Hypothesis: S01_P00 regime breakdown showed NORMAL-vol regime destroyed aggregate
edge (-$198 on 44 trades) while LOW (+$62) and HIGH (+$144) were profitable.
Gating on LOW+HIGH only should isolate the structural edge and eliminate the
sustained-trend false-setup contamination that occurs in NORMAL vol.
"""

import pandas as pd

# --- IMPORTS (Deterministic from Directive) ---
from indicators.trend.linreg_regime import linreg_regime
from indicators.trend.linreg_regime_htf import linreg_regime_htf
from indicators.trend.kalman_regime import kalman_regime
from indicators.trend.trend_persistence import trend_persistence
from indicators.trend.efficiency_ratio_regime import efficiency_ratio_regime
from indicators.volatility.volatility_regime import volatility_regime
from indicators.volatility.atr import atr
from indicators.momentum.stochastic_momentum_index import stochastic_momentum_index
from engines.filter_stack import FilterStack

# ---------------------------------------------------------------------------
# Strategy constants
# ---------------------------------------------------------------------------
_SMI_PERIOD       = 14
_SMI_SMOOTH1      = 3
_SMI_SMOOTH2      = 3
_SMI_SIGNAL       = 3

_SETUP_THRESHOLD  = -50.0    # 1H SMI setup filter (same as S01_P00)
_TRIGGER_RECOVERY = -40.0    # 15M SMI recovery zone threshold
_EXIT_REVERSION   = -10.0    # 1H SMI mean-reversion exit threshold

_ALLOWED_REGIMES  = {-1, 1}   # -1=low, 1=high; 0=normal excluded


class Strategy:

    # --- IDENTITY ---
    name = "07_MR_XAUUSD_15M_SMI_SMIFILT_S02_V1_P02"
    timeframe = "15m"

    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "stop_loss": {
            "fixed_points": 50,
            "type": "fixed_usd"
        },
        "take_profit": {
            "enabled": False
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "exit_rules": {
        "condition_1": {
            "condition": "greater_than",
            "indicator": "smi_1h",
            "threshold": -10,
            "type": "indicator_threshold"
        },
        "condition_2": {
            "timing": "penultimate_bar_of_day",
            "type": "time_based"
        },
        "logic": "OR",
        "type": "composite"
    },
    "indicators": [
        "indicators.trend.linreg_regime",
        "indicators.trend.linreg_regime_htf",
        "indicators.trend.kalman_regime",
        "indicators.trend.trend_persistence",
        "indicators.trend.efficiency_ratio_regime",
        "indicators.volatility.volatility_regime",
        "indicators.volatility.atr",
        "indicators.momentum.stochastic_momentum_index"
    ],
    "mean_reversion_rules": {
        "exit_reversion_threshold": -10,
        "setup_condition": "less_than",
        "setup_indicator": "smi_1h",
        "setup_threshold": -50,
        "setup_timeframe": "1H",
        "trigger_recovery_threshold": -40,
        "trigger_timeframe": "15M",
        "trigger_type": "signal_cross_with_recovery"
    },
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "position_management": {
        "lots": 0.01
    },
    "signature_version": 2,
    "state_machine": {
        "entry": {
            "direction": "long_only",
            "trigger": "signal_bar"
        },
        "no_reentry_after_stop": True,
        "session_reset": "new_day"
    },
    "trade_management": {
        "direction_restriction": "long_only",
        "max_trades_per_session": 1,
        "reentry": {
            "allowed": False
        }
    },
    "volatility_filter": {
        "allow_regime": "LOW,HIGH",
        "type": "volatility_regime"
    }
}
    # --- STRATEGY SIGNATURE END ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    def prepare_indicators(self, df):
        if not isinstance(df.index, pd.DatetimeIndex):
            df = df.set_index(pd.DatetimeIndex(df['timestamp']))

        # Engine-required authoritative columns
        df['atr'] = atr(df, window=14)
        vr = volatility_regime(df['atr'], window=100)
        df['volatility_regime'] = vr['regime']

        # 15M SMI
        smi_15m = stochastic_momentum_index(
            df['high'], df['low'], df['close'],
            period=_SMI_PERIOD, smooth1=_SMI_SMOOTH1,
            smooth2=_SMI_SMOOTH2, signal_period=_SMI_SIGNAL
        )
        df['smi_15m']             = smi_15m['smi']
        df['smi_signal_15m']      = smi_15m['smi_signal']
        df['smi_15m_prev']        = df['smi_15m'].shift(1)
        df['smi_signal_15m_prev'] = df['smi_signal_15m'].shift(1)

        # 1H SMI (resampled from 15M)
        h1_df = pd.DataFrame({
            'high':  df['high'].resample('1h').max(),
            'low':   df['low'].resample('1h').min(),
            'close': df['close'].resample('1h').last(),
        }).dropna()

        smi_1h = stochastic_momentum_index(
            h1_df['high'], h1_df['low'], h1_df['close'],
            period=_SMI_PERIOD, smooth1=_SMI_SMOOTH1,
            smooth2=_SMI_SMOOTH2, signal_period=_SMI_SIGNAL
        )

        smi_by_hour = smi_1h['smi'].shift(1).to_dict()
        df['smi_1h'] = df.index.floor('1h').map(smi_by_hour)
        df['smi_1h'] = df['smi_1h'].ffill()

        # Session bar labels
        dates = df.index.normalize()
        bar_number  = df.groupby(dates).cumcount()
        bars_in_day = df.groupby(dates)[df.columns[0]].transform('count')
        df['is_penultimate_bar'] = bar_number == (bars_in_day - 2)

        return df

    def check_entry(self, ctx):
        if not self.filter_stack.allow_trade(ctx):
            return None

        row = ctx.row

        # Gate 0: Volatility regime — only LOW or HIGH, block NORMAL
        regime = row.get('volatility_regime')
        if regime not in _ALLOWED_REGIMES:
            return None

        # Gate 1: 1H structural oversold setup active
        smi_1h = row.get('smi_1h')
        if smi_1h is None or pd.isna(smi_1h) or smi_1h >= _SETUP_THRESHOLD:
            return None

        # Gate 2: 15M SMI signal-line upward cross
        smi_now  = row.get('smi_15m')
        sig_now  = row.get('smi_signal_15m')
        smi_prev = row.get('smi_15m_prev')
        sig_prev = row.get('smi_signal_15m_prev')

        if any(pd.isna(v) or v is None for v in [smi_now, sig_now, smi_prev, sig_prev]):
            return None

        if not ((smi_prev <= sig_prev) and (smi_now > sig_now)):
            return None

        # Gate 3: 15M SMI must be in recovery zone
        if smi_now <= _TRIGGER_RECOVERY:
            return None

        return {"signal": 1}

    def check_exit(self, ctx):
        row = ctx.row

        smi_1h = row.get('smi_1h')
        if smi_1h is not None and not pd.isna(smi_1h) and smi_1h > _EXIT_REVERSION:
            return True

        if row.get('is_penultimate_bar', False):
            return True

        return False
