"""
06_PA_XAUUSD_15M_DAYOC_REGFILT_S02_V1_P13 -- Generated by Strategy Provisioner
Timestamp: 2026-03-08T14:46:35.347964
Directive: 06_PA_XAUUSD_15M_DAYOC_REGFILT_S02_V1_P13

P13: Interaction patch -- threshold=37 (best from Axis 1) x window=120 (best from Axis 2).
     15M timeframe. Warm-up from 2023-01-01; trade window opens 2024-01-01.
"""

import pandas as pd

# --- IMPORTS (Deterministic from Directive) ---
from indicators.trend.linreg_regime import linreg_regime
from indicators.trend.linreg_regime_htf import linreg_regime_htf
from indicators.trend.kalman_regime import kalman_regime
from indicators.trend.trend_persistence import trend_persistence
from indicators.trend.efficiency_ratio_regime import efficiency_ratio_regime
from indicators.volatility.volatility_regime import volatility_regime
from indicators.volatility.atr import atr
from indicators.volatility.atr_percentile import atr_percentile
from engines.filter_stack import FilterStack

# Patch parameters
_LOW_THRESHOLD = 0.37
_PERCENTILE_WINDOW = 120
_TRADE_WINDOW_START = pd.Timestamp("2024-01-01", tz="UTC")


class Strategy:

    # --- IDENTITY ---
    name = "06_PA_XAUUSD_15M_DAYOC_REGFILT_S02_V1_P13"
    timeframe = "15m"

    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "stop_loss": {
            "fixed_points": 50,
            "type": "fixed_usd"
        },
        "take_profit": {
            "enabled": False
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "exit_rules": {
        "timing": "penultimate_bar_of_day",
        "type": "time_based"
    },
    "indicators": [
        "indicators.trend.linreg_regime",
        "indicators.trend.linreg_regime_htf",
        "indicators.trend.kalman_regime",
        "indicators.trend.trend_persistence",
        "indicators.trend.efficiency_ratio_regime",
        "indicators.volatility.volatility_regime",
        "indicators.volatility.atr",
        "indicators.volatility.atr_percentile"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "position_management": {
        "lots": 0.01
    },
    "signature_version": 2,
    "state_machine": {
        "entry": {
            "direction": "long_only",
            "trigger": "first_bar_of_day"
        },
        "no_reentry_after_stop": True,
        "session_reset": "new_day"
    },
    "trade_management": {
        "direction_restriction": "long_only",
        "max_trades_per_session": 1,
        "reentry": {
            "allowed": False
        }
    },
    "volatility_filter": {
        "allow_regime": "LOW",
        "atr_period": 14,
        "lookback_source": "previous_day",
        "low_threshold_pct": 37,
        "type": "atr_percentile",
        "window": 120
    }
}
    # --- STRATEGY SIGNATURE END ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    def prepare_indicators(self, df):
        """
        Compute and attach all indicators. Must return the dataframe.

        Data is loaded from 2023-01-01 for warm-up. ATR(14) + 120-day percentile
        are stable well before 2024-01-01. Entries are gated by in_trade_window.
        """
        # Ensure DatetimeIndex for resample ('D') -- engine sets index after this call
        if not isinstance(df.index, pd.DatetimeIndex):
            df = df.set_index(pd.DatetimeIndex(df['timestamp']))

        # --- 15M ATR and volatility regime (engine-required authoritative columns) ---
        df['atr'] = atr(df, window=14)
        vr = volatility_regime(df['atr'], window=100)
        df['volatility_regime'] = vr['regime']

        # --- Daily ATR regime filter (previous day's daily ATR percentile) ---
        # Build daily OHLC from 15M bars
        daily_high = df['high'].resample('D').max()
        daily_low = df['low'].resample('D').min()
        daily_close = df['close'].resample('D').last()
        daily_df = pd.DataFrame({
            'high': daily_high,
            'low': daily_low,
            'close': daily_close,
        }).dropna()

        # Daily ATR(14) -> shift(1) for previous day -> rolling percentile rank
        daily_atr_series = atr(daily_df, window=14)
        daily_atr_prev = daily_atr_series.shift(1)
        daily_atr_pct = atr_percentile(daily_atr_prev, window=_PERCENTILE_WINDOW)

        # Classify: LOW if percentile rank < _LOW_THRESHOLD
        daily_regime = daily_atr_pct.map(
            lambda x: 'LOW' if pd.notna(x) and x < _LOW_THRESHOLD else ('NORMAL' if pd.notna(x) else None)
        )

        # Map daily regime back to 15M bars by calendar date
        regime_by_date = daily_regime.dropna().to_dict()
        df['atr_regime_daily'] = df.index.normalize().map(regime_by_date)

        # --- Trade window gate (warm-up period excluded from entries) ---
        df['in_trade_window'] = df.index >= _TRADE_WINDOW_START

        # --- Session bar labeling ---
        dates = df.index.normalize()
        bar_number = df.groupby(dates).cumcount()
        bars_in_day = df.groupby(dates)[df.columns[0]].transform('count')
        df['bar_number'] = bar_number
        df['bars_in_day'] = bars_in_day
        df['is_first_bar'] = bar_number == 0
        df['is_penultimate_bar'] = bar_number == (bars_in_day - 2)

        return df

    def check_entry(self, ctx):
        """
        Long entry: within trade window, first bar of day, previous day daily ATR LOW.
        """
        # Architectural Requirement: Allow FilterStack to gate entry
        if not self.filter_stack.allow_trade(ctx):
            return None

        row = ctx.row

        # Warm-up gate: no entries before 2024-01-01
        if not row.get('in_trade_window', False):
            return None

        # Must be first bar of the day
        if not row.get('is_first_bar', False):
            return None

        # Previous day's daily ATR must be LOW volatility
        if row.get('atr_regime_daily') != 'LOW':
            return None

        return {"signal": 1}

    def check_exit(self, ctx):
        """
        Exit at penultimate bar of day.
        """
        return bool(ctx.row.get('is_penultimate_bar', False))
