"""
02_VOL_NAS100_1D_VOLEXP_ATRFILT_S02_V1_P00 — Generated by Strategy Provisioner
Timestamp: 2026-03-10T19:07:48.886652
Directive: 02_VOL_NAS100_1D_VOLEXP_ATRFILT_S02_V1_P00
"""

# --- IMPORTS (Deterministic from Directive) ---
from indicators.structure.highest_high import highest_high
from indicators.volatility.atr import atr
from indicators.volatility.atr_percentile import atr_percentile
from indicators.volatility.volatility_regime import volatility_regime
from engines.filter_stack import FilterStack

class Strategy:

    # --- IDENTITY ---
    name = "02_VOL_NAS100_1D_VOLEXP_ATRFILT_S02_V1_P00"
    timeframe = "1d"

    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "entry_logic": {
            "atr_length": 10,
            "condition": "close_less_than_hh_minus_atr",
            "lookback_bars": 4,
            "type": "volatility_pullback"
        },
        "entry_when_flat_only": True,
        "exit_logic": {
            "price_exit": "close_greater_than_hh_prev",
            "time_exit_bars": 4,
            "type": "dynamic_or_time"
        },
        "pyramiding": False,
        "reset_on_exit": True,
        "stop_loss": {
            "type": "none"
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "indicators": [
        "indicators.structure.highest_high",
        "indicators.volatility.atr",
        "indicators.volatility.atr_percentile",
        "indicators.volatility.volatility_regime"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "signature_version": 2,
    "trade_management": {
        "direction": "long_only",
        "reentry": {
            "allowed": False
        },
        "session_reset": "none"
    },
    "volatility_filter": {
        "atr_length": 14,
        "atr_percentile_lookback": 100,
        "condition": "atr_percentile_above_threshold",
        "cooldown_bars": 4,
        "threshold": 75
    }
}
    # --- STRATEGY SIGNATURE END ---

    # Directive params
    _LOOKBACK = 4
    _ATR_LEN  = 10
    _TIME_EXIT_BARS = 4
    _ATR_PCT_THRESHOLD = 0.75  # 75th percentile

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    def prepare_indicators(self, df):
        df['atr'] = atr(df, window=14)
        vr = volatility_regime(df['atr'], window=100)
        df['volatility_regime'] = vr['regime']

        # Entry signal indicators
        df['hh'] = highest_high(df['high'], window=self._LOOKBACK)
        df['atr_sig'] = atr(df, window=self._ATR_LEN)

        # Previous bar HH for price exit
        df['hh_prev'] = df['hh'].shift(1)

        # ATR percentile filter (14-period ATR, 100-bar lookback)
        df['atr_pct'] = atr_percentile(df['atr'], window=100)

        return df

    def check_entry(self, ctx):
        if not self.filter_stack.allow_trade(ctx):
            return None

        row = ctx.row
        close  = row.get('close')
        hh     = row.get('hh')
        atr_e  = row.get('atr_sig')
        atr_p  = row.get('atr_pct')

        if any(v is None for v in [close, hh, atr_e, atr_p]):
            return None

        # Volatility filter: ATR percentile must be above threshold (high volatility)
        if atr_p < self._ATR_PCT_THRESHOLD:
            return None

        # Entry: pullback — close below HH minus ATR
        if close < (hh - atr_e):
            return {"signal": 1}

        return None

    def check_exit(self, ctx):
        row = ctx.row
        close    = row.get('close')
        hh_prev  = row.get('hh_prev')

        # Time exit
        if ctx.bars_held >= self._TIME_EXIT_BARS:
            return True

        # Price exit: close recovers above previous HH
        if close is not None and hh_prev is not None and close > hh_prev:
            return True

        return False
