"""
08_BRK_XAUUSD_15M_IBREAK_REGFILT_S01_V1_P04 -- Generated by Strategy Provisioner
Timestamp: 2026-03-09T17:59:57.306501
Directive: 08_BRK_XAUUSD_15M_IBREAK_REGFILT_S01_V1_P04

S01_V1_P04: Asian Session Breakout — 1.5R take profit exit.

Change from P00:
  P00 exits only at penultimate bar of day.
  P04 adds a 1.5R take profit: exit when unrealized PnL reaches 1.5x the
  $50 stop loss ($75 profit target). This locks in winners early instead
  of holding through NY session noise.

  Penultimate bar of day retained as safety backstop (OR logic).
  Stop is $50 fixed USD. 1R = $50. Target = $75.

  For XAUUSD at 0.01 lot (1 oz), $1 price move = $1.
  So 1.5R = $75 price distance from entry.

Entry logic: identical to P00.
"""

import pandas as pd
import numpy as np

# --- IMPORTS (Deterministic from Directive) ---
from indicators.trend.linreg_regime import linreg_regime
from indicators.trend.linreg_regime_htf import linreg_regime_htf
from indicators.trend.kalman_regime import kalman_regime
from indicators.trend.trend_persistence import trend_persistence
from indicators.trend.efficiency_ratio_regime import efficiency_ratio_regime
from indicators.volatility.volatility_regime import volatility_regime
from indicators.volatility.atr import atr
from indicators.structure.range_breakout_session import session_range_structure
from engines.filter_stack import FilterStack

# ---------------------------------------------------------------------------
# Strategy constants
# ---------------------------------------------------------------------------
_SESSION_START     = "01:00"
_SESSION_END       = "07:00"
_RANGE_QUALITY_MIN = 0.3
_RANGE_QUALITY_MAX = 2.0
_ALLOWED_REGIMES   = {0, 1}
_STOP_USD          = 50.0
_R_MULTIPLE        = 1.5
_TARGET_DISTANCE   = _STOP_USD * _R_MULTIPLE  # $75 price distance

class Strategy:

    # --- IDENTITY ---
    name = "08_BRK_XAUUSD_15M_IBREAK_REGFILT_S01_V1_P04"
    timeframe = "15m"

    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "stop_loss": {
            "fixed_points": 50,
            "type": "fixed_usd"
        },
        "take_profit": {
            "enabled": False
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "exit_rules": {
        "condition_1": {
            "target": 1.5,
            "type": "r_multiple"
        },
        "condition_2": {
            "timing": "penultimate_bar_of_day",
            "type": "time_based"
        },
        "logic": "OR",
        "type": "composite"
    },
    "indicators": [
        "indicators.trend.linreg_regime",
        "indicators.trend.linreg_regime_htf",
        "indicators.trend.kalman_regime",
        "indicators.trend.trend_persistence",
        "indicators.trend.efficiency_ratio_regime",
        "indicators.volatility.volatility_regime",
        "indicators.volatility.atr",
        "indicators.structure.range_breakout_session"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "position_management": {
        "lots": 0.01
    },
    "range_definition": {
        "close_confirmation": True,
        "r_multiple_target": 1.5,
        "range_quality_max": 2.0,
        "range_quality_min": 0.3,
        "session_end": "07:00",
        "session_start": "01:00"
    },
    "signature_version": 2,
    "state_machine": {
        "entry": {
            "direction": "long_and_short",
            "trigger": "signal_bar"
        },
        "no_reentry_after_stop": True,
        "session_reset": "new_day"
    },
    "trade_management": {
        "direction_restriction": "long_and_short",
        "max_trades_per_session": 1,
        "reentry": {
            "allowed": False
        }
    },
    "volatility_filter": {
        "allow_regime": "NORMAL,HIGH",
        "type": "volatility_regime"
    }
}
    # --- STRATEGY SIGNATURE END ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)
        self._entry_price = None


    def prepare_indicators(self, df):
        if not isinstance(df.index, pd.DatetimeIndex):
            df = df.set_index(pd.DatetimeIndex(df['timestamp']))

        # Engine-required authoritative columns
        df['atr'] = atr(df, window=14)
        vr = volatility_regime(df['atr'], window=100)
        df['volatility_regime'] = vr['regime']

        # Session range structure
        srs = session_range_structure(df, session_start=_SESSION_START,
                                      session_end=_SESSION_END)
        df['session_high']    = srs['session_high']
        df['session_low']     = srs['session_low']
        df['range_points']    = srs['range_points']
        df['break_direction'] = srs['break_direction']

        # Range quality ratio
        df['range_atr_ratio'] = df['range_points'] / df['atr']

        # Penultimate bar safety backstop
        dates = df.index.normalize()
        bar_number  = df.groupby(dates).cumcount()
        bars_in_day = df.groupby(dates)[df.columns[0]].transform('count')
        df['is_penultimate_bar'] = bar_number == (bars_in_day - 2)

        return df

    def check_entry(self, ctx):
        if not self.filter_stack.allow_trade(ctx):
            return None

        row = ctx.row

        regime = row.get('volatility_regime')
        if regime not in _ALLOWED_REGIMES:
            return None

        break_dir = row.get('break_direction', 0)
        if break_dir == 0:
            return None

        ratio = row.get('range_atr_ratio')
        if ratio is None or pd.isna(ratio):
            return None
        if ratio < _RANGE_QUALITY_MIN or ratio > _RANGE_QUALITY_MAX:
            return None

        close = row.get('close')
        session_high = row.get('session_high')
        session_low  = row.get('session_low')

        if any(v is None or pd.isna(v) for v in [close, session_high, session_low]):
            return None

        if break_dir == 1 and close > session_high:
            self._entry_price = close
            return {"signal": 1}
        if break_dir == -1 and close < session_low:
            self._entry_price = close
            return {"signal": -1}

        return None

    def check_exit(self, ctx):
        row = ctx.row

        # Exit 1: 1.5R take profit
        if self._entry_price is not None:
            close = row.get('close')
            direction = ctx.direction
            if close is not None and direction != 0:
                unrealized = (close - self._entry_price) * direction
                if unrealized >= _TARGET_DISTANCE:
                    self._entry_price = None
                    return True

        # Exit 2: Penultimate bar safety backstop
        if row.get('is_penultimate_bar', False):
            self._entry_price = None
            return True

        return False
