"""
49_STR_XAU_1H_CHOCH_S01_V1_P00 — Generated by Strategy Provisioner
Timestamp: 2026-04-14T13:43:45.773883
Directive: 49_STR_XAU_1H_CHOCH_S01_V1_P00
"""

# --- IMPORTS (Deterministic from Directive) ---
from indicators.volatility.atr import atr
from indicators.structure.choch_v3 import choch_v3
from engines.filter_stack import FilterStack

class Strategy:

    # --- IDENTITY ---
    name = "49_STR_XAU_1H_CHOCH_S01_V1_P00"
    timeframe = "1h"

    # --- PARAMETERS ---
    _ATR_WINDOW = 14
    _SL_ATR_MULT = 1.5
    _TP_ATR_MULT = 3.0
    
    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "entry_logic": {
            "type": "choch_structural_break"
        },
        "entry_when_flat_only": True,
        "exit_logic": {
            "type": "sl_or_tp"
        },
        "pyramiding": False,
        "reset_on_exit": True,
        "stop_loss": {
            "atr_multiplier": 1.5,
            "type": "atr_multiple"
        },
        "take_profit": {
            "atr_multiplier": 3.0,
            "enabled": True,
            "type": "atr_multiple"
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "exit_rules": {
        "type": "sl_tp"
    },
    "indicators": [
        "indicators.volatility.atr",
        "indicators.structure.choch_v3"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "position_management": {
        "lots": 0.01
    },
    "repeat_override_reason": "Signal-primitive change: Ideas 46/47/48 used CHOCH_V2 (pivot break only, no structure gate). Ideas 49/50/51 use CHOCH_V3 which adds a minimal structure precondition (must have observed HH+HL or LL+LH on the last two pivots of each type before a break qualifies). This is a strict subset of V2 and emits fewer, context-conditioned events. The two are mechanically different signal primitives and prior CHOCH runs at this idea are not comparable.",
    "signature_version": 2,
    "state_machine": {
        "entry": {
            "direction": "long_and_short",
            "trigger": "signal_bar"
        },
        "no_reentry_after_stop": True,
        "session_reset": "none"
    },
    "trade_management": {
        "direction_restriction": "long_and_short",
        "reentry": {
            "allowed": True
        },
        "session_reset": "none"
    },
    "version": 1
}
    # --- STRATEGY SIGNATURE END ---
    # --- SIGNATURE HASH: 8a1f832683732807 ---

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    @staticmethod
    def _schema_sample() -> dict:
        return {
            "signal": 1,
            "stop_price": 0.0,
            "tp_price": 0.0,
            "entry_reference_price": 0.0,
            "entry_reason": "choch_v3_bullish_break",
        }

    def prepare_indicators(self, df):
        df['atr'] = atr(df, self._ATR_WINDOW)
        df = choch_v3(df)
        return df

    def check_entry(self, ctx):
        if not self.filter_stack.allow_trade(ctx):
            return None
        event = int(ctx.require('choch_event_v3'))
        if event == 0:
            return None
        close = float(ctx.require('close'))
        atr_val = float(ctx.require('atr'))
        if atr_val <= 0 or not (atr_val == atr_val):
            return None
        if event == 1:
            reason = "choch_v3_bullish_break"
        else:
            reason = "choch_v3_bearish_break"
        return {
            "signal": event,
            "entry_reference_price": close,
            "entry_reason": reason,
        }

    def check_exit(self, ctx):
        return False
