"""basket_provenance.py — per-run code snapshot for basket directives.

Brings basket runs to provenance parity with single-strategy runs. A
single-strategy run snapshots its strategy.py into runs/<run_id>/strategy.py
(write-once; Snapshot Immutability, AGENT.md #4) so the run record pins the
exact code that executed. Basket runs instead import their leg strategies
(tools/recycle_strategies.py) and recycle rule (tools/recycle_rules/<rule>.py)
live from tools/, so without a snapshot a past basket run cannot be reproduced
once that shared code changes — the run records only `rule_name@version`, a
symbolic reference whose code can drift.

This module copies the EXACT leg-strategy + rule source files that executed
(resolved via inspect.getsourcefile) into runs/<run_id>/basket_code/,
write-once, with a code_manifest.json recording each file's canonical
(LF-normalized) sha256 + rule_name@version + the leg-strategy class names.

Scope: provenance only — a record of what ran. It does NOT change execution
(the run still imports live, unlike the single-strategy load-from-snapshot
path). Home: the run folder (prunable). Per operator direction 2026-06-01,
per-run provenance belongs in the prunable run folder, NOT DRY_RUN_VAULT,
which is a curated store for promotable artifacts only.
"""
from __future__ import annotations

import hashlib
import inspect
import json
import shutil
from pathlib import Path

import yaml

from tools.capital.capital_broker_spec import broker_spec_path
from tools.recycle_rules import rule_class_for
from tools.verify_engine_integrity import canonical_sha256


SNAPSHOT_DIRNAME = "basket_code"
MANIFEST_NAME = "code_manifest.json"

PROJECT_ROOT = Path(__file__).resolve().parent.parent
# Sidecar pinning each rule_name@version to the canonical sha256 of its module
# file. Machine-generated by tools/generate_recycle_rule_hashes.py (human-only)
# and read by namespace_gate to reject a rule whose code drifted from its
# registered version. Lives alongside registry.yaml but is kept SEPARATE so the
# hand-authored, comment-rich registry is never machine-rewritten (mirrors the
# tools_manifest.json / GUARD_FILES split).
RULE_CODE_HASHES_PATH = (
    PROJECT_ROOT / "governance" / "recycle_rules" / "rule_code_hashes.yaml"
)


class BasketProvenanceError(RuntimeError):
    """Raised when a write-once basket_code snapshot would be overwritten by
    different code (snapshot drift / tamper-evidence)."""


def _rel_under_tools(src: Path, project_root: Path) -> str:
    """Path of a source file relative to tools/ (so recycle_rules/<x>.py keeps
    its subdir), else the bare filename if it lives outside tools/."""
    try:
        return src.resolve().relative_to((project_root / "tools").resolve()).as_posix()
    except Exception:
        return src.name


def collect_basket_source_files(rule_name: str, rule_version, leg_strategies,
                                *, project_root) -> dict[str, Path]:
    """Resolve the unique source files that defined the executed rule + leg
    strategies. Returns {relpath_under_tools: absolute Path}, rule first.
    Resolution failures are skipped (provenance is best-effort, never fatal).
    """
    project_root = Path(project_root)
    files: dict[str, Path] = {}

    try:
        rule_cls = rule_class_for(rule_name, int(rule_version))
        rsrc = inspect.getsourcefile(rule_cls)
        if rsrc:
            p = Path(rsrc)
            files[_rel_under_tools(p, project_root)] = p
    except Exception:
        pass

    for strat in (leg_strategies or {}).values():
        try:
            ssrc = inspect.getsourcefile(type(strat))
            if ssrc:
                p = Path(ssrc)
                files[_rel_under_tools(p, project_root)] = p
        except Exception:
            continue

    return files


def snapshot_basket_code(run_dir, *, rule_name: str, rule_version,
                         leg_strategies, project_root) -> dict:
    """Write runs/<run_id>/basket_code/ with the executed source files +
    code_manifest.json, then return the manifest dict.

    Write-once: if the snapshot already exists, verify its recorded hashes
    match the current code and return the prior manifest; raise
    BasketProvenanceError on any drift (mirrors Snapshot Immutability).
    """
    run_dir = Path(run_dir)
    project_root = Path(project_root)
    snap_dir = run_dir / SNAPSHOT_DIRNAME
    manifest_path = snap_dir / MANIFEST_NAME

    files = collect_basket_source_files(
        rule_name, rule_version, leg_strategies, project_root=project_root,
    )
    hashes = {rel: canonical_sha256(src).lower() for rel, src in files.items()}
    classes = sorted({type(s).__name__ for s in (leg_strategies or {}).values()})
    manifest = {
        "rule": f"{rule_name}@{rule_version}",
        "rule_name": rule_name,
        "rule_version": int(rule_version),
        "leg_strategy_classes": classes,
        "files": hashes,  # relpath under tools/ -> canonical (LF) sha256
    }

    if manifest_path.exists():
        prior = json.loads(manifest_path.read_text(encoding="utf-8"))
        if prior.get("files") != hashes:
            raise BasketProvenanceError(
                f"basket_code snapshot drift in {snap_dir}: existing manifest "
                f"hashes do not match current code. A run folder's code "
                f"snapshot is write-once (Snapshot Immutability)."
            )
        return prior

    snap_dir.mkdir(parents=True, exist_ok=True)
    for rel, src in files.items():
        dest = snap_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)  # exact byte copy, mirrors the strategy.py snapshot
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


# ── Recycle-rule code-hash pinning (admission-gate integrity) ──────────────


def recycle_rule_code_sha256(rule_name: str, rule_version) -> str:
    """Canonical (LF-normalized) sha256 of the module file implementing
    rule_name@version. Raises BasketProvenanceError if the source cannot be
    resolved."""
    cls = rule_class_for(rule_name, int(rule_version))
    src = inspect.getsourcefile(cls)
    if not src:
        raise BasketProvenanceError(
            f"cannot resolve source file for recycle_rule {rule_name}@{rule_version}"
        )
    return canonical_sha256(Path(src)).lower()


def load_recycle_rule_hashes(path: Path = RULE_CODE_HASHES_PATH) -> dict:
    """Return {`name@version`: sha256} from the sidecar. Empty dict if the file
    is absent or malformed — callers (the gate) soft-skip on an empty map so a
    missing sidecar never blocks admission; it only catches accidental drift."""
    path = Path(path)
    if not path.exists():
        return {}
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception:
        return {}
    hashes = data.get("hashes") if isinstance(data, dict) else None
    return {str(k): str(v) for k, v in hashes.items()} if isinstance(hashes, dict) else {}


# ── Input provenance (reproducibility identity) ────────────────────────────
# A basket run is reproducible iff its inputs are unchanged: directive + engine
# + leg data + leg/rule code + broker spec. Part A already folds the code hashes
# into the run manifest; these helpers add the engine version + per-leg DATA
# hash + per-leg BROKER-SPEC hash so a re-run can be compared to a prior run and
# declared reproducible-or-new-truth (the single-strategy `parquet_sha256` match
# -> restore / mismatch -> new truth model). The DATA hash is of the loaded leg
# DataFrame (the exact input that fed the engine, post-slice/derive), not the
# raw source parquet, so a different date range or derived column is correctly
# detected. The BROKER-SPEC hash pins the sizing substrate (usd_per_pu /
# lot_step / min_lot) that GP sizing reads per leg via load_broker_spec; the
# OctaFx spec YAML self-updates daily (skip-worktree'd, never pushed), so without
# this hash a past run's sizing tier is unrecoverable once the spec drifts.


def leg_data_sha256(df) -> str:
    """Deterministic content hash (schema + rows) of a leg's input DataFrame."""
    import pandas as pd  # local: keep module import light for non-data callers

    schema = repr([(str(c), str(df[c].dtype)) for c in df.columns]).encode("utf-8")
    rows = pd.util.hash_pandas_object(df, index=True).values.tobytes()
    return hashlib.sha256(schema + rows).hexdigest()


def effective_input_sha256(leg_data_hashes: dict | None) -> str | None:
    """Single deterministic DECISION witness for the engine-consumed leg DATA,
    folded SOLELY from the already-computed per-leg `leg_data_sha256` values.

    Introduces no new provenance: it is a canonical fold of the existing per-leg
    data hashes -- sorted by upper-cased symbol, rendered "SYM=hash" joined by
    ";", then sha256 of the UTF-8 string. Two runs share this scalar IFF every
    leg's loaded-data hash matches, so "did these two runs consume the same
    effective input data?" becomes a single ledger equality
    (`WHERE effective_input_sha256 = ?`) with no JSON parse, no manifest, no run
    folder.

    SCOPE (do NOT over-read): attests DATA identity ONLY. It does NOT attest
    rule-code identity (`strategy_code_sha256` is NULL for baskets) or sizing
    identity (`broker_spec_sha256`); those remain in runs/<id>/manifest.json. For
    a full "same effective input" determination, combine with directive_sha256 +
    engine_version + engine_abi. Returns None for an empty/None mapping (the
    ledger column stays NULL -- provenance never aborts a run).
    """
    if not leg_data_hashes:
        return None
    canonical = ";".join(
        f"{str(sym).upper()}={leg_data_hashes[sym]}"
        for sym in sorted(leg_data_hashes, key=lambda s: str(s).upper())
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def broker_spec_sha256(symbol: str) -> str | None:
    """Canonical (LF-normalized) sha256 of a leg symbol's resolved OctaFx broker
    spec — the exact YAML that GP sizing reads via load_broker_spec for
    usd_per_pu / lot_step / min_lot. Returns None if the spec is absent or
    unreadable (best-effort: provenance must never abort a run).

    Resolves the path through capital_broker_spec.broker_spec_path so the hashed
    file is byte-identical to the one sizing loaded (same SSOT, worktree-safe).
    LF-normalized so a CRLF re-save of the daily-updating YAML does not read as a
    spec change.
    """
    try:
        path = broker_spec_path(symbol)
        if not path.exists():
            return None
        return canonical_sha256(path).lower()
    except Exception:
        return None


# --- R9 cost-regime self-identification (2026-06-17) -------------------------
# The basket engine charges purely off the per-bar `spread` column. Two facts
# were previously unrecorded on a run: whether that column was POPULATED (data
# axis) and whether the COMPUTE charges it at all (engine axis). The old
# `execution_model_version` lived in the RESEARCH preamble (CSV comment="#")
# with 0 code readers, so a run never recorded which cost regime applied. These
# helpers measure the data axis and derive the engine axis honestly from the
# imported compute -- see memory engine_identity_is_compute_not_stamp.

def leg_spread_coverage_pct(df) -> float | None:
    """MEASURED % (0-100) of a leg's consumed bars carrying a populated spread
    (>0). None when the frame is empty or has no `spread` column -- the engine
    charges off this column, so coverage<100 flags bars whose spread cost the
    engine could NOT have applied (the XAU spread=0 acquisition gap that
    motivated R9). Best-effort: a measurement hiccup returns None, never aborts
    a run (mirrors the leg_data_sha256 / broker_spec_sha256 contract)."""
    try:
        if df is None:
            return None
        cols = getattr(df, "columns", None)
        # NB: `cols or []` would raise on a pandas Index (ambiguous truth value)
        # and the spread col would silently read as absent -> coverage NULL.
        if cols is None or "spread" not in list(cols):
            return None
        n = len(df)
        if n == 0:
            return None
        import pandas as pd  # local: keep module import light for non-data callers

        s = pd.to_numeric(df["spread"], errors="coerce")
        nonzero = int((s > 0).sum())
        return round(100.0 * nonzero / n, 6)
    except Exception:
        return None


def min_spread_coverage_pct(per_leg: dict | None) -> float | None:
    """Fold per-leg coverage to the BINDING (worst) leg: a basket is only as
    spread-faithful as its least-covered leg, so one spread=0 leg drags the
    whole row's self-reported coverage down. None when no leg reports coverage
    (the ledger column stays NULL -- provenance never aborts a run)."""
    if not per_leg:
        return None
    vals = [v for v in per_leg.values() if v is not None]
    return min(vals) if vals else None


# Map the imported basket compute ABI -> a human-readable cost regime. The ABI
# string is sourced from the basket_runner SSOT (override-inert), so this label
# is exactly as honest as engine_abi itself -- it is DERIVED from the compute,
# never an independently-set stamp that could drift (the failure mode
# engine_identity_is_compute_not_stamp warns about). An unmapped ABI returns a
# visible `unspecified:<abi>` rather than silently mislabeling.
#
# Label scheme: the UNCHARGED token deliberately avoids the substring "charged"
# (so a naive `LIKE '%charged%'` does NOT match "uncharged") -- the charged
# regime is cleanly isolated by `execution_cost_model LIKE 'spread_charged%'`.
_COST_MODEL_BY_ABI = {
    "engine_abi.v1_5_9": "spread_uncosted_roundtrip_v1_5_9",
    "engine_abi.v1_5_10": "spread_charged_diraware_v1_5_10",
}


def execution_cost_model(engine_abi: str | None) -> str | None:
    """Cost regime DERIVED from the imported compute ABI (basket_runner SSOT).
    None for a None/blank ABI; `unspecified:<abi>` for an unmapped one."""
    if not engine_abi:
        return None
    return _COST_MODEL_BY_ABI.get(str(engine_abi), f"unspecified:{engine_abi}")


def basket_input_provenance(leg_data: dict, engine_version: str) -> dict:
    """Build the reproducibility-identity block written into the run manifest:
    the engine version + a per-leg DATA hash + a per-leg BROKER-SPEC hash + a
    per-leg SPREAD-COVERAGE measurement.

    broker_spec_sha256 pins the sizing substrate (usd_per_pu / lot_step /
    min_lot) that GP sizing reads per leg; the OctaFx spec YAML self-updates
    daily, so without it a run's sizing tier is non-reproducible once the spec
    drifts. Additive: a None value means no spec file was on disk for that leg
    (that leg's sizing would itself have been rejected at run time).

    spread_coverage_pct is the per-leg MEASURED % of consumed bars with
    spread>0 (folded to the binding-leg minimum on the ledger row); it makes a
    run self-report whether its cost basis was actually present in the data."""
    legs = leg_data or {}
    return {
        "engine_version": str(engine_version),
        "leg_data_sha256": {
            str(sym): leg_data_sha256(df) for sym, df in legs.items()
        },
        "broker_spec_sha256": {
            str(sym): broker_spec_sha256(str(sym)) for sym in legs
        },
        "spread_coverage_pct": {
            str(sym): leg_spread_coverage_pct(df) for sym, df in legs.items()
        },
    }


def basket_run_identity(manifest: dict) -> dict:
    """Extract the full reproducibility identity from a basket run manifest:
    directive hash + engine + per-leg data hashes + leg/rule code hashes."""
    manifest = manifest or {}
    arts = manifest.get("artifacts") or {}
    inp = manifest.get("input_provenance") or {}
    return {
        "directive": manifest.get("strategy_hash"),
        "engine_version": manifest.get("engine_version") or inp.get("engine_version"),
        "leg_data_sha256": dict(inp.get("leg_data_sha256") or {}),
        "code": {k: v for k, v in arts.items() if k.startswith("basket_code/")},
    }


def compare_basket_runs(manifest_a: dict, manifest_b: dict) -> dict:
    """Diff two basket run manifests' reproducibility identities. Returns
    {"reproducible": bool, "changed": [<dimension>, ...]} — empty `changed`
    means a re-run would reproduce (identical inputs)."""
    a, b = basket_run_identity(manifest_a), basket_run_identity(manifest_b)
    changed: list[str] = []
    if a["directive"] != b["directive"]:
        changed.append("directive")
    if a["engine_version"] != b["engine_version"]:
        changed.append(f"engine_version ({a['engine_version']} -> {b['engine_version']})")
    for leg in sorted(set(a["leg_data_sha256"]) | set(b["leg_data_sha256"])):
        if a["leg_data_sha256"].get(leg) != b["leg_data_sha256"].get(leg):
            changed.append(f"leg_data:{leg}")
    for c in sorted(set(a["code"]) | set(b["code"])):
        if a["code"].get(c) != b["code"].get(c):
            changed.append(f"code:{c.removeprefix('basket_code/')}")
    return {"reproducible": not changed, "changed": changed}
