"""basket_data_loader.py — load real OHLC + factor data for basket legs.

Plan ref: H2_ENGINE_PROMOTION_PLAN.md Phase 5c.

Provides the runtime side of the basket pipeline: reads the per-symbol
multi-year 5m RESEARCH CSVs and joins the daily USD_SYNTH compression_5d
(forward-filled onto the 5m grid). Returned DataFrames are shaped for
direct consumption by `tools.basket_runner.BasketRunner`.

Conventions:
  * 5m CSVs live under DATA_ROOT/MASTER_DATA/<SYMBOL>_OCTAFX_MASTER/
    RESEARCH/<SYMBOL>_OCTAFX_5m_<YYYY>_RESEARCH.csv (header lines start
    with '#' and are skipped).
  * USD_SYNTH features live under DATA_ROOT/SYSTEM_FACTORS/USD_SYNTH/
    usd_synth_compression_d1.csv (column: compression_5d, daily).
  * The compression series is broadcast onto each leg's 5m index by
    forward-fill on the Date.

Returned dict[symbol] -> DataFrame columns:
    ['open', 'high', 'low', 'close', 'volume', 'spread', 'session',
     'commission_cash', 'slippage', 'compression_5d']
with a DatetimeIndex named 'time' and rows filtered to [start_date, end_date].
"""
from __future__ import annotations

from datetime import datetime
from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd

from config.path_authority import DATA_ROOT


__all__ = [
    "load_basket_leg_data",
    "load_compression_5d_factor",  # legacy alias; prefer load_usd_synth_factor
    "load_usd_synth_factor",
    "load_fx_correlation_factor",
    "load_cointegration_factor",
    "compute_spread_sma_cross_5m",
    "compute_intra_z",
    "clear_year_file_cache",
]


# ---------------------------------------------------------------------------
# FX_CORRELATION_MATRIX — leg-pair rolling Pearson factor (2026-05-17)
# ---------------------------------------------------------------------------
# Mirrors USD_SYNTH pattern: offline-generated SYSTEM_FACTORS file (one
# per timeframe), runtime-joined onto basket legs' 5m DataFrames via ffill.
#
# Generated by tools.factors.fx_correlation_matrix; columns named
# corr_<A>_<B> with leg symbols alphabetically sorted (deterministic).
# Only meaningful for 2-leg baskets (correlation between MORE than two
# pairs is a matrix, not a scalar — out of scope for this loader).

_FX_CORR_DIR = DATA_ROOT / "SYSTEM_FACTORS" / "FX_CORRELATION_MATRIX"
_FX_CORR_TIMEFRAMES = ("1h", "4h")


# ---------------------------------------------------------------------------
# USD_SYNTH factor catalog (S12 generalization, 2026-05-16)
# ---------------------------------------------------------------------------
# Maps column name -> source file under SYSTEM_FACTORS/USD_SYNTH/. Used by
# load_usd_synth_factor to resolve which file holds the requested column.
# Each file contains multiple period variants of the same metric family.

_USD_SYNTH_FACTOR_CATALOG = {
    # Compression family — path_length / net_displacement ratio.
    # LOW = trending; HIGH = chop. Use operator '>=' to gate "skip when below threshold".
    "compression_5d":  "usd_synth_compression_d1.csv",
    "compression_20d": "usd_synth_compression_d1.csv",
    # Volatility family — rolling realized vol (annualized).
    # HIGH = turbulent/trending; LOW = quiet/chop. Use operator '<=' to gate "skip when above threshold".
    "vol_5d":  "usd_synth_volatility_d1.csv",
    "vol_20d": "usd_synth_volatility_d1.csv",
    "vol_60d": "usd_synth_volatility_d1.csv",
    # Persistence family — rolling lag-1 autocorr of returns.
    # HIGH = trending (momentum); LOW/negative = mean-reverting. Use operator '<=' to gate "skip when above threshold".
    "autocorr_5d":  "usd_synth_persistence_d1.csv",
    "autocorr_20d": "usd_synth_persistence_d1.csv",
    "autocorr_60d": "usd_synth_persistence_d1.csv",
    # Stretch family — Z-score of returns vs rolling window.
    # HIGH abs = extreme move; LOW abs = normal. Z is signed; gating semantics are caller-specific.
    "stretch_z20": "usd_synth_stretch_d1.csv",
    "stretch_z60": "usd_synth_stretch_d1.csv",
}


# ---------------------------------------------------------------------------
# USD-conversion reference pairs (2026-05-15) — for H2_recycle@3 cross-pair
# PnL support. Each non-USD currency maps to a USD-anchored pair whose close
# is used to convert that currency to USD at runtime.
# ---------------------------------------------------------------------------

_CCY_TO_USD_PAIR = {
    "EUR": "EURUSD",
    "GBP": "GBPUSD",
    "AUD": "AUDUSD",
    "NZD": "NZDUSD",
    "JPY": "USDJPY",
    "CHF": "USDCHF",
    "CAD": "USDCAD",
}


def _split_pair_ccys(symbol: str) -> tuple[str, str]:
    """Return (base, quote) currency 3-letter codes."""
    if len(symbol) != 6:
        return ("", "")
    return symbol[:3].upper(), symbol[3:].upper()


def _required_ref_pairs(trade_symbols: list[str]) -> list[str]:
    """Return USD-anchored pairs needed as reference for currency conversion.

    Excludes trade symbols themselves (those would self-reference).
    """
    needed: set[str] = set()
    for sym in trade_symbols:
        base, quote = _split_pair_ccys(sym)
        for ccy in (base, quote):
            if ccy and ccy != "USD" and ccy in _CCY_TO_USD_PAIR:
                ref = _CCY_TO_USD_PAIR[ccy]
                if ref not in trade_symbols:
                    needed.add(ref)
    return sorted(needed)


# ---------------------------------------------------------------------------
# Phase 5b.4 — process-local year-file cache.
#
# Multi-window matrix runs (e.g., h2_parity_run.py --all) often re-load
# the same year-files across windows (window A 2016-2018 and window E
# 2017-2019 both need 2017 + 2018). Caching at the year-file granularity
# means each year-file is parsed once per process. Cleared by
# clear_year_file_cache() if needed (e.g., between independent matrix
# runs in the same long-running session).
#
# Sized for ~10 years × ~10 symbols = 100 unique frames; an OctaFx 5m
# year-file is ~5-7 MB CSV → ~50-100 MB pandas memory. 64-entry cap
# keeps total RAM under 6 GB even in the worst case.
# ---------------------------------------------------------------------------


@lru_cache(maxsize=64)
def _read_year_csv_cached(symbol: str, year: int, timeframe: str = "5m") -> pd.DataFrame:
    """Parse one year of OCTAFX bars for one symbol at the given timeframe.
    Cached process-locally (per (symbol, year, timeframe)).

    Returned DataFrame is the FULL year (no window filter applied) with
    `time` as a DatetimeIndex. Callers slice by date range themselves.
    Returns an EMPTY DataFrame if the year-file is missing — callers
    should treat that as a gap year.

    `timeframe` selects the OCTAFX CSV file (5m, 15m, 30m, 1h available
    per the 2026-05 ingest). Default "5m" preserves legacy behavior for
    all pre-2026-05-19 callers.
    """
    research_dir = DATA_ROOT / "MASTER_DATA" / f"{symbol}_OCTAFX_MASTER" / "RESEARCH"
    f = research_dir / f"{symbol}_OCTAFX_{timeframe}_{year}_RESEARCH.csv"
    if not f.is_file():
        return pd.DataFrame()  # caller treats as gap year
    df = pd.read_csv(f, comment="#", parse_dates=["time"])
    df = df.set_index("time").sort_index()
    return df


def clear_year_file_cache() -> None:
    """Drop all cached year-files. Call between independent multi-window
    runs in the same process if memory matters."""
    _read_year_csv_cached.cache_clear()


# ---------------------------------------------------------------------------
# Factor loader
# ---------------------------------------------------------------------------


def load_usd_synth_factor(factor_column: str, start_date: str, end_date: str) -> pd.Series:
    """Read any USD_SYNTH daily factor series filtered to the window.

    Generalization of the legacy load_compression_5d_factor (S12 patch,
    2026-05-16). Resolves the column name to a source file via
    _USD_SYNTH_FACTOR_CATALOG, then reads/shifts/window-filters identically
    to the compression path.

    Supported `factor_column` values (catalog keys):
      compression_5d, compression_20d              (compression family)
      vol_5d, vol_20d, vol_60d                     (volatility family)
      autocorr_5d, autocorr_20d, autocorr_60d      (persistence family)
      stretch_z20, stretch_z60                     (stretch family)

    Returns a Series indexed by daily DatetimeIndex with name=factor_column.
    NaN rows (pre-warm-up) retained — caller handles.

    Lookahead-safe: applies `shift(1)` so the value at date D is the value
    that was originally for date D-1. Same convention as before; see the
    Phase 5d.1 parity finding for the rationale on the shift discipline.
    """
    if factor_column not in _USD_SYNTH_FACTOR_CATALOG:
        raise ValueError(
            f"Unknown USD_SYNTH factor column: {factor_column!r}. "
            f"Known columns: {sorted(_USD_SYNTH_FACTOR_CATALOG.keys())}"
        )
    filename = _USD_SYNTH_FACTOR_CATALOG[factor_column]
    path = DATA_ROOT / "SYSTEM_FACTORS" / "USD_SYNTH" / filename
    if not path.is_file():
        raise FileNotFoundError(
            f"USD_SYNTH factor file missing at {path}. "
            "Confirm DATA_INGRESS has populated SYSTEM_FACTORS/USD_SYNTH/."
        )
    df = pd.read_csv(path, parse_dates=["Date"])
    df = df.set_index("Date").sort_index()
    if factor_column not in df.columns:
        raise ValueError(
            f"{factor_column!r} column missing in {path}; found {list(df.columns)}"
        )
    # Lookahead-safe shift BEFORE window filter (so first-day-of-window has
    # prior-day's value, not NaN from being on the window boundary).
    series = df[factor_column].shift(1)
    start_ts = pd.Timestamp(start_date)
    end_ts = pd.Timestamp(end_date)
    series = series[(series.index >= start_ts) & (series.index <= end_ts)]
    series.name = factor_column
    return series


def load_fx_correlation_factor(
    sym_a: str,
    sym_b: str,
    timeframe: str,
    start_date: str,
    end_date: str,
) -> pd.Series:
    """Load the rolling Pearson correlation series for one leg-pair at one timeframe.

    Looks up the alphabetically-sorted pair column from
    ``SYSTEM_FACTORS/FX_CORRELATION_MATRIX/fx_correlation_<tf>.parquet``
    and returns the series filtered to [start_date, end_date].

    Args:
        sym_a, sym_b: leg symbols (order doesn't matter; alphabetized internally).
        timeframe:    '1h' or '4h' — must match a generated matrix file.
        start_date, end_date: 'YYYY-MM-DD' window bounds.

    Returns:
        pd.Series indexed by the source timeframe's bar timestamps, with
        values in [-1.0, 1.0] (or NaN during warmup). Name field set to
        ``fx_corr_<tf>`` for downstream joining.

    Raises:
        FileNotFoundError: matrix file missing for the requested timeframe.
        KeyError: pair-pair column not present (likely symbol not in
                  FX_UNIVERSE at generation time).
    """
    tf = timeframe.lower()
    if tf not in _FX_CORR_TIMEFRAMES:
        raise ValueError(
            f"load_fx_correlation_factor: timeframe {timeframe!r} not in "
            f"{_FX_CORR_TIMEFRAMES}. Add it to tools.factors.fx_correlation_matrix "
            f"and regenerate."
        )
    path = _FX_CORR_DIR / f"fx_correlation_{tf}.parquet"
    if not path.is_file():
        raise FileNotFoundError(
            f"FX_CORRELATION_MATRIX file missing at {path}. "
            f"Run: python -m tools.factors.fx_correlation_matrix"
        )
    a, b = sorted([sym_a.upper(), sym_b.upper()])
    col = f"corr_{a}_{b}"
    df = pd.read_parquet(path, columns=[col])
    if col not in df.columns:
        raise KeyError(
            f"FX_CORRELATION_MATRIX: pair {col!r} not present in {path}. "
            f"Confirm both symbols are in tools.factors.fx_correlation_matrix.FX_UNIVERSE "
            f"and regenerate."
        )
    s = df[col]
    s = s.loc[(s.index >= pd.Timestamp(start_date)) & (s.index <= pd.Timestamp(end_date))]
    s.name = f"fx_corr_{tf}"
    return s


def load_compression_5d_factor(start_date: str, end_date: str) -> pd.Series:
    """Legacy alias for load_usd_synth_factor('compression_5d', ...).

    Preserved for backward compatibility with any caller importing this
    function by name. New code should use load_usd_synth_factor directly.
    """
    return load_usd_synth_factor("compression_5d", start_date, end_date)


# ---------------------------------------------------------------------------
# Per-symbol 5m loader (multi-year concat)
# ---------------------------------------------------------------------------


def _load_symbol_5m(symbol: str, start_date: str, end_date: str,
                    timeframe: str = "5m") -> pd.DataFrame:
    """Read every RESEARCH year-file for symbol covering the window at the
    given timeframe, concat (via cache), filter to [start, end].

    Function name retains _5m suffix for callsite-compat; `timeframe` param
    selects the actual file series (5m/15m/30m/1h per DATA_INGRESS ingest).
    Year-files are cached process-locally via _read_year_csv_cached so
    cross-window matrix runs reuse parsed frames instead of re-parsing.
    """
    research_dir = DATA_ROOT / "MASTER_DATA" / f"{symbol}_OCTAFX_MASTER" / "RESEARCH"
    if not research_dir.is_dir():
        raise FileNotFoundError(
            f"RESEARCH dir missing for {symbol} at {research_dir}. "
            f"Confirm DATA_INGRESS has produced the OctaFx {timeframe} "
            f"series for this symbol."
        )
    start_year = int(start_date[:4])
    end_year = int(end_date[:4])
    pieces: list[pd.DataFrame] = []
    for year in range(start_year, end_year + 1):
        piece = _read_year_csv_cached(symbol, year, timeframe)
        if piece.empty:
            continue  # gap year — not necessarily fatal; window filter handles edges
        pieces.append(piece)
    if not pieces:
        raise FileNotFoundError(
            f"No {timeframe} RESEARCH files found for {symbol} in window "
            f"{start_year}-{end_year} under {research_dir}."
        )
    df = pd.concat(pieces).sort_index()
    start_ts = pd.Timestamp(start_date)
    end_ts = pd.Timestamp(end_date)
    df = df[(df.index >= start_ts) & (df.index <= end_ts)]
    if df.empty:
        raise ValueError(
            f"After window filter {start_date}..{end_date}, no {timeframe} bars "
            f"remain for {symbol}. Year files were present but bars fall outside "
            f"the window."
        )
    return df


# ---------------------------------------------------------------------------
# Compose: per-symbol DF + compression_5d column
# ---------------------------------------------------------------------------


def _join_factor_onto_5m(df_5m: pd.DataFrame, factor: pd.Series) -> pd.DataFrame:
    """Forward-fill the daily factor onto the 5m DatetimeIndex of df_5m.

    The factor's daily date stamp aligns to the START of each UTC day, so
    every 5m bar at-or-after that day's 00:00 inherits the day's value
    until the next daily print. NaN rows (pre-warm-up) propagate.

    The joined column name is taken from `factor.name` so generalized
    factors (vol_5d, autocorr_5d, etc.) land under their own column.
    """
    out = df_5m.copy()
    col_name = factor.name or "compression_5d"
    # Reindex factor onto 5m index via forward-fill.
    out[col_name] = factor.reindex(out.index, method="ffill")
    return out


_BAR_SECONDS = {"5m": 300, "15m": 900, "30m": 1800, "1h": 3600,
                "4h": 14400, "1d": 86400}


# Macro-direction filter defaults (2026-05-19). Used only when
# macro_direction_timeframe is set on load_basket_leg_data. The z/sma
# windows are macro-meaningful at the daily TF (3 months / 1 week) rather
# than the calendar-equivalent ~50h rule used for the entry timeframe.
_MACRO_Z_WINDOW = 60
_MACRO_SMA_WINDOW = 5
_MACRO_WARMUP_DAYS_DEFAULT = 120


def load_basket_leg_data(
    symbols: list[str],
    start_date: str,
    end_date: str,
    factor_column: str = "compression_5d",
    timeframe: str = "5m",
    macro_direction_timeframe: str | None = None,
    macro_warmup_days: int = _MACRO_WARMUP_DAYS_DEFAULT,
    macro_z_window: int = _MACRO_Z_WINDOW,
    macro_sma_window: int = _MACRO_SMA_WINDOW,
    macro_correlation_window: int | None = None,
    macro_correlation_threshold: float = -0.5,
    regime_gate_lookback_bars: int | None = None,
    regime_gate_flip_threshold: float | None = None,
) -> dict[str, pd.DataFrame]:
    """Load per-symbol OHLC + a USD_SYNTH regime factor for a basket.

    Args:
        symbols:        list of leg symbols, e.g. ['EURUSD', 'USDJPY']
        start_date:     'YYYY-MM-DD'
        end_date:       'YYYY-MM-DD'
        factor_column:  USD_SYNTH factor column to join (default
                        'compression_5d' for backward compat). Any column
                        in _USD_SYNTH_FACTOR_CATALOG is accepted: vol_5d,
                        autocorr_5d, stretch_z20, etc. The column lands
                        on every leg's DataFrame under its own name.

    Returns:
        dict mapping symbol -> DataFrame indexed by 'time' with columns:
            open, high, low, close, volume, spread, session,
            commission_cash, slippage, <factor_column>, and (for cross-pair
            H2_recycle@3 support) usd_ref_<PAIR>_close columns for each
            USD-anchored reference pair needed to convert any non-USD
            currency in the basket to USD.

    S12 patch (2026-05-16): factor_column generalized from hardcoded
    compression_5d. Backward-compatible default preserves all existing
    callers and directive YAMLs unchanged.

    H2_recycle@3 cross-pair support (2026-05-15): when the basket includes
    pairs whose base or quote currency is NOT USD (e.g. AUDJPY, GBPAUD),
    additional USD-anchored reference pair closes are auto-loaded and
    joined as `usd_ref_<PAIR>_close` columns on EVERY leg's DataFrame.
    For example, an AUDJPY + GBPAUD basket auto-loads USDJPY, AUDUSD,
    GBPUSD and joins their closes onto both legs' DataFrames so the v3
    rule can compute USD-denominated PnL via the generalized currency
    conversion logic.
    """
    if not symbols:
        raise ValueError("load_basket_leg_data: symbols must be non-empty.")
    # Validate dates are parseable
    datetime.strptime(start_date, "%Y-%m-%d")
    datetime.strptime(end_date, "%Y-%m-%d")
    factor = load_usd_synth_factor(factor_column, start_date, end_date)

    # Identify USD-anchored reference pairs needed for currency conversion
    ref_pairs = _required_ref_pairs(list(symbols))
    ref_closes: dict[str, pd.Series] = {}
    for ref_pair in ref_pairs:
        try:
            ref_df = _load_symbol_5m(ref_pair, start_date, end_date,
                                      timeframe=timeframe)
            ref_closes[ref_pair] = ref_df["close"]
        except (FileNotFoundError, ValueError) as exc:
            # Non-fatal — the v3 rule's _build_ref_closes will degrade gracefully
            print(f"[BASKET_DATA] WARN: reference pair {ref_pair!r} unavailable ({exc}); "
                  f"cross-pair PnL may not work for legs requiring {ref_pair!r}.")

    # FX leg-pair correlation factor (2026-05-17) — auto-joined for 2-leg
    # baskets only. Adds `fx_corr_1h` and `fx_corr_4h` columns to every
    # leg's df (both legs see the same correlation series — it's a pair
    # property, not a per-leg property). Missing matrix file is non-fatal:
    # legacy 2-leg directives that don't use the correlation gate continue
    # to work; the new columns simply aren't present.
    fx_corr_series: dict[str, pd.Series] = {}
    if len(symbols) == 2:
        for tf in _FX_CORR_TIMEFRAMES:
            try:
                fx_corr_series[tf] = load_fx_correlation_factor(
                    symbols[0], symbols[1], tf, start_date, end_date,
                )
            except (FileNotFoundError, KeyError) as exc:
                print(
                    f"[BASKET_DATA] WARN: fx_correlation factor {tf!r} unavailable "
                    f"for ({symbols[0]}, {symbols[1]}) ({exc}); correlation gate "
                    f"in H2_recycle@5 will not fire if configured."
                )

    out: dict[str, pd.DataFrame] = {}
    for sym in symbols:
        df_5m = _load_symbol_5m(sym, start_date, end_date, timeframe=timeframe)
        df_5m = _join_factor_onto_5m(df_5m, factor)
        # Join USD reference rates as columns
        for ref_pair, ref_series in ref_closes.items():
            df_5m[f"usd_ref_{ref_pair}_close"] = ref_series.reindex(
                df_5m.index, method="ffill"
            )
        # Join leg-pair FX correlation series (ffill onto 5m bar index).
        for tf, corr_series in fx_corr_series.items():
            df_5m[f"fx_corr_{tf}"] = corr_series.reindex(df_5m.index, method="ffill")
        out[sym] = df_5m

    # spread_sma_cross signal join (2026-05-18) — auto-joined for 2-leg
    # baskets. Adds `cross_event` and `cross_side` columns to every leg's
    # df (both legs see the same signal series — it's a pair-property).
    # Used by H3_spread@1 rule + SpreadCrossLegStrategy. Failure is
    # non-fatal: directives that don't use the signal continue to work.
    if len(symbols) == 2:
        try:
            # Calendar-time-equivalent params: keep z-normalization lookback
            # ≈ 50h and SMA smoothing ≈ 75min regardless of bar size. At 5m
            # this preserves the historical defaults (z=600, sma=15).
            bar_sec = _BAR_SECONDS.get(timeframe, 300)
            z_window_tf = max(20, int(50 * 3600 / bar_sec))      # ~50h
            sma_window_tf = max(2, int(75 * 60 / bar_sec))       # ~75min
            cross_df = compute_spread_sma_cross_5m(
                out[symbols[0]]["close"],
                out[symbols[1]]["close"],
                z_window=z_window_tf,
                sma_window=sma_window_tf,
            )
            for sym in symbols:
                out[sym]["cross_event"] = cross_df["cross_event"].reindex(
                    out[sym].index, method="ffill", fill_value=0
                ).astype(int)
                out[sym]["cross_side"] = cross_df["cross_side"].reindex(
                    out[sym].index, method="ffill", fill_value=0
                ).astype(int)
                # Unsmoothed exit signal (added 2026-05-22 for S16 z=0 exit
                # probe). Default behavior unchanged — recycle rules only
                # read this column if they set `reverse_cross_column:
                # cross_side_raw` in their directive params.
                out[sym]["cross_side_raw"] = cross_df["cross_side_raw"].reindex(
                    out[sym].index, method="ffill", fill_value=0
                ).astype(int)
                # Smoothed diff = SMA(z_a) - SMA(z_b) (added 2026-05-22 for
                # the H3_spread@3 extreme-z exit). Read by the @3 rule
                # when extreme_z_threshold is set; @2 and earlier ignore it.
                # Float dtype (the smoothed diff is a continuous signal,
                # not a categorical side). fill_value=0.0 keeps warmup
                # bars within the extreme-z deadband (no false trigger).
                out[sym]["diff"] = cross_df["diff"].reindex(
                    out[sym].index, method="ffill", fill_value=0.0
                ).astype(float)

            # Regime-gate signal (added 2026-05-23 for the
            # h3_spread_window_c_regime_detector charter): rolling count of
            # cross_side sign changes over a configurable lookback window.
            # Default regime_gate_lookback_bars=None preserves legacy
            # behavior — no column is added, no schema change for callers
            # that do not opt in. When set, the h3_spread_v3 rule reads
            # this column to gate cycle_init and pyramid_add when count
            # exceeds regime_gate_flip_threshold (charter H1 revised).
            #
            # Cold-start contract: the first regime_gate_lookback_bars-1
            # bars are NaN (min_periods=full window). The consuming rule
            # treats NaN as "gate inactive" so the strategy behaves as
            # baseline until the lookback is filled.
            if regime_gate_lookback_bars is not None:
                lookback_n = int(regime_gate_lookback_bars)
                for sym in symbols:
                    cs = out[sym]["cross_side"]
                    # fillna(0): the shift-by-1 produces NaN at position 0;
                    # in pandas, (NaN != 0) evaluates to True, which would
                    # phantom-count the first bar as a flip. Treating NaN as
                    # 0 (the same value the warmup bars carry) suppresses
                    # that without affecting any real flip detection.
                    prev_cs = cs.shift(1).fillna(0)
                    is_flip = (
                        (cs != prev_cs) & (cs != 0) & (prev_cs != 0)
                    ).astype(int)
                    out[sym]["flips_in_lookback"] = is_flip.rolling(
                        lookback_n, min_periods=lookback_n
                    ).sum()

                # Cycle-init suppression: zero out cross_event on bars where
                # the gate trips. Same precedent as the macro-direction
                # entry-only filter (block above) — cross_side (the exit
                # signal) is intentionally left untouched so cycles that
                # opened pre-trip can exit normally on a subsequent flip.
                # Pyramid suppression on already-open cycles is the v3
                # rule's responsibility (it reads flips_in_lookback +
                # regime_gate_flip_threshold from its own params).
                #
                # NaN flips (cold-start) compare False against any finite
                # threshold, so the gate is naturally inactive until the
                # lookback fills (= the charter's cold-start contract).
                if regime_gate_flip_threshold is not None:
                    threshold = float(regime_gate_flip_threshold)
                    for sym in symbols:
                        ce = out[sym]["cross_event"]
                        flips = out[sym]["flips_in_lookback"]
                        tripped = flips > threshold  # NaN > T -> False
                        out[sym]["cross_event"] = ce.where(
                            ~tripped, 0
                        ).astype(int)

            # Macro-direction filter (2026-05-19). When configured, compute
            # the SAME SMA-of-z cross signal on a HIGHER native broker
            # timeframe (e.g. 1d, 4h), shift by 1 macro bar to prevent
            # look-ahead leakage from the macro bar's own close into 5m
            # bars on the same day, and forward-fill onto the entry-TF
            # grid as `htf_direction`. Then AND-filter the entry-TF
            # `cross_event` column so only macro-aligned crosses fire
            # entries. cross_side (used for reverse-cross EXITS) is left
            # untouched — per design, cycles still exit on entry-TF flips.
            if macro_direction_timeframe is not None:
                # Extend the start backwards to give the macro indicator
                # full warmup. Each leg is reloaded at the macro TF over
                # the extended range; the result is forward-filled onto
                # the entry-TF grid (which is bounded by the ORIGINAL
                # start_date).
                ext_start = (
                    pd.Timestamp(start_date)
                    - pd.Timedelta(days=int(macro_warmup_days))
                ).strftime("%Y-%m-%d")
                macro_closes: dict[str, pd.Series] = {}
                for sym in symbols:
                    sym_df_macro = _load_symbol_5m(
                        sym, ext_start, end_date,
                        timeframe=macro_direction_timeframe,
                    )
                    macro_closes[sym] = sym_df_macro["close"]
                macro_cross = compute_spread_sma_cross_5m(
                    macro_closes[symbols[0]],
                    macro_closes[symbols[1]],
                    z_window=macro_z_window,
                    sma_window=macro_sma_window,
                )
                # 1-bar shift: a 5m bar at time T should see the macro
                # cross_side from the PREVIOUS macro close, not the
                # macro bar it's currently inside. Otherwise we leak
                # information from the current macro bar's close back
                # into intra-bar 5m decisions.
                macro_side_shifted = macro_cross["cross_side"].shift(1)
                for sym in symbols:
                    htf_direction = macro_side_shifted.reindex(
                        out[sym].index, method="ffill", fill_value=0
                    ).astype(int)
                    out[sym]["htf_direction"] = htf_direction
                    # Entry-only filter: zero out cross_event where it
                    # doesn't match the macro direction. cross_side
                    # (exit signal) intentionally left untouched.
                    cross_event = out[sym]["cross_event"]
                    aligned = (cross_event != 0) & (cross_event == htf_direction)
                    out[sym]["cross_event"] = cross_event.where(aligned, 0).astype(int)

            # Correlation-health filter (2026-05-19, post-Window-C diagnosis).
            # The H3_spread basket's PnL math (leg_a × Δa − leg_b × Δb)
            # only IS a USD-direction trade when corr(Δa, Δb) is strongly
            # negative. When correlation breaks (Δa and Δb decouple), the
            # basket becomes two independent noise streams and the cycle PnL
            # distribution flattens to coin-flip (cycle PF -> ~1.0 or below).
            # Verified empirically: Window C had 25% of days with broken
            # correlation (vs 5% on Window A) and lost -130% Net.
            #
            # Filter: compute rolling correlation of daily log-returns over
            # macro_correlation_window days, shift by 1 day (look-ahead
            # protection), forward-fill onto entry-TF grid as
            # htf_correlation, and AND-filter cross_event so it only fires
            # when correlation is at-or-below macro_correlation_threshold
            # (strongly inverse). cross_side (exit signal) intentionally
            # left untouched — symmetric with the macro-direction filter
            # design.
            #
            # Default macro_correlation_window=None preserves legacy
            # behavior. Typical config: macro_correlation_window=20,
            # macro_correlation_threshold=-0.5.
            if macro_correlation_window is not None:
                # Load daily closes (re-use the macro extended window if
                # the macro-direction filter ran; otherwise compute a
                # similar extended window).
                ext_start_corr = (
                    pd.Timestamp(start_date)
                    - pd.Timedelta(days=max(int(macro_warmup_days),
                                            int(macro_correlation_window) + 30))
                ).strftime("%Y-%m-%d")
                daily_closes: dict[str, pd.Series] = {}
                for sym in symbols:
                    sym_df_daily = _load_symbol_5m(
                        sym, ext_start_corr, end_date, timeframe="1d",
                    )
                    daily_closes[sym] = sym_df_daily["close"]
                aligned_d = pd.concat(
                    [daily_closes[symbols[0]].rename("a"),
                     daily_closes[symbols[1]].rename("b")],
                    axis=1,
                ).dropna()
                ret_d = np.log(aligned_d).diff()
                roll_corr = (
                    ret_d["a"]
                    .rolling(int(macro_correlation_window))
                    .corr(ret_d["b"])
                )
                # 1-bar shift: a 5m bar at time T uses correlation from
                # the PREVIOUS daily close, not today's (which wasn't
                # known until end-of-day).
                roll_corr_shifted = roll_corr.shift(1)
                for sym in symbols:
                    corr_aligned = roll_corr_shifted.reindex(
                        out[sym].index, method="ffill",
                    )
                    # During warmup `corr` is NaN; treat as "no signal" =
                    # not-strongly-inverse = filter rejects entries.
                    out[sym]["htf_correlation"] = corr_aligned
                    # Entry-only gate: cross_event must be nonzero AND
                    # correlation must be at-or-below threshold (strongly
                    # inverse). NaN comparisons return False → reject.
                    cross_event = out[sym]["cross_event"]
                    corr_ok = (corr_aligned <= macro_correlation_threshold)
                    keep = (cross_event != 0) & corr_ok.fillna(False)
                    out[sym]["cross_event"] = cross_event.where(keep, 0).astype(int)

        except Exception as exc:
            print(
                f"[BASKET_DATA] WARN: spread_sma_cross unavailable for "
                f"({symbols[0]}, {symbols[1]}) ({exc}); H3_spread rule will "
                f"not fire entries if configured."
            )

        # Macro-filter warmup assertion (lives OUTSIDE the try block above
        # so it isn't swallowed by the cross-signal try/except). If the
        # macro filter was requested but the htf_direction column is all-
        # zero during the first 24h of the test window, the macro
        # indicator's warmup hasn't completed → fail fast instead of
        # silently running with all entries blocked.
        if macro_direction_timeframe is not None and len(symbols) == 2:
            # Sample by BAR INDEX, not calendar time — start_date may fall on
            # a market-closed day (weekend / holiday), in which case the
            # first actual bar is later. We check that within the first
            # ~24 trading hours of bars the macro signal has populated to
            # something other than zero.
            bars_per_day = max(1, int(86400 / _BAR_SECONDS.get(timeframe, 300)))
            for sym in symbols:
                if "htf_direction" not in out[sym].columns:
                    raise ValueError(
                        f"macro_direction_filter: htf_direction column "
                        f"missing for {sym}. Upstream macro-cross computation "
                        f"likely failed silently — check [BASKET_DATA] WARN "
                        f"output above."
                    )
                first_day = out[sym]["htf_direction"].iloc[:bars_per_day]
                if len(first_day) > 0 and (first_day == 0).all():
                    raise ValueError(
                        f"macro_direction_filter: htf_direction is all-zero "
                        f"for {sym} during the first 24h of [{start_date}, "
                        f"{end_date}]. macro_warmup_days={macro_warmup_days} "
                        f"may be insufficient for macro_direction_timeframe="
                        f"{macro_direction_timeframe!r} (need ~"
                        f"{macro_z_window + macro_sma_window} bars at "
                        f"that TF before start_date)."
                    )

    # Cointegration factor auto-join was retired 2026-05-21 with the COINTREV
    # v1 strategy chain. The screener infrastructure (load_cointegration_factor
    # below, indicators/stats/cointegration_state, tools/cointegration_*) is
    # retained. Any future β-weighted cointegration strategy should re-add a
    # deliberate auto-join here, with explicit opt-in via directive params.

    return out


def load_cointegration_factor(
    sym_a: str,
    sym_b: str,
    *,
    matrix_hash: str | None = None,
    start_date: datetime | None = None,
    end_date: datetime | None = None,
) -> pd.DataFrame:
    """Load per-bar cointegration features for one pair-pair.

    Reads the historical cointegration matrix (built by
    tools/cointegration_history_matrix.py) and extracts the per-date
    feature rows for the unordered (sym_a, sym_b) pair. Pair lookup is
    alphabetically canonicalized so caller order doesn't matter.

    Returns a DataFrame indexed by date with columns:
        beta, spread_mean, spread_std, daily_z,
        adf_p_252, adf_p_504, qualified

    matrix_hash:
        None  → reads LATEST pointer (most recent matrix build)
        "..." → pins to a specific historical build for reproducibility

    Used by load_basket_leg_data's auto-join block to inject cointegration
    columns onto every 2-leg basket. Raises FileNotFoundError if no matrix
    has been built, KeyError if the pair-pair isn't in the matrix universe.
    """
    # Local import keeps top-of-module light + avoids ordering concerns.
    from indicators.stats.cointegration_state import (
        FEATURE_COLUMNS,
        load_history_matrix,
    )
    matrix = load_history_matrix(matrix_hash)
    a, b = sorted([sym_a, sym_b])
    sub = matrix.loc[(matrix["pair_a"] == a) & (matrix["pair_b"] == b)]
    if sub.empty:
        raise KeyError(
            f"cointegration matrix has no pair ({a}, {b}). "
            f"Universe size: {matrix.groupby(['pair_a','pair_b']).ngroups} pair-pairs."
        )
    sub = sub.set_index("date")[FEATURE_COLUMNS].sort_index()
    if start_date is not None:
        sub = sub.loc[sub.index >= pd.Timestamp(start_date)]
    if end_date is not None:
        sub = sub.loc[sub.index <= pd.Timestamp(end_date)]
    return sub


def compute_intra_z(
    close_a: pd.Series,
    close_b: pd.Series,
    beta_series: pd.Series,
    *,
    window: int = 100,
) -> pd.Series:
    """Compute rolling 15m z-score of spread = close_b - beta·close_a.

    `beta_series` is the daily β forward-filled onto the 15m index — typically
    pulled from the cointegration matrix via load_cointegration_factor and
    reindexed onto the leg df's intraday timestamps.

    `window` defaults to 100 bars (~25h on 15m = one full FX session cycle).
    Per operator review 2026-05-20, this is the operational sweet spot —
    short enough to respond within hours of a fresh dislocation, long enough
    that single-session noise doesn't dominate. The daily-cointegration
    qualification (joined separately) carries the structural-memory job, so
    the intraday window doesn't need to recreate it.

    Returns a Series aligned to `close_a`'s index. NaN during warmup
    (first ~window/2 bars).
    """
    spread = close_b - beta_series * close_a
    sp_mean = spread.rolling(window, min_periods=max(2, window // 2)).mean()
    sp_std = spread.rolling(window, min_periods=max(2, window // 2)).std(ddof=0)
    return (spread - sp_mean) / sp_std


def compute_spread_sma_cross_5m(
    close_a: pd.Series,
    close_b: pd.Series,
    z_window: int = 600,
    sma_window: int = 15,
) -> pd.DataFrame:
    """Compute the SMA-crossover signal on z-normalized 5m closes of two
    pairs. Thin wrapper around indicators.stats.spread_sma_cross — keeps
    the indicator pure and centralizes the basket-loader-side parameter
    defaults (which differ from the indicator's 15m-oriented defaults).

    The output is aligned to whichever close index is the inner-join of
    the two inputs (caller passes already-aligned series).
    """
    # Local import to avoid top-of-module circular ordering concerns when
    # indicators/ imports any tools/ helper in the future.
    from indicators.stats.spread_sma_cross import spread_sma_cross
    aligned = pd.concat([close_a, close_b], axis=1).dropna()
    if aligned.empty:
        # Empty input — return empty same-schema frame so callers can join safely.
        return pd.DataFrame(
            columns=["z_a", "z_b", "sma_z_a", "sma_z_b", "diff",
                     "cross_side", "cross_event"],
            index=close_a.index,
        )
    return spread_sma_cross(
        aligned.iloc[:, 0],
        aligned.iloc[:, 1],
        z_window=z_window,
        sma_window=sma_window,
    )
