"""
format_excel_artifact.py — Unified Excel Formatter & Rounding Governance

Applies strict styling and number formatting to Excel artifacts.
Logic is presentation-layer only. No data mutation.

Usage:
    python tools/format_excel_artifact.py --file <path> --profile <strategy|portfolio>
"""

import argparse
import sys
import openpyxl
from pathlib import Path
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

# ==========================================================
# CONSTANTS
# ==========================================================

# Styling
HEADER_FILL_COLOR = "4472C4"  # Lighter Blue (SOP Governance)
HEADER_FONT_COLOR = "FFFFFF"
ALT_ROW_FILL_COLOR = "DCE6F1"

# Number Formats
FMT_CURRENCY = "#,##0.00"   # USD (2 decimals, comma)
FMT_PERCENT = "0.00%"       # Percent ratio (0.1234 -> 12.34%)
FMT_PCT_RAW = "0.00\"%\""   # Raw percent number (65.24 -> 65.24%)
FMT_FLOAT = "0.00"          # Ratio/Float (2 decimals: 1.23)
FMT_INT = "0"               # Integer

# Header display
HEADER_ROW_HEIGHT = 36       # Tall enough for 2-line wrapped headers
MAX_HEADER_LINE_LEN = 14     # Wrap headers wider than this

# Column Rules (Column Name -> Format)
# Keys should be lower-case for matching
FORMAT_MAP = {
    # Rank (auto-generated by formatter)
    "rank": FMT_INT,

    # Trades List Headers (Human Readable)
    "pnl (usd)": FMT_CURRENCY,
    "entry price": FMT_FLOAT,
    "exit price": FMT_FLOAT,
    "bars held": FMT_INT,
    
    # Summary Metrics (Human Readable - Lowercase)
    "net profit (usd)": FMT_CURRENCY,
    "gross profit (usd)": FMT_CURRENCY,
    "gross loss (usd)": FMT_CURRENCY,
    "starting capital": FMT_CURRENCY,
    "max drawdown (usd)": FMT_CURRENCY,
    "largest win (usd)": FMT_CURRENCY,
    "largest loss (usd)": FMT_CURRENCY,
    "expectancy (usd)": FMT_CURRENCY,
    "avg trade (usd)": FMT_CURRENCY,
    "avg win (usd)": FMT_CURRENCY,
    "avg loss (usd)": FMT_CURRENCY,
    
    "max drawdown (%)": FMT_PERCENT,
    "% profitable": FMT_PERCENT,
    "% of gross profit (top trades)": FMT_PERCENT,
    "worst 5 trades loss %": FMT_PERCENT,
    "return on capital": FMT_PERCENT,
    "% time in market": FMT_PERCENT,
    
    "profit factor": FMT_FLOAT,
    "sharpe ratio": FMT_FLOAT,
    "sortino ratio": FMT_FLOAT,
    "k-ratio": FMT_FLOAT,
    "sqn (system quality number)": FMT_FLOAT,
    "return / drawdown ratio": FMT_FLOAT,
    "return retracement ratio": FMT_FLOAT,
    "avg mfe (r)": FMT_FLOAT,
    "avg mae (r)": FMT_FLOAT,
    "edge ratio (mfe / mae)": FMT_FLOAT,
    "win/loss ratio": FMT_FLOAT,
    "avg bars in winning trades": FMT_FLOAT,
    "avg bars in losing trades": FMT_FLOAT,
    "avg bars per trade": FMT_FLOAT,
    
    # Strategy Master Filter Keys (Stage-3)
    "total_net_profit": FMT_CURRENCY,
    "expectancy": FMT_CURRENCY,
    "sharpe_ratio": FMT_FLOAT,
    "return_dd_ratio": FMT_FLOAT,
    "worst_5_loss_pct": FMT_PERCENT,
    "max_drawdown": FMT_CURRENCY, # "max_dd_usd" is legacy
    "longest_loss_streak": FMT_INT,
    "pct_time_in_market": FMT_PERCENT,
    "avg_bars_in_trade": FMT_FLOAT,
    "net_profit_high_vol": FMT_CURRENCY,
    "net_profit_normal_vol": FMT_CURRENCY,
    "net_profit_low_vol": FMT_CURRENCY,
    
    # Legacy / Internal Keys (Keep for compatibility)
    "net_pnl_usd": FMT_CURRENCY,
    "net_profit": FMT_CURRENCY, 
    "gross_profit": FMT_CURRENCY,
    "gross_loss": FMT_CURRENCY,
    "max_dd_usd": FMT_CURRENCY,
    "max_dd_pct": FMT_PERCENT,
    "win_rate": FMT_PCT_RAW,
    "sharpe": FMT_FLOAT,
    "profit_factor": FMT_FLOAT,
    "total_trades": FMT_INT,
    "winning_trades": FMT_INT,
    "losing_trades": FMT_INT,
    "max_consec_wins": FMT_INT,
    "max_consec_losses": FMT_INT,
    "consecutive_wins": FMT_INT,
    "consecutive_losses": FMT_INT,

    # Profile Selector (Step 12) — Master Portfolio Sheet
    "realized_pnl_usd": FMT_CURRENCY,
    "trades_accepted": FMT_INT,
    "trades_rejected": FMT_INT,
    "rejection_rate_pct": FMT_PCT_RAW,
    "realized_vs_theoretical_pnl": FMT_FLOAT,

    # Portfolio Sheet — Additional Keys
    "reference_capital_usd": FMT_CURRENCY,
    "peak_capital_deployed": FMT_CURRENCY,
    "capital_overextension_ratio": FMT_FLOAT,
    "avg_concurrent": FMT_FLOAT,
    "max_concurrent": FMT_INT,
    "p95_concurrent": FMT_INT,
    "dd_max_concurrent": FMT_INT,
    "full_load_cluster": FMT_FLOAT,
    "avg_pairwise_corr": FMT_FLOAT,
    "max_pairwise_corr_stress": FMT_FLOAT,
    "portfolio_net_profit_low_vol": FMT_CURRENCY,
    "portfolio_net_profit_normal_vol": FMT_CURRENCY,
    "portfolio_net_profit_high_vol": FMT_CURRENCY,
    "exposure_pct": FMT_PCT_RAW,
    "equity_stability_k_ratio": FMT_FLOAT,
    "expectancy": FMT_CURRENCY
}

# Hidden Columns (SOP Auditing Fields)
HIDDEN_COLS = {
    "constituent_run_ids",
    "run_ids",
    "genome_id",
    "run_id",
    "creation_timestamp",
    "timestamp"
}

# Dropdown Columns (Column Name -> list of allowed values)
# Applied as Excel Data Validation (dropdown) on all data rows
DROPDOWN_COLS = {
    "in_portfolio": ["True", "False"],
}

# Strategy Master Filter — Preferred Column Order
# IN_PORTFOLIO moved right after return_dd_ratio for quick decision-making
STRATEGY_COLUMN_ORDER = [
    "run_id",
    "strategy",
    "symbol",
    "timeframe",
    "test_start",
    "test_end",
    "trading_period",
    "total_trades",
    "total_net_profit",
    "gross_profit",
    "gross_loss",
    "profit_factor",
    "expectancy",
    "sharpe_ratio",
    "max_drawdown",
    "max_dd_pct",
    "return_dd_ratio",
    "IN_PORTFOLIO",          # Moved here for quick pick-and-choose
    "worst_5_loss_pct",
    "longest_loss_streak",
    "pct_time_in_market",
    "avg_bars_in_trade",
    "net_profit_high_vol",
    "net_profit_normal_vol",
    "net_profit_low_vol",
    "net_profit_asia",
    "net_profit_london",
    "net_profit_ny",
    "net_profit_strong_up",
    "net_profit_weak_up",
    "net_profit_neutral",
    "net_profit_weak_down",
    "net_profit_strong_down",
    "trades_strong_up",
    "trades_weak_up",
    "trades_neutral",
    "trades_weak_down",
    "trades_strong_down",
]

# ==========================================================
# LOGIC
# ==========================================================

def apply_formatting(file_path, profile):
    path = Path(file_path)
    if not path.exists():
        print(f"[ERROR] File not found: {file_path}")
        sys.exit(1)

    print(f"[INFO] Formatting {path.name} (Profile: {profile})...")

    # Pre-step: Column Reorder + Sort by Return/DD Ratio (pandas-based)
    try:
        import pandas as pd
        df = pd.read_excel(path)

        # --- Sort by return_dd_ratio (descending) ---
        sort_col = None
        if profile == "strategy" and "return_dd_ratio" in df.columns:
            sort_col = "return_dd_ratio"
        elif profile == "portfolio" and "return_dd_ratio" in df.columns:
            sort_col = "return_dd_ratio"

        if sort_col:
            df[sort_col] = pd.to_numeric(df[sort_col], errors="coerce")
            df = df.sort_values(by=sort_col, ascending=False, na_position="last")
            df = df.reset_index(drop=True)

            # Add/update rank column (1-based)
            df.insert(0, "rank", range(1, len(df) + 1)) if "rank" not in df.columns else df.__setitem__("rank", range(1, len(df) + 1))
            print(f"  [RANKED] Sorted by {sort_col} descending ({len(df)} rows)")

        # --- Column Reorder (strategy only) ---
        col_order = None
        if profile == "strategy" and STRATEGY_COLUMN_ORDER:
            # Prepend rank to the order
            col_order = ["rank"] + STRATEGY_COLUMN_ORDER

        if col_order:
            existing = df.columns.tolist()
            ordered = [c for c in col_order if c in existing]
            remaining = [c for c in existing if c not in ordered]
            new_order = ordered + remaining
            if new_order != existing:
                df = df[new_order]
                print(f"  [REORDER] Columns reordered ({len(ordered)} matched, {len(remaining)} appended)")

        # Save back
        df.to_excel(path, index=False)
    except Exception as e:
        print(f"  [WARN] Pre-processing skipped: {e}")

    try:
        wb = openpyxl.load_workbook(path)
        
        # Styles Objects
        header_fill = PatternFill(start_color=HEADER_FILL_COLOR, end_color=HEADER_FILL_COLOR, fill_type="solid")
        header_font = Font(bold=True, color=HEADER_FONT_COLOR)
        alt_row_fill = PatternFill(start_color=ALT_ROW_FILL_COLOR, end_color=ALT_ROW_FILL_COLOR, fill_type="solid")
        
        # Iterate over ALL sheets
        for ws in wb.worksheets:
            print(f"  [INFO] Processing sheet: {ws.title}")
            
            # 1. Header & Column ID Mapping
            col_map = {} # col_index -> col_name_lower
            max_col = ws.max_column
            max_row = ws.max_row
            
            for col_idx in range(1, max_col + 1):
                cell = ws.cell(row=1, column=col_idx)
                val = str(cell.value).lower().strip() if cell.value else ""
                col_map[col_idx] = val
                
                # Header Styling
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

            # 2. Row Iteration (Data)
            for row_idx in range(2, max_row + 1):
                is_alt = (row_idx % 2 == 0)
                
                # Special Logic for Transposed Summary
                # If Sheet is "Performance Summary", Column 1 is Metric Name.
                # Use that to determine format for Col 2, 3...
                row_metric_fmt = None
                if ws.title == "Performance Summary":
                     metric_name = str(ws.cell(row=row_idx, column=1).value).lower().strip()
                     row_metric_fmt = FORMAT_MAP.get(metric_name)
                    
                for col_idx in range(1, max_col + 1):
                    cell = ws.cell(row=row_idx, column=col_idx)
                    col_name = col_map.get(col_idx, "")
                    
                    # Alternating Row Shading
                    if is_alt:
                        cell.fill = alt_row_fill
                    
                    # Formatting & Alignment
                    fmt = None
                    
                    # Strategy A: Column Header Match (Normal Sheets)
                    if col_name in FORMAT_MAP:
                        fmt = FORMAT_MAP[col_name]
                        
                    # Strategy B: Row Metric Match (Transposed Summary) -- Value Columns Only (Col > 1)
                    elif row_metric_fmt and col_idx > 1:
                        fmt = row_metric_fmt
                        
                    if fmt:
                        cell.number_format = fmt
                        cell.alignment = Alignment(horizontal="right")
                    else:
                        # Default Left Align for text/other (unless it's a value col in summary, assume right? No, stick to default)
                        # Actually for Summary Column 1 (headers), left is good.
                        if row_metric_fmt and col_idx > 1:
                             cell.alignment = Alignment(horizontal="right") # Align unformatted numbers right too
                        else:
                             cell.alignment = Alignment(horizontal="left")

            # 3. Header Row Height (tall enough for 2-line wrapped headers)
            ws.row_dimensions[1].height = HEADER_ROW_HEIGHT

            # 4. Column Widths & Hiding
            for col_idx in range(1, max_col + 1):
                col_name = col_map.get(col_idx, "")
                col_letter = get_column_letter(col_idx)
                
                # Hide specific columns
                if col_name in HIDDEN_COLS:
                    ws.column_dimensions[col_letter].hidden = True
                    continue

                # Measure max data width from sample rows
                max_data_len = 0
                is_numeric_col = False
                sample_rows = list(range(2, min(max_row, 50) + 1))
                
                for r in sample_rows:
                    cell = ws.cell(row=r, column=col_idx)
                    val = cell.value
                    if val is not None:
                        if isinstance(val, (int, float)):
                            is_numeric_col = True
                            max_data_len = max(max_data_len, len(f"{val:.2f}"))
                        else:
                            max_data_len = max(max_data_len, len(str(val)))

                # Header length — use longest word if wrapping
                header_text = str(ws.cell(row=1, column=col_idx).value or "")
                header_words = header_text.replace("_", " ").split()
                longest_word = max((len(w) for w in header_words), default=0)

                # Width = max(longest header word, data width) + padding
                if is_numeric_col:
                    width = max(max_data_len + 2, longest_word + 2)
                    width = max(width, 10)   # minimum for numbers
                    width = min(width, 16)   # cap tight for numbers
                else:
                    width = max(max_data_len + 2, longest_word + 2)
                    width = max(width, 8)    # minimum for text
                    width = min(width, 28)   # cap for text
                    
                ws.column_dimensions[col_letter].width = width

            # 5. Dropdown Data Validation
            for col_idx in range(1, max_col + 1):
                col_name = col_map.get(col_idx, "")
                if col_name in DROPDOWN_COLS:
                    options = DROPDOWN_COLS[col_name]
                    formula = '"' + ','.join(options) + '"'
                    dv = DataValidation(
                        type="list",
                        formula1=formula,
                        allow_blank=True,
                        showDropDown=False,  # False = SHOW the dropdown arrow
                    )
                    dv.prompt = f"Select {col_name}"
                    dv.promptTitle = col_name
                    col_letter = get_column_letter(col_idx)
                    dv.add(f"{col_letter}2:{col_letter}{max_row}")
                    ws.add_data_validation(dv)
                    print(f"    [DROPDOWN] {col_name} (col {col_letter}): {options}")

            # 4. Freeze Header
            ws.freeze_panes = "A2"
        
        wb.save(path)
        print("[SUCCESS] Formatting complete.")
        
    except Exception as e:
        print(f"[FATAL] Formatting failed: {e}")
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="Unified Excel Formatter")
    parser.add_argument("--file", required=True, help="Path to Excel file")
    parser.add_argument("--profile", required=True, choices=["strategy", "portfolio"], help="Formatting profile")
    
    args = parser.parse_args()
    
    apply_formatting(args.file, args.profile)

if __name__ == "__main__":
    main()
