"""
format_excel_artifact.py — Unified Excel Formatter & Rounding Governance

Applies strict styling and number formatting to Excel artifacts.
Logic is presentation-layer only. No data mutation.

Usage:
    python tools/format_excel_artifact.py --file <path> --profile <strategy|portfolio>
"""

import argparse
import sys
import openpyxl
from pathlib import Path
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

# ==========================================================
# CONSTANTS
# ==========================================================

# Styling
HEADER_FILL_COLOR = "4472C4"  # Lighter Blue (SOP Governance)
HEADER_FONT_COLOR = "FFFFFF"
ALT_ROW_FILL_COLOR = "DCE6F1"

# Number Formats
FMT_CURRENCY = "#,##0.00"   # USD (2 decimals, comma)
FMT_PERCENT = "0.0%"        # Percent ratio (0.1234 -> 12.3%)
FMT_PCT_RAW = "0.0\"%\""    # Raw percent number (65.24 -> 65.2%)
FMT_FLOAT = "0.00"          # Ratio/Float (2 decimals: 1.23)
FMT_INT = "0"               # Integer

# Header display
HEADER_ROW_HEIGHT = 36       # Tall enough for 2-line wrapped headers
MAX_HEADER_LINE_LEN = 14     # Wrap headers wider than this

# Column Rules (Column Name -> Format)
# Keys should be lower-case for matching
FORMAT_MAP = {
    # Rank (auto-generated by formatter)
    "rank": FMT_INT,

    # Trades List Headers (Human Readable)
    "pnl (usd)": FMT_CURRENCY,
    "entry price": FMT_FLOAT,
    "exit price": FMT_FLOAT,
    "bars held": FMT_INT,
    
    # Summary Metrics (Human Readable - Lowercase)
    "net profit (usd)": FMT_CURRENCY,
    "gross profit (usd)": FMT_CURRENCY,
    "gross loss (usd)": FMT_CURRENCY,
    "starting capital": FMT_CURRENCY,
    "max drawdown (usd)": FMT_CURRENCY,
    "largest win (usd)": FMT_CURRENCY,
    "largest loss (usd)": FMT_CURRENCY,
    "expectancy (usd)": FMT_CURRENCY,
    "avg trade (usd)": FMT_CURRENCY,
    "avg win (usd)": FMT_CURRENCY,
    "avg loss (usd)": FMT_CURRENCY,
    
    "max drawdown (%)": FMT_PERCENT,
    "% profitable": FMT_PERCENT,
    "% of gross profit (top trades)": FMT_PERCENT,
    "worst 5 trades loss %": FMT_PERCENT,
    "return on capital": FMT_PERCENT,
    "% time in market": FMT_PERCENT,
    
    "profit factor": FMT_FLOAT,
    "sharpe ratio": FMT_FLOAT,
    "sortino ratio": FMT_FLOAT,
    "k-ratio": FMT_FLOAT,
    "sqn (system quality number)": FMT_FLOAT,
    "return / drawdown ratio": FMT_FLOAT,
    "return retracement ratio": FMT_FLOAT,
    "avg mfe (r)": FMT_FLOAT,
    "avg mae (r)": FMT_FLOAT,
    "edge ratio (mfe / mae)": FMT_FLOAT,
    "win/loss ratio": FMT_FLOAT,
    "avg bars in winning trades": FMT_FLOAT,
    "avg bars in losing trades": FMT_FLOAT,
    "avg bars per trade": FMT_FLOAT,
    
    # Strategy Master Filter Keys (Stage-3)
    "total_net_profit": FMT_CURRENCY,
    "expectancy": FMT_CURRENCY,
    "sharpe_ratio": FMT_FLOAT,
    "return_dd_ratio": FMT_FLOAT,
    "worst_5_loss_pct": FMT_PERCENT,
    "max_drawdown": FMT_CURRENCY, # "max_dd_usd" is legacy
    "longest_loss_streak": FMT_INT,
    "pct_time_in_market": FMT_PERCENT,
    "avg_bars_in_trade": FMT_FLOAT,
    "net_profit_high_vol": FMT_CURRENCY,
    "net_profit_normal_vol": FMT_CURRENCY,
    "net_profit_low_vol": FMT_CURRENCY,
    
    # Legacy / Internal Keys (Keep for compatibility)
    "net_pnl_usd": FMT_CURRENCY,
    "realized_pnl": FMT_CURRENCY,
    "theoretical_pnl": FMT_CURRENCY,
    "net_profit": FMT_CURRENCY, 
    "theoretical_pnl": FMT_CURRENCY,
    "net_profit": FMT_CURRENCY, 
    "gross_profit": FMT_CURRENCY,
    "gross_loss": FMT_CURRENCY,
    "max_dd_usd": FMT_CURRENCY,
    "max_dd_pct": FMT_PCT_RAW,
    "win_rate": FMT_PCT_RAW,
    "sharpe": FMT_FLOAT,
    "profit_factor": FMT_FLOAT,
    "total_trades": FMT_INT,
    "sqn": FMT_FLOAT,
    "edge_quality": FMT_FLOAT,
    "trade_density": FMT_INT,
    "profile_trade_density": FMT_INT,
    "winning_trades": FMT_INT,
    "losing_trades": FMT_INT,
    "max_consec_wins": FMT_INT,
    "max_consec_losses": FMT_INT,
    "consecutive_wins": FMT_INT,
    "consecutive_losses": FMT_INT,

    # Profile Selector (Step 12) — Master Portfolio Sheet
    "trades_accepted": FMT_INT,
    "trades_rejected": FMT_INT,
    "rejection_rate_pct": FMT_PCT_RAW,
    "realized_vs_theoretical_pnl": FMT_FLOAT,

    # Portfolio Sheet — Additional Keys
    "reference_capital_usd": FMT_CURRENCY,
    "peak_capital_deployed": FMT_CURRENCY,
    "capital_overextension_ratio": FMT_FLOAT,
    "avg_concurrent": FMT_FLOAT,
    "max_concurrent": FMT_INT,
    "p95_concurrent": FMT_INT,
    "dd_max_concurrent": FMT_INT,
    "full_load_cluster": FMT_FLOAT,
    "avg_pairwise_corr": FMT_FLOAT,
    "max_pairwise_corr_stress": FMT_FLOAT,
    "portfolio_net_profit_low_vol": FMT_CURRENCY,
    "portfolio_net_profit_normal_vol": FMT_CURRENCY,
    "portfolio_net_profit_high_vol": FMT_CURRENCY,
    "exposure_pct": FMT_PCT_RAW,
    "equity_stability_k_ratio": FMT_FLOAT,
    "expectancy": FMT_CURRENCY,

    # Single-Asset Composites — Regime-Aware Metrics
    "n_strategies": FMT_INT,
    "activation_rate_pct": FMT_PCT_RAW,
    "regime_blocked_trades": FMT_INT,
    "blocked_pnl_raw": FMT_CURRENCY,
}

# Hidden Columns (SOP Auditing Fields)
HIDDEN_COLS = {
    "constituent_run_ids",
    "run_ids",
    "genome_id",
    "run_id",
    "creation_timestamp",
    "timestamp",
    "source_strategy",   # Redundant with portfolio_id
    "parsed_fields",     # JSON blob — machine-readable, not for visual inspection
    "total_trades",      # trade_density provides equivalent information
}

# Columns with short text values — override text width logic to be data-driven (universal)
NARROW_TEXT_COLS = {
    "portfolio_engine_version",
    "timeframe",
}

# Explicit width overrides — bypass auto-sizing for specific columns (column_name_lower -> width)
COLUMN_WIDTH_OVERRIDES = {
    "portfolio_id": 22,   # IDs are 35-44 chars; 22 shows family+asset+timeframe, saves space
    "strategy":     26,   # Strategy names are long; 26 is a comfortable readable cap
    "rank":          6,   # 1-3 digit values; header wraps fine
    "exit_spread":  12,   # 6 decimal places (e.g. 0.000120)
    "net_pnl":      12,   # 6 decimal places (e.g. -0.001234)
}

# Dropdown Columns (Column Name -> list of allowed values)
# Applied as Excel Data Validation (dropdown) on all data rows
DROPDOWN_COLS = {
    "in_portfolio": ["True", "False"],
    "candidate_status": ["CORE", "WATCH", "FAIL", "BURN_IN", "RBIN"],
}

# Strategy Master Filter — Preferred Column Order
# IN_PORTFOLIO moved right after return_dd_ratio for quick decision-making
STRATEGY_COLUMN_ORDER = [
    "run_id",
    "strategy",
    "symbol",
    "asset_class",
    "timeframe",
    "test_start",
    "test_end",
    "trading_period",
    "sqn",
    "total_trades",
    "trade_density",
    "total_net_profit",
    "gross_profit",
    "gross_loss",
    "profit_factor",
    "expectancy",
    "sharpe_ratio",
    "max_drawdown",
    "max_dd_pct",
    "return_dd_ratio",
    "IN_PORTFOLIO",          # Moved here for quick pick-and-choose
    "candidate_status",
    "worst_5_loss_pct",
    "longest_loss_streak",
    "pct_time_in_market",
    "avg_bars_in_trade",
    "net_profit_high_vol",
    "net_profit_normal_vol",
    "net_profit_low_vol",
    "net_profit_asia",
    "net_profit_london",
    "net_profit_ny",
    "net_profit_strong_up",
    "net_profit_weak_up",
    "net_profit_neutral",
    "net_profit_weak_down",
    "net_profit_strong_down",
    "trades_strong_up",
    "trades_weak_up",
    "trades_neutral",
    "trades_weak_down",
    "trades_strong_down",
]

# Portfolio Ledger — Preferred Column Orders
# Keep rank out of canonical order so reference_capital remains column C.
# Multi-asset ("Portfolios" tab)
PORTFOLIO_COLUMN_ORDER = [
    "portfolio_id",
    "source_strategy",
    "reference_capital_usd",
    "portfolio_status",
    "evaluation_timeframe",
    "trade_density",
    "profile_trade_density",
    "theoretical_pnl",
    "realized_pnl",
    "sharpe",
    "max_dd_pct",
    "return_dd_ratio",
    "win_rate",
    "profit_factor",
    "expectancy",
    "total_trades",
    "exposure_pct",
    "equity_stability_k_ratio",
    "deployed_profile",
    "edge_quality",
    "trades_accepted",
    "trades_rejected",
    "rejection_rate_pct",
    "realized_vs_theoretical_pnl",
    "peak_capital_deployed",
    "capital_overextension_ratio",
    "avg_concurrent",
    "max_concurrent",
    "p95_concurrent",
    "dd_max_concurrent",
    "full_load_cluster",
    "avg_pairwise_corr",
    "max_pairwise_corr_stress",
    "portfolio_net_profit_low_vol",
    "portfolio_net_profit_normal_vol",
    "portfolio_net_profit_high_vol",
    "parsed_fields",
    "portfolio_engine_version",
    "creation_timestamp",
    "constituent_run_ids",
]

# Single-asset ("Single-Asset Composites" tab)
# Drops correlation, regime-gate, and full_load columns (meaningless for single asset).
# Adds n_strategies.
SINGLE_ASSET_COLUMN_ORDER = [
    "portfolio_id",
    "source_strategy",
    "reference_capital_usd",
    "portfolio_status",
    "evaluation_timeframe",
    "n_strategies",
    "trade_density",
    "profile_trade_density",
    "theoretical_pnl",
    "realized_pnl",
    "sharpe",
    "max_dd_pct",
    "return_dd_ratio",
    "win_rate",
    "profit_factor",
    "expectancy",
    "total_trades",
    "exposure_pct",
    "equity_stability_k_ratio",
    "deployed_profile",
    "sqn",
    "trades_accepted",
    "trades_rejected",
    "rejection_rate_pct",
    "realized_vs_theoretical_pnl",
    "peak_capital_deployed",
    "capital_overextension_ratio",
    "avg_concurrent",
    "max_concurrent",
    "p95_concurrent",
    "dd_max_concurrent",
    "portfolio_net_profit_low_vol",
    "portfolio_net_profit_normal_vol",
    "portfolio_net_profit_high_vol",
    "parsed_fields",
    "portfolio_engine_version",
    "creation_timestamp",
    "constituent_run_ids",
]

# Display-only header renames for portfolio profile.
# Column keys in DataFrames and code stay unchanged — this only affects
# what the user sees in the Excel header row.
PORTFOLIO_HEADER_DISPLAY = {
    "sharpe": "sharpe (ann.)",
    "equity_stability_k_ratio": "k_ratio (log)",
}

# ==========================================================
# LOGIC
# ==========================================================

def apply_formatting(file_path, profile):
    path = Path(file_path)
    if not path.exists():
        print(f"[ERROR] File not found: {file_path}")
        sys.exit(1)

    print(f"[INFO] Formatting {path.name} (Profile: {profile})...")

    # Pre-step: Column Reorder + Sort by Return/DD Ratio (pandas-based)
    # IMPORTANT: only run on single-sheet ledgers; multi-sheet AK reports must be preserved.
    try:
        import pandas as pd

        xl = pd.ExcelFile(path)
        sheet_names = xl.sheet_names

        # Portfolio workbooks may have multiple data sheets (Portfolios,
        # Single-Asset Composites) — process each independently.
        _PORTFOLIO_DATA_SHEETS = {"Portfolios", "Single-Asset Composites"}
        _is_portfolio_multi = (profile == "portfolio"
                               and any(s in _PORTFOLIO_DATA_SHEETS for s in sheet_names))

        if _is_portfolio_multi or len(sheet_names) == 1:
            # Determine which sheets to process
            if _is_portfolio_multi:
                _sheets_to_process = [s for s in sheet_names
                                      if s in _PORTFOLIO_DATA_SHEETS]
            else:
                _sheets_to_process = [sheet_names[0]]

            _all_dfs = {}  # sheet_name -> processed df
            # Load non-data sheets (Notes, etc.) for preservation
            _preserve_sheets = [s for s in sheet_names
                                if s not in _PORTFOLIO_DATA_SHEETS
                                and (_is_portfolio_multi or s != sheet_names[0])]

            for sheet_name in _sheets_to_process:
                df = pd.read_excel(path, sheet_name=sheet_name)

                # --- Sort by return_dd_ratio (descending) ---
                sort_col = None
                if "return_dd_ratio" in df.columns:
                    sort_col = "return_dd_ratio"

                if sort_col:
                    df[sort_col] = pd.to_numeric(df[sort_col], errors="coerce")
                    df = df.sort_values(by=sort_col, ascending=False, na_position="last")
                    df = df.reset_index(drop=True)

                    # Add/update rank column (1-based, independent per sheet)
                    if "rank" not in df.columns:
                        df.insert(0, "rank", range(1, len(df) + 1))
                    else:
                        df["rank"] = range(1, len(df) + 1)
                    print(f"  [RANKED] {sheet_name}: Sorted by {sort_col} descending ({len(df)} rows)")

                # --- Column Reorder ---
                col_order = None
                if profile == "strategy" and STRATEGY_COLUMN_ORDER:
                    col_order = ["rank"] + STRATEGY_COLUMN_ORDER
                elif profile == "portfolio":
                    if sheet_name == "Single-Asset Composites":
                        col_order = SINGLE_ASSET_COLUMN_ORDER
                    else:
                        col_order = PORTFOLIO_COLUMN_ORDER

                if col_order:
                    existing = df.columns.tolist()
                    ordered = [c for c in col_order if c in existing]
                    remaining = [c for c in existing if c not in ordered]
                    new_order = ordered + remaining
                    if new_order != existing:
                        df = df[new_order]
                        print(f"  [REORDER] {sheet_name}: Columns reordered ({len(ordered)} matched, {len(remaining)} appended)")

                _all_dfs[sheet_name] = df

            # Save all processed sheets back.
            with pd.ExcelWriter(path, engine="openpyxl", mode="w") as writer:
                for sname, sdf in _all_dfs.items():
                    sdf.to_excel(writer, sheet_name=sname, index=False)
                # Preserve non-data sheets (will be re-created by notes pass, but
                # keep existing content if notes pass doesn't run)
                for ps in _preserve_sheets:
                    try:
                        pdf = pd.read_excel(xl, sheet_name=ps)
                        pdf.to_excel(writer, sheet_name=ps, index=False)
                    except Exception:
                        pass
        else:
            print(f"  [INFO] Pre-processing skipped (multi-sheet workbook: {len(sheet_names)} sheets)")
    except Exception as e:
        print(f"  [WARN] Pre-processing skipped: {e}")

    try:
        wb = openpyxl.load_workbook(path)
        
        # Styles Objects
        header_fill = PatternFill(start_color=HEADER_FILL_COLOR, end_color=HEADER_FILL_COLOR, fill_type="solid")
        header_font = Font(bold=True, color=HEADER_FONT_COLOR)
        alt_row_fill = PatternFill(start_color=ALT_ROW_FILL_COLOR, end_color=ALT_ROW_FILL_COLOR, fill_type="solid")
        
        # Iterate over ALL sheets (skip Notes — managed by --notes-type)
        for ws in wb.worksheets:
            if ws.title == "Notes":
                print(f"  [INFO] Skipping sheet: {ws.title} (managed by --notes-type)")
                continue
            print(f"  [INFO] Processing sheet: {ws.title}")
            
            # 1. Header & Column ID Mapping
            col_map = {} # col_index -> col_name_lower
            max_col = ws.max_column
            max_row = ws.max_row
            
            for col_idx in range(1, max_col + 1):
                cell = ws.cell(row=1, column=col_idx)
                val = str(cell.value).lower().strip() if cell.value else ""
                col_map[col_idx] = val

                # Portfolio profile: add clarification comments (NOT renames —
                # renaming headers causes column-name collisions when the evaluator
                # appends new rows with the canonical column names).
                if profile == "portfolio" and val in PORTFOLIO_HEADER_DISPLAY:
                    from openpyxl.comments import Comment
                    note = {"sharpe": "Annualized (x √252)", "equity_stability_k_ratio": "Computed on log(daily equity)"}
                    cell.comment = Comment(note.get(val, PORTFOLIO_HEADER_DISPLAY[val]), "System")

                # Header Styling
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

            # 2. Row Iteration (Data)
            for row_idx in range(2, max_row + 1):
                is_alt = (row_idx % 2 == 0)
                
                # Special Logic for Transposed Summary
                # If Sheet is "Performance Summary", Column 1 is Metric Name.
                # Use that to determine format for Col 2, 3...
                row_metric_fmt = None
                if ws.title == "Performance Summary":
                     metric_name = str(ws.cell(row=row_idx, column=1).value).lower().strip()
                     row_metric_fmt = FORMAT_MAP.get(metric_name)
                    
                for col_idx in range(1, max_col + 1):
                    cell = ws.cell(row=row_idx, column=col_idx)
                    col_name = col_map.get(col_idx, "")
                    
                    # Alternating Row Shading
                    if is_alt:
                        cell.fill = alt_row_fill
                    
                    # Formatting & Alignment
                    fmt = None
                    
                    # Strategy A: Column Header Match (Normal Sheets)
                    if col_name in FORMAT_MAP:
                        fmt = FORMAT_MAP[col_name]
                        
                    # Strategy B: Row Metric Match (Transposed Summary) -- Value Columns Only (Col > 1)
                    elif row_metric_fmt and col_idx > 1:
                        fmt = row_metric_fmt
                        
                    if fmt:
                        cell.number_format = fmt
                        cell.alignment = Alignment(horizontal="right")
                    else:
                        # Default Left Align for text/other (unless it's a value col in summary, assume right? No, stick to default)
                        # Actually for Summary Column 1 (headers), left is good.
                        if row_metric_fmt and col_idx > 1:
                             cell.alignment = Alignment(horizontal="right") # Align unformatted numbers right too
                        else:
                             cell.alignment = Alignment(horizontal="left")

            # 3. Header Row Height (tall enough for 2-line wrapped headers)
            ws.row_dimensions[1].height = HEADER_ROW_HEIGHT

            # 4. Column Widths & Hiding
            for col_idx in range(1, max_col + 1):
                col_name = col_map.get(col_idx, "")
                col_letter = get_column_letter(col_idx)
                
                # Hide specific columns
                if col_name in HIDDEN_COLS:
                    ws.column_dimensions[col_letter].hidden = True
                    continue

                # Measure max data width from sample rows
                max_data_len = 0
                is_numeric_col = False
                sample_rows = list(range(2, min(max_row, 50) + 1))
                
                for r in sample_rows:
                    cell = ws.cell(row=r, column=col_idx)
                    val = cell.value
                    if val is not None:
                        if isinstance(val, (int, float)):
                            is_numeric_col = True
                            max_data_len = max(max_data_len, len(f"{val:.2f}"))
                        else:
                            max_data_len = max(max_data_len, len(str(val)))

                # Header length — use longest word if wrapping
                header_text = str(ws.cell(row=1, column=col_idx).value or "")
                header_words = header_text.replace("_", " ").split()
                longest_word = max((len(w) for w in header_words), default=0)

                # Width: numeric columns are data-driven (headers wrap, so longest_word
                # is not a hard floor). Text columns retain header-word floor, except
                # known short-value text columns which are also data-driven.
                is_narrow_text = col_name in NARROW_TEXT_COLS
                if is_numeric_col or is_narrow_text:
                    width = max(max_data_len + 2, 6)   # data-driven, small floor
                    width = min(width, 16)              # cap tight for numbers
                else:
                    width = max(max_data_len + 2, longest_word + 2)
                    width = max(width, 8)    # minimum for text
                    width = min(width, 28)   # cap for text
                    
                # Apply explicit override if defined
                if col_name in COLUMN_WIDTH_OVERRIDES:
                    width = COLUMN_WIDTH_OVERRIDES[col_name]

                ws.column_dimensions[col_letter].width = width

            # 5. Dropdown Data Validation
            for col_idx in range(1, max_col + 1):
                col_name = col_map.get(col_idx, "")
                if col_name in DROPDOWN_COLS:
                    options = DROPDOWN_COLS[col_name]
                    formula = '"' + ','.join(options) + '"'
                    dv = DataValidation(
                        type="list",
                        formula1=formula,
                        allow_blank=True,
                        showDropDown=False,  # False = SHOW the dropdown arrow
                    )
                    dv.prompt = f"Select {col_name}"
                    dv.promptTitle = col_name
                    col_letter = get_column_letter(col_idx)
                    dv.add(f"{col_letter}2:{col_letter}{max_row}")
                    ws.add_data_validation(dv)
                    print(f"    [DROPDOWN] {col_name} (col {col_letter}): {options}")

            # 6. Portfolio composition comments on column A (portfolio_id)
            if profile == "portfolio" and col_map.get(1, "") == "portfolio_id":
                import json as _json, re as _re, csv as _csv
                from openpyxl.comments import Comment as _Comment
                _strat_root = path.parent
                _commented = 0
                for row_idx in range(2, max_row + 1):
                    pid = str(ws.cell(row=row_idx, column=1).value or "")
                    if not pid:
                        continue
                    _eval_dir = _strat_root / pid / "portfolio_evaluation"
                    _assets = None
                    # Source 1: evaluated_assets from metadata/summary JSON
                    for _fname in ("portfolio_metadata.json", "portfolio_summary.json"):
                        _fp = _eval_dir / _fname
                        if _fp.exists():
                            try:
                                with open(_fp, encoding="utf-8") as _f:
                                    _d = _json.load(_f)
                                _assets = _d.get("evaluated_assets")
                                if _assets:
                                    break
                            except Exception:
                                pass
                    # Source 2: extract from trade-level CSV strategy_name (symbol = last segment)
                    if not _assets:
                        _tl = _eval_dir / "portfolio_tradelevel.csv"
                        if _tl.exists():
                            try:
                                import pandas as _pd
                                _tdf = _pd.read_csv(_tl, usecols=["strategy_name"])
                                _syms = set()
                                for _sn in _tdf["strategy_name"].dropna().unique():
                                    _last = str(_sn).split("_")[-1]
                                    if _re.match(r"^[A-Za-z0-9]{4,}$", _last):
                                        _syms.add(_last.upper())
                                if _syms:
                                    _assets = sorted(_syms)
                            except Exception:
                                pass
                    if _assets and isinstance(_assets, list):
                        _text = " | ".join(str(a).upper() for a in _assets)
                        ws.cell(row=row_idx, column=1).comment = _Comment(_text, "System")
                        _commented += 1
                print(f"    [COMMENTS] Portfolio composition added to column A ({_commented}/{max_row - 1} rows)")

            # 4. Freeze Header (and column A for portfolio — keeps portfolio_id visible)
            ws.freeze_panes = "B2" if profile == "portfolio" else "A2"
            if max_col >= 1 and max_row >= 1:
                ws.auto_filter.ref = f"A1:{get_column_letter(max_col)}{max_row}"

                # Pre-select portfolio_status=CORE/WATCH for portfolio sheets
                if profile == "portfolio":
                    _headers_lower = [str(c.value).lower() if c.value else "" for c in ws[1]]
                    if "portfolio_status" in _headers_lower:
                        from openpyxl.worksheet.filters import FilterColumn, Filters
                        _ps_idx = _headers_lower.index("portfolio_status")
                        _fc = FilterColumn(colId=_ps_idx)
                        _fc.filters = Filters(filter=["CORE", "WATCH"])
                        ws.auto_filter.filterColumn.append(_fc)
                        _ps_col = _ps_idx + 1  # 1-based
                        _hidden_count = 0
                        for _r in range(2, max_row + 1):
                            _val = str(ws.cell(row=_r, column=_ps_col).value or "")
                            if _val not in ("CORE", "WATCH"):
                                ws.row_dimensions[_r].hidden = True
                                _hidden_count += 1
                        print(f"    [FILTER] Pre-selected portfolio_status=CORE/WATCH (hidden {_hidden_count} FAIL rows)")

                # Pre-select event_type=EXIT filter for shadow_trades files
                _fname = Path(path).stem.lower()
                if "shadow_trade" in _fname:
                    _headers_lower = [str(c.value).lower() if c.value else "" for c in ws[1]]
                    if "event_type" in _headers_lower:
                        from openpyxl.worksheet.filters import FilterColumn, Filters
                        _et_idx = _headers_lower.index("event_type")
                        _fc = FilterColumn(colId=_et_idx)
                        _fc.filters = Filters(filter=["EXIT"])
                        ws.auto_filter.filterColumn.append(_fc)
                        # openpyxl sets filter metadata but does NOT hide rows —
                        # Excel may or may not re-apply on open. Explicitly hide
                        # non-EXIT rows so the filter is visually applied on save.
                        _et_col = _et_idx + 1  # 1-based for cell access
                        _hidden_count = 0
                        for _r in range(2, max_row + 1):
                            _val = str(ws.cell(row=_r, column=_et_col).value or "")
                            if _val != "EXIT":
                                ws.row_dimensions[_r].hidden = True
                                _hidden_count += 1
                        print(f"    [FILTER] Pre-selected event_type=EXIT on column {_et_idx} (hidden {_hidden_count} non-EXIT rows)")
        
        # Portfolio profile: preserve existing Notes sheet if present (generated by
        # --notes-type portfolio). Only create the legacy 4-line Notes if none exists.
        if profile == "portfolio":
            if "Notes" not in wb.sheetnames:
                ns = wb.create_sheet("Notes")
                notes_lines = [
                    "Metric Notes — Portfolio Sheet",
                    "",
                    "Sharpe: daily-return based, annualized (x sqrt(252)). Stage 2 Sharpe is trade-level (mean PnL / stdev), non-annualized. Values are not comparable.",
                    "K-Ratio: computed on log(daily equity). Stage 2 K-Ratio uses cumulative trade PnL (linear). Values are not comparable.",
                    "max_dd_pct: decimal fraction (0..1), negative sign. Filter sheets use positive 0..100 scale.",
                ]
                for row_idx, line in enumerate(notes_lines, start=1):
                    ns.cell(row=row_idx, column=1, value=line)
                ns.cell(row=1, column=1).font = Font(bold=True)
                ns.column_dimensions["A"].width = 120

        # ── Hyperlink restoration ──────────────────────────────────────────
        # Applied here (last openpyxl step) so hyperlinks survive any upstream
        # pandas rewrite.  Config: column_name → link_prefix (relative to file).
        _HYPERLINK_MAP = {
            "Filtered_Strategies_Passed": {"strategy": "../backtests/"},
            "Master_Portfolio_Sheet":     {"portfolio_id": ""},
        }
        _LINK_FONT = Font(color="0563C1", underline="single")
        _file_stem = Path(path).stem
        _hl_conf = _HYPERLINK_MAP.get(_file_stem, {})
        if _hl_conf:
            # Apply hyperlinks to ALL data sheets (not just the first).
            _data_sheets = [s for s in wb.sheetnames if s != "Notes"]
            for _sheet_name in _data_sheets:
                _ws = wb[_sheet_name]
                _max_row = _ws.max_row or 1
                _max_col = _ws.max_column or 1
                # Build header map for this sheet
                _hdr = {str(_ws.cell(row=1, column=c).value or "").strip(): c
                        for c in range(1, _max_col + 1)}
                for _hl_col_name, _hl_prefix in _hl_conf.items():
                    _hl_col_idx = _hdr.get(_hl_col_name)
                    if _hl_col_idx is None:
                        continue
                    _hl_count = 0
                    for _r in range(2, _max_row + 1):
                        _cell = _ws.cell(row=_r, column=_hl_col_idx)
                        _val = str(_cell.value or "").strip()
                        if not _val:
                            continue
                        _cell.hyperlink = f"{_hl_prefix}{_val}/"
                        _cell.font = _LINK_FONT
                        _hl_count += 1
                    if _hl_count:
                        print(f"    [HYPERLINKS] {_sheet_name} / {_hl_col_name}: {_hl_count} links applied")

        wb.save(path)
        print("[SUCCESS] Formatting complete.")
        
    except Exception as e:
        print(f"[FATAL] Formatting failed: {e}")
        sys.exit(1)

def add_notes_sheet_to_ledger(file_path: str, sheet_type: str) -> None:
    """
    Append a 'Notes' sheet to an aggregate ledger Excel file.

    sheet_type:
      "master_filter" — Strategy_Master_Filter.xlsx (Stage-3 raw aggregation)
      "candidates"    — Filtered_Strategies_Passed.xlsx (promotion-filtered + classified)
      "portfolio"     — Master_Portfolio_Sheet.xlsx (multi-symbol portfolio evaluations)

    Thresholds are sourced from:
      candidates  → filter_strategies._compute_candidate_status() and mask
      portfolio   → portfolio_evaluator._compute_portfolio_status()
    No logic is redefined; constants are reproduced here for display only.
    """
    from openpyxl import load_workbook

    # ── Classification thresholds per sheet type ──────────────────────────────
    # candidates: promotion mask (filter_strategies.py lines 165–172)
    PROMO_MIN_TRADES   = 40
    PROMO_MIN_PF       = 1.05
    PROMO_MIN_RET_DD   = 0.6
    PROMO_MIN_EXP      = 0.0
    PROMO_MIN_SHARPE   = 0.3
    PROMO_MAX_DD_PCT   = 80.0

    # candidates: candidate_status rules (filter_strategies._compute_candidate_status)
    CAND_FAIL_TRADES   = 50
    CAND_FAIL_DD       = 40.0
    CAND_FAIL_EXP_FX   = 0.15   # FX expectancy FAIL gate (USD/trade)
    CAND_FAIL_EXP_XAU  = 0.50   # XAU expectancy FAIL gate (3.3x FX)
    CAND_FAIL_EXP_BTC  = 0.50   # BTC/crypto expectancy FAIL gate (3.3x FX)
    CAND_FAIL_EXP_IDX  = 0.50   # INDEX expectancy FAIL gate (3.0-3.8x FX)
    CAND_CORE_TRADES   = 200
    CAND_CORE_RET_DD   = 2.0
    CAND_CORE_SHARPE   = 1.5
    CAND_CORE_MAX_DD   = 30.0
    CAND_CORE_DENSITY  = 50
    CAND_CORE_PF       = 1.25

    # portfolio: portfolio_status rules (portfolio_evaluator._compute_portfolio_status)
    PORT_FAIL_PNL      = 0.0
    PORT_FAIL_TRADES   = 50
    PORT_FAIL_DENSITY  = 50
    PORT_FAIL_EXP_FX   = 0.15   # Same gates as candidates (min-lot basis)
    PORT_FAIL_EXP_XAU  = 0.50
    PORT_FAIL_EXP_BTC  = 0.50
    PORT_FAIL_EXP_IDX  = 0.50
    PORT_CORE_PNL      = 1000.0
    PORT_CORE_TRADES   = 200
    PORT_CORE_REJ_MAX  = 30.0

    try:
        wb = load_workbook(file_path)
    except Exception as e:
        print(f"[WARN] Notes sheet skipped — cannot open {file_path}: {e}")
        return

    if "Notes" in wb.sheetnames:
        del wb["Notes"]
    ws = wb.create_sheet("Notes")

    bold   = Font(bold=True, size=10)
    header = Font(bold=True, size=11)
    normal = Font(size=10)

    r = 1

    def _w(row, col, value, font=None):
        c = ws.cell(row=row, column=col, value=value)
        if font:
            c.font = font

    # ── Section 1: Sheet Purpose ──────────────────────────────────────────────
    _w(r, 1, "SECTION 1 — SHEET PURPOSE", header); r += 1

    if sheet_type == "master_filter":
        _w(r, 1,
           "Strategy_Master_Filter.xlsx — Raw Stage-3 aggregation of all completed backtest runs. "
           "Every run that completes Stage 1→3 is written here. No promotion filter applied. "
           "Rows are keyed by run_id and are append-only (existing rows never modified).",
           normal); r += 2

    elif sheet_type == "candidates":
        _w(r, 1,
           "Filtered_Strategies_Passed.xlsx — Candidate ledger. Contains all strategies that passed "
           "the promotion criteria gate. Rows are append-only (strategies that once passed are "
           "never evicted). Each row carries a candidate_status classification.",
           normal); r += 2

    elif sheet_type == "portfolio":
        _w(r, 1,
           "Master_Portfolio_Sheet.xlsx — Portfolio evaluation ledger. Two data tabs: "
           "'Portfolios' (multi-asset, 2+ symbols) and 'Single-Asset Composites' "
           "(single symbol, multiple strategies). Each row is evaluated through the "
           "capital wrapper and deployed profile selector. Append-only; explicit human "
           "authorization required to modify an existing entry. "
           "Rankings are independent per tab — scores are not compared across types.",
           normal); r += 2

    # ── Section 2: Inclusion / Promotion Criteria ─────────────────────────────
    _w(r, 1, "SECTION 2 — INCLUSION CRITERIA", header); r += 1
    _w(r, 1, "Condition", bold); _w(r, 2, "Threshold", bold); r += 1

    if sheet_type == "master_filter":
        for cond, val in [
            ("All Stage-3 completed runs",          "No filter — everything included"),
            ("Deduplication key",                   "run_id (one row per backtest run)"),
            ("Row mutation policy",                 "Append-only — rows never modified after write"),
        ]:
            _w(r, 1, cond, normal); _w(r, 2, val, normal); r += 1

    elif sheet_type == "candidates":
        for cond, val in [
            ("Total Trades",         f">= {PROMO_MIN_TRADES}"),
            ("Profit Factor",        f">= {PROMO_MIN_PF}"),
            ("Return / DD Ratio",    f">= {PROMO_MIN_RET_DD}"),
            ("Expectancy (USD)",     f">= {PROMO_MIN_EXP}"),
            ("Sharpe Ratio",         f">= {PROMO_MIN_SHARPE}"),
            ("Max Drawdown (%)",     f"<= {PROMO_MAX_DD_PCT:.0f}%"),
        ]:
            _w(r, 1, cond, normal); _w(r, 2, val, normal); r += 1

    elif sheet_type == "portfolio":
        for cond, val in [
            ("All strategies evaluated through Stage 4+",  "No promotion filter"),
            ("Deduplication key",                          "portfolio_id (append-only)"),
            ("Overwrite policy",                           "BLOCKED — requires explicit human authorization"),
        ]:
            _w(r, 1, cond, normal); _w(r, 2, val, normal); r += 1
    r += 1

    # ── Section 3: Classification Rules ───────────────────────────────────────
    _w(r, 1, "SECTION 3 — CLASSIFICATION RULES", header); r += 1

    if sheet_type in ("master_filter", "candidates"):
        _w(r, 1, "candidate_status", bold); r += 1
        _w(r, 1, "Class", bold); _w(r, 2, "Rule", bold); r += 1
        for cls, rule in [
            ("FAIL",
             f"Total Trades < {CAND_FAIL_TRADES}  OR  Max Drawdown (%) > {CAND_FAIL_DD:.0f}  "
             f"OR  expectancy below asset-class gate"),
            ("",
             f"  Expectancy FAIL gates (logic-driven from broker spread/slippage ratios):  "
             f"FX < ${CAND_FAIL_EXP_FX}  |  XAU < ${CAND_FAIL_EXP_XAU}  |  BTC < ${CAND_FAIL_EXP_BTC}  |  INDEX < ${CAND_FAIL_EXP_IDX}"),
            ("CORE",
             f"Total Trades >= {CAND_CORE_TRADES}  AND  Return/DD >= {CAND_CORE_RET_DD}  AND  Sharpe >= {CAND_CORE_SHARPE}  AND  Max DD <= {CAND_CORE_MAX_DD:.0f}%  AND  Trade Density >= {CAND_CORE_DENSITY}  AND  PF >= {CAND_CORE_PF}  (and not FAIL)"),
            ("WATCH",
             "Does not meet CORE criteria; not FAIL; not present in TS_Execution/portfolio.yaml"),
            ("BURN_IN",
             "Present in TS_Execution/portfolio.yaml with enabled=true — overrides computed status. "
             "BURN_IN promotion thresholds: FX >= $0.25  |  XAU >= $0.80  |  BTC >= $0.80  |  INDEX >= $0.80"),
            ("RBIN",
             "Removed from Burn-In. Strategy entered live burn-in but failed the Edge Quality Gate "
             "(Section 18 robustness suite). Reverted to research pool for rework."),
        ]:
            _w(r, 1, cls, bold); _w(r, 2, rule, normal); r += 1

        if sheet_type == "master_filter":
            r += 1
            _w(r, 1,
               "Note: candidate_status is computed in Filtered_Strategies_Passed.xlsx (filter_strategies.py). "
               "This sheet (Strategy_Master_Filter) holds raw aggregated metrics only.",
               Font(italic=True, size=9))
            r += 1

    elif sheet_type == "portfolio":
        _w(r, 1, "portfolio_status", bold); r += 1
        _w(r, 1, "Class", bold); _w(r, 2, "Rule", bold); r += 1
        for cls, rule in [
            ("FAIL",
             f"Realized PnL <= ${PORT_FAIL_PNL:.0f}  OR  Accepted Trades < {PORT_FAIL_TRADES}  "
             f"OR  Trade Density < {PORT_FAIL_DENSITY} (per-symbol)  "
             f"OR  expectancy below asset-class gate"),
            ("",
             f"  Expectancy FAIL gates (same as candidates, min-lot basis):  "
             f"FX < ${PORT_FAIL_EXP_FX}  |  XAU < ${PORT_FAIL_EXP_XAU}  |  BTC < ${PORT_FAIL_EXP_BTC}  |  INDEX < ${PORT_FAIL_EXP_IDX}  |  MIXED (PF_ composites): no gate"),
            ("",
             "  Note on PF_ composites: Asset class is detected from portfolio_id keywords. "
             "PF_ hash-based IDs (multi-strategy portfolios) cannot be classified from the name alone. "
             "Their expectancy is a trade-count-weighted average across mixed asset classes, so "
             "per-class gates do not apply. If needed, constituent asset classes can be inspected "
             "in portfolio_metadata.json under evaluated_assets."),
            ("CORE (Portfolios tab)",
             f"Realized PnL > ${PORT_CORE_PNL:.0f}  AND  Accepted Trades >= {PORT_CORE_TRADES}  AND  Rejection Rate <= {PORT_CORE_REJ_MAX:.0f}%  AND  edge_quality >= 0.12"),
            ("CORE (Single-Asset tab)",
             f"Realized PnL > ${PORT_CORE_PNL:.0f}  AND  Accepted Trades >= {PORT_CORE_TRADES}  AND  Rejection Rate <= {PORT_CORE_REJ_MAX:.0f}%  AND  SQN >= 2.5"),
            ("WATCH (Portfolios tab)",
             "Passes all FAIL gates  AND  edge_quality >= 0.08  (but not CORE)"),
            ("WATCH (Single-Asset tab)",
             "Passes all FAIL gates  AND  SQN >= 2.0  (but not CORE)"),
        ]:
            _w(r, 1, cls, bold); _w(r, 2, rule, normal); r += 1
    r += 1

    # ── Section 4: Key Column Glossary ────────────────────────────────────────
    _w(r, 1, "SECTION 4 — KEY COLUMN GLOSSARY", header); r += 1
    _w(r, 1, "Column", bold); _w(r, 2, "Definition", bold); r += 1

    if sheet_type in ("master_filter", "candidates"):
        glossary = [
            ("run_id",           "Unique identifier for the backtest run (immutable once written)"),
            ("strategy",         "Full strategy ID including symbol suffix"),
            ("profit_factor",    "Gross profit / gross loss across all trades"),
            ("sharpe_ratio",     "Risk-adjusted return (mean trade PnL / std dev), trade-level"),
            ("max_dd_pct",       "Maximum drawdown as positive percentage (e.g. 3.18 = 3.18%)"),
            ("return_dd_ratio",  "Net profit / max drawdown — primary risk-efficiency metric"),
            ("total_trades",     "Number of completed trades in the backtest period"),
            ("expectancy",       "Average expected PnL per trade (USD) at min-lot (0.01). "
                                  "Computed in Stage 1 as sum(pnl_usd)/total_trades where pnl_usd uses "
                                  "broker min_lot (0.01) x contract_size. This normalizes all strategies "
                                  "to the same position size for apples-to-apples comparison. "
                                  "Deployed lot sizes (risk-based) produce proportionally larger PnL."),
            ("sqn",              "System Quality Number: sqrt(N) × mean(R) / stdev(R, ddof=1). "
                                  "Van Tharp metric for individual trading systems. "
                                  "Thresholds: <1.5 FAIL, 1.5–2.5 WATCH, ≥2.5 required for CORE."),
            ("IN_PORTFOLIO",     "True if strategy is active in TS_Execution/portfolio.yaml"),
            ("candidate_status", "CORE / WATCH / FAIL / BURN_IN / RBIN — see Section 3"),
        ]
    else:
        glossary = [
            ("portfolio_id",                "Unique portfolio identifier"),
            ("theoretical_pnl",             "Raw Stage-4 aggregated PnL before sizing/rejection"),
            ("realized_pnl",                "Actual PnL after deployed profile sizing rules"),
            ("deployed_profile",            "Capital sizing profile selected by profile_selector"),
            ("expectancy",                  "Trade-count-weighted average PnL per trade (USD) at min-lot (0.01). "
                                            "Equals sum(pnl_usd)/total_trades across ALL constituent symbols. "
                                            "NOT the simple average of per-symbol expectancies — symbols with "
                                            "more trades naturally weight more. Computed from Stage 1 results "
                                            "at broker min_lot; deployed profile lot sizes are much larger."),
            ("sharpe",                      "Portfolio-level Sharpe ratio"),
            ("max_dd_pct",                  "Maximum portfolio drawdown as positive percentage"),
            ("return_dd_ratio",             "Realized PnL / max drawdown"),
            ("edge_quality",                "mean(R) / stdev(R) — edge consistency metric for portfolios. "
                                            "Unlike SQN, omits sqrt(N) so portfolios with different trade "
                                            "counts are directly comparable. "
                                            "Thresholds: <0.05 weak (edge ≈ noise), 0.05–0.10 moderate, "
                                            "0.10–0.15 good, >0.15 strong. "
                                            "Values >0.25 with low trade counts may indicate overfitting."),
            ("sqn",                         "System Quality Number: sqrt(N) × mean(R) / stdev(R, ddof=1). "
                                            "Van Tharp metric for individual trading systems. "
                                            "Thresholds: <1.6 poor, 1.6–2.0 average, 2.0–3.0 good, >3.0 excellent. "
                                            "Single-Asset tab only — see edge_quality for Portfolios tab."),
            ("rejection_rate_pct",          "Percentage of trades rejected by leverage/heat cap"),
            ("avg_concurrent",              "Average number of simultaneously open positions"),
            ("max_concurrent",              "Peak simultaneous open positions"),
            ("avg_pairwise_corr",           "Average correlation between constituent strategy equity curves"),
            ("portfolio_status",            "CORE / WATCH / FAIL — see Section 3"),
            ("parsed_fields",               "JSON decomposition of portfolio_id tokens "
                                            "(idea_id, family, symbol, timeframe, model, filter, sweep, "
                                            "variant, param_set, asset_class). Hidden column."),
            ("n_strategies",                "Number of constituent strategies (Single-Asset tab only)"),
        ]

    for col_name, definition in glossary:
        _w(r, 1, col_name, normal); _w(r, 2, definition, normal); r += 1
    r += 1

    # ── Section 5: Deployed Profile Reference (portfolio only) ────────────────
    if sheet_type == "portfolio":
        _w(r, 1, "SECTION 5 — DEPLOYED PROFILE SELECTION", header); r += 2

        # 5a. Available profiles
        _w(r, 1, "Available Capital Profiles", bold); r += 1
        _w(r, 1, "Profile", bold); _w(r, 2, "Lot Sizing Approach", bold); r += 1
        for pname, desc in [
            ("RAW_MIN_LOT_V1",
             "Unconditional min lot (0.01). Every signal executes regardless of risk. "
             "Baseline measurement only."),
            ("DYNAMIC_V1",
             "Heat-aware dynamic scaling. risk_per_trade=0.5%, heat_cap=3%, "
             "leverage_cap=15x. Scales down when heat cap is breached."),
            ("CONSERVATIVE_V1",
             "Fixed fractional: equity x 0.25%. heat_cap=4%, leverage_cap=5x. "
             "Smallest risk per trade."),
            ("FIXED_USD_V1",
             "Fixed $50 USD risk per trade. heat_cap=4%, leverage_cap=11x."),
            ("MIN_LOT_FALLBACK_V1",
             "Fixed $50 USD with min-lot override when optimal sizing < min lot. "
             "max_risk_multiple=3.0 (capped)."),
            ("MIN_LOT_FALLBACK_UNCAPPED_V1",
             "Fixed $50 USD with min-lot override (uncapped). "
             "No risk multiple cap."),
            ("BOUNDED_MIN_LOT_V1",
             "Fixed $65 USD with conservative min-lot override. "
             "max_risk_multiple=1.5 (tightest cap)."),
        ]:
            _w(r, 1, pname, normal); _w(r, 2, desc, normal); r += 1
        r += 1

        # 5b. Selection algorithm
        _w(r, 1, "Selection Algorithm", bold); r += 1
        _w(r, 1, "Step", bold); _w(r, 2, "Description", bold); r += 1
        for step, desc in [
            ("1. Hard Filter",
             "Remove profiles with realized_pnl <= 0, "
             "capital_validity_flag = False, or avg_risk_multiple > 1.5."),
            ("2. Reliability Pool",
             "Prefer profiles with >= 50 accepted trades AND >= 1.0 sim years (reliable pool). "
             "Fall back to hard-valid-only pool if none qualify."),
            ("3. Score",
             "base_score = realized_pnl / max(max_drawdown_usd, 1.0). "
             "Penalized by execution health: "
             "rejection <= 30% = 1.0x, 30-60% = 0.7x, > 60% = 0.4x."),
            ("4. Rank",
             "Sort by: (1) highest score, (2) lowest rejection rate, "
             "(3) most accepted trades, (4) alphabetical name."),
            ("5. Stabilize",
             "Profiles within 15% of best score are considered tied. "
             "Tied candidates re-ranked by rejection rate and trade count."),
            ("6. Persist",
             "If a previous profile exists and scores >= 85% of the new best, "
             "keep the previous profile to avoid flip-flopping."),
        ]:
            _w(r, 1, step, normal); _w(r, 2, desc, normal); r += 1
        r += 1

    # ── Column widths ─────────────────────────────────────────────────────────
    ws.column_dimensions["A"].width = 30
    ws.column_dimensions["B"].width = 72

    try:
        wb.save(file_path)
        print(f"[NOTES] Notes sheet added ({sheet_type}) -> {Path(file_path).name}")
    except Exception as e:
        print(f"[WARN] Notes sheet could not be saved: {e}")


def main():
    parser = argparse.ArgumentParser(description="Unified Excel Formatter")
    parser.add_argument("--file", required=True, help="Path to Excel file")
    parser.add_argument("--profile", choices=["strategy", "portfolio"], default=None, help="Formatting profile")
    parser.add_argument("--notes-type", choices=["master_filter", "candidates", "portfolio"],
                        default=None, help="If set, append a Notes sheet of this type (skips formatting)")

    args = parser.parse_args()

    if args.notes_type:
        add_notes_sheet_to_ledger(args.file, args.notes_type)
    elif args.profile:
        apply_formatting(args.file, args.profile)
        # Auto-generate Notes for portfolio profile so it never regresses.
        if args.profile == "portfolio":
            add_notes_sheet_to_ledger(args.file, "portfolio")
    else:
        parser.error("--profile is required when --notes-type is not specified")

if __name__ == "__main__":
    main()
