"""Generate tools/TOOLS_INDEX.md -- a disk-derived inventory of every module
under tools/.

This REPLACES the former hand-maintained index. It lists every .py file under
tools/ (excluding __init__.py), grouped by directory, with the first line of
each module's docstring. Docstrings are read via ast (no import, no execution),
so this is safe to run anywhere and never triggers script-on-import side
effects.

Scope is INVENTORY ONLY: no classification, health checks, orphan detection,
or usage data. Output is deterministic (no timestamp) so regeneration is a
no-op diff whenever the tool set is unchanged.

Usage:
    python -m tools.generate_tools_index            # regenerate + write
    python -m tools.generate_tools_index --check    # exit 1 if out of sync (no write)

Auto-refresh: tools/system_introspection.py calls regenerate() at the end of
its run, so the index is refreshed during the session-close flow (step 3.10).
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

TOOLS_ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = TOOLS_ROOT.parent
INDEX_PATH = TOOLS_ROOT / "TOOLS_INDEX.md"

_MAX_SUMMARY = 140

_HEADER = """# TradeScan Tools Index

> AUTO-GENERATED by `tools/generate_tools_index.py` -- do not edit by hand.
> Regenerate: `python -m tools.generate_tools_index`
> (also auto-runs at session-close via `tools/system_introspection.py`, step 3.10).
>
> Inventory only: every `.py` under `tools/` grouped by directory, with its
> one-line module docstring. No classification, health, orphan, or usage data.

## Tool execution convention

Tools run as Python modules from the repository root:

```bash
python -m tools.run_pipeline <DIRECTIVE_ID>
python -m tools.control_panel --list
python -m tools.robustness.cli <PF_ID> --suite full
```

Top-level modules are operational entrypoints; modules under subpackages
(`orchestration/`, `robustness/`, `portfolio_core/`, `capital_engine/`,
`utils/`, `system_logging/`, `state_lifecycle/`) are internal libraries.
"""

_FOOTER_RULES = """## Tool governance rules

- This index is AUTO-GENERATED from disk -- do not hand-add tools; they appear
  automatically on regeneration.
- One-off scripts belong in `tools/tmp/`. If a `tmp/` script becomes reused,
  move it to a permanent location.
- Tools must not contain core engine logic. Engines belong in `engines/` or
  `engine_dev/`, not `tools/`.
- Any tool that mutates an Excel ledger MUST delegate styling to
  `format_excel_artifact.py` (no direct `openpyxl` imports).
- Tools must encode UTF-8 on every file read/write (enforced by `lint_encoding`).
- Tools must never hardcode absolute user paths (enforced by
  `lint_no_hardcoded_paths`).
"""


def _docstring_summary(path: Path) -> str:
    """First non-empty line of a module's docstring, via ast (no execution)."""
    try:
        tree = ast.parse(path.read_bytes(), filename=str(path))
    except SyntaxError:
        return "(parse error)"
    doc = ast.get_docstring(tree)
    if not doc:
        return "(no docstring)"
    for raw in doc.splitlines():
        line = raw.strip()
        if line:
            line = line.replace("|", "\\|")  # keep markdown table intact
            if len(line) > _MAX_SUMMARY:
                line = line[: _MAX_SUMMARY - 3] + "..."
            return line
    return "(no docstring)"


def _dotted(rel: Path) -> str:
    """tools/orchestration/runner.py -> tools.orchestration.runner"""
    return "tools." + ".".join(rel.with_suffix("").parts)


def _group_key(rel: Path) -> str:
    if len(rel.parts) == 1:
        return "tools/ (top-level)"
    return "tools/" + "/".join(rel.parts[:-1]) + "/"


def build_index() -> str:
    """Build the full TOOLS_INDEX.md content deterministically (no I/O write)."""
    modules = sorted(
        p for p in TOOLS_ROOT.rglob("*.py") if p.name != "__init__.py"
    )
    groups: dict[str, list[Path]] = {}
    for path in modules:
        rel = path.relative_to(TOOLS_ROOT)
        groups.setdefault(_group_key(rel), []).append(rel)

    def _order(key: str) -> tuple[int, str]:
        # top-level first, then subpackage directories alphabetically
        return (0, "") if key == "tools/ (top-level)" else (1, key)

    out: list[str] = [_HEADER, ""]
    out.append(f"Total modules indexed: {len(modules)} (excludes `__init__.py`).")
    out.append("")

    for key in sorted(groups, key=_order):
        rels = sorted(groups[key])
        out.append(f"## {key}  ({len(rels)} modules)")
        out.append("")
        out.append("| Module | Summary |")
        out.append("|---|---|")
        for rel in rels:
            out.append(f"| `{_dotted(rel)}` | {_docstring_summary(TOOLS_ROOT / rel)} |")
        out.append("")

    out.append(_FOOTER_RULES)
    return "\n".join(out).rstrip() + "\n"


def regenerate(write: bool = True) -> Path:
    """Build the index and (by default) write it to tools/TOOLS_INDEX.md."""
    content = build_index()
    if write:
        INDEX_PATH.write_text(content, encoding="utf-8", newline="\n")
    return INDEX_PATH


def _check() -> int:
    fresh = build_index()
    if not INDEX_PATH.exists():
        print("[DRIFT] TOOLS_INDEX.md does not exist; run the generator.")
        return 1
    current = INDEX_PATH.read_text(encoding="utf-8")
    if current == fresh:
        print("[OK] TOOLS_INDEX.md is in sync with tools/ on disk.")
        return 0
    print(
        "[DRIFT] TOOLS_INDEX.md is stale vs tools/ on disk. "
        "Regenerate: python -m tools.generate_tools_index"
    )
    return 1


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate or verify tools/TOOLS_INDEX.md (disk-derived inventory)."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare the on-disk index to a fresh build; exit 1 if stale (no write).",
    )
    args = parser.parse_args()

    if args.check:
        sys.exit(_check())

    path = regenerate(write=True)
    print(f"[DONE] TOOLS_INDEX.md written: {path}")


if __name__ == "__main__":
    main()
