"""Generate governance/recycle_rules/rule_code_hashes.yaml.

Pins each registered recycle-rule's `name@version` to the canonical (LF-
normalized) sha256 of the module file that implements it. namespace_gate reads
this sidecar and rejects a basket directive whose rule code has drifted from
its registered version — making the registry's append-only "version is part of
the basket strategy hash" guarantee MECHANICAL instead of convention-only.

The sidecar is kept SEPARATE from registry.yaml on purpose: the registry is a
hand-authored, comment-rich spec/doc; this file is machine-generated (mirrors
the tools_manifest.json / GUARD_FILES split, so the documented registry is
never clobbered by a machine rewrite).

HUMAN-ONLY: like tools/generate_guard_manifest.py, this blesses code. Run it
only to backfill, or when a rule's code LEGITIMATELY changed AND its version
was bumped (append-only) or an in-place fix was intentionally accepted.
Unauthorized regeneration defeats the gate.

Usage:
    python tools/generate_recycle_rule_hashes.py
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from tools.basket_provenance import (  # noqa: E402
    RULE_CODE_HASHES_PATH,
    recycle_rule_code_sha256,
)
from tools.recycle_rules import RULE_CLASSES  # noqa: E402

_HEADER = (
    "# Machine-generated by tools/generate_recycle_rule_hashes.py (HUMAN-ONLY).\n"
    "# Do NOT hand-edit. Pins each recycle rule_name@version to the canonical\n"
    "# (LF) sha256 of its module file; namespace_gate rejects basket directives\n"
    "# whose rule code drifted from its registered version. Regenerate only when\n"
    "# a rule's code legitimately changed AND its version was bumped (append-\n"
    "# only), or to accept an intended in-place fix.\n"
)


def main() -> int:
    print("=" * 60)
    print("RECYCLE-RULE CODE-HASH GENERATOR")
    print("=" * 60)

    hashes: dict[str, str] = {}
    for name, version in sorted(RULE_CLASSES.keys()):
        key = f"{name}@{version}"
        h = recycle_rule_code_sha256(name, version)
        hashes[key] = h
        print(f"  [HASH] {key:34s} {h[:16]}...")

    payload = {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "hashes": hashes,
    }
    RULE_CODE_HASHES_PATH.parent.mkdir(parents=True, exist_ok=True)
    RULE_CODE_HASHES_PATH.write_text(
        _HEADER + yaml.safe_dump(payload, sort_keys=False), encoding="utf-8"
    )
    print(f"\n[DONE] Wrote {len(hashes)} rule hashes to "
          f"{RULE_CODE_HASHES_PATH.relative_to(PROJECT_ROOT)}")
    print("[INFO] Stage + commit the sidecar to make the pins durable.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
