"""
02_VOL_XAUUSD_1H_VOLEXP_TRENDFILT_S04_V1_P00 — Generated by Strategy Provisioner
Timestamp: 2026-03-10T19:07:48.886652
Directive: 02_VOL_XAUUSD_1H_VOLEXP_TRENDFILT_S04_V1_P00
"""

# --- IMPORTS (Deterministic from Directive) ---
from indicators.structure.ema_slope import ema_slope
from indicators.structure.highest_high import highest_high
from indicators.volatility.atr import atr
from indicators.momentum.rsi import rsi
from indicators.volatility.volatility_regime import volatility_regime
from engines.filter_stack import FilterStack

class Strategy:

    # --- IDENTITY ---
    name = "02_VOL_XAUUSD_1H_VOLEXP_TRENDFILT_S04_V1_P00"
    timeframe = "1h"

    # --- STRATEGY SIGNATURE START ---
    STRATEGY_SIGNATURE = {
    "execution_rules": {
        "entry_logic": {
            "atr_length": 14,
            "condition": "ema_slope_50_up_AND_three_lower_closes_AND_break_hh2_shift1",
            "lookback_bars": 2,
            "type": "intersection"
        },
        "entry_when_flat_only": True,
        "exit_logic": {
            "price_exit": "rsi2_above_85",
            "time_exit_bars": 15,
            "type": "dynamic_or_time"
        },
        "pyramiding": False,
        "reset_on_exit": True,
        "stop_loss": {
            "atr_multiplier": 2.1,
            "type": "atr_multiple"
        },
        "trailing_stop": {
            "enabled": False
        }
    },
    "indicators": [
        "indicators.structure.ema_slope",
        "indicators.structure.highest_high",
        "indicators.volatility.atr",
        "indicators.momentum.rsi",
        "indicators.volatility.volatility_regime"
    ],
    "order_placement": {
        "execution_timing": "next_bar_open",
        "type": "market"
    },
    "signature_version": 2,
    "trade_management": {
        "direction": "long_only",
        "reentry": {
            "allowed": False
        }
    },
    "volatility_filter": {
        "enabled": True,
        "operator": "gte",
        "required_regime": 0
    }
}
    # --- STRATEGY SIGNATURE END ---

    _TIME_EXIT_BARS = 15
    _ATR_MULTIPLIER = 2.1

    def __init__(self):
        self.filter_stack = FilterStack(self.STRATEGY_SIGNATURE)

    def prepare_indicators(self, df):
        df['atr'] = atr(df, window=14)
        vr = volatility_regime(df['atr'], window=100)
        df['volatility_regime'] = vr['regime']

        # EMA(50) slope — positive = uptrend
        df['ema_slope_50'] = ema_slope(df['close'], period=50)

        # HH(2) shifted by 1 bar for breakout confirmation
        df['hh2_shift1'] = highest_high(df['high'], window=2, shift=1)

        # Previous 3 closes for lower-close pullback check
        df['close_1'] = df['close'].shift(1)
        df['close_2'] = df['close'].shift(2)
        df['close_3'] = df['close'].shift(3)

        # RSI(2) for exit
        df['rsi2'] = rsi(df['close'], period=2)

        return df

    def check_entry(self, ctx):
        if not self.filter_stack.allow_trade(ctx):
            return None

        row = ctx.row

        # Volatility filter: regime >= 0 (NORMAL or HIGH, exclude LOW=-1)
        vol_regime = row.get('volatility_regime')
        if vol_regime is None or vol_regime < 0:
            return None

        ema_sl    = row.get('ema_slope_50')
        hh2_s1    = row.get('hh2_shift1')
        close     = row.get('close')
        high      = row.get('high')
        close_1   = row.get('close_1')
        close_2   = row.get('close_2')
        close_3   = row.get('close_3')

        if any(v is None for v in [ema_sl, hh2_s1, close, high, close_1, close_2, close_3]):
            return None

        # Condition 1: EMA(50) slope is positive (uptrend)
        if ema_sl <= 0:
            return None

        # Condition 2: Three consecutive lower closes (pullback)
        if not (close < close_1 < close_2):
            return None

        # Condition 3: Current bar breaks above HH(2) of prior bars
        if high <= hh2_s1:
            return None

        return {"signal": 1}

    def check_exit(self, ctx):
        row = ctx.row

        # Time exit
        if ctx.bars_held >= self._TIME_EXIT_BARS:
            return True

        # Price exit: RSI(2) crosses above 85 (overbought — take profit)
        rsi2 = row.get('rsi2')
        if rsi2 is not None and rsi2 > 85:
            return True

        return False
